### ISSUE TITLE
[ELE-1483] On the Dashboard the table is blank for the generic test which run against source table

### ISSUE THREAD

**Issue by minhajpasha** [elementary-data/elementary#1009]
**Describe the bug**

**To Reproduce**
schema.yml

version: 2
sources:

* name: raw_layers
  tables:
  * name: raw_customers
    tests:
    * customer_date_sequence_check:
      tags:
      \- customers_sequence_precheck

test/customer_date_sequence_check.sql

{% test customer_date_sequence_check(model) %}

SQL to test customer created should be greater than current date in raw_customers table

{% endtest %}

**Expected behaviour**

on UI under -->test results

table name should be raw_customers

**Screenshots**

![](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/caacf0cd-9c4e-46b9-92f0-0f55947a2743/c78ef826-52f2-4588-8529-8d38d4749f69)

**Environment (please complete the following information):**

* edr Version: \[e.g. 0.5.3\], can be found by running `pip show elementary-data`
* Name: elementary-data
  Version: 0.8.2
  Summary: Data monitoring and lineage
  Home-page: [https://github.com/elementary-data/elementary](https://github.com/elementary-data/elementary)
  Author: Elementary
  Author-email: [or@elementary-data.com](mailto:or@elementary-data.com)
  License:
  Location: /Users/abcd/Library/Python/3.8/lib/python/site-packages
  Requires: alive-progress, beautifulsoup4, boto3, click, dbt-core, google-cloud-storage, networkx, packaging, posthog, pydantic, pyfiglet, pytest-parametrization, ratelimit, requests, ruamel.yaml, slack-sdk
  Required-by:
* dbt package Version: \[e.g. 0.4.1\], can be found in `packages.yml` file

**Additional context**

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-1483](https://linear.app/elementary/issue/ELE-1483/on-the-dashboard-the-table-is-blank-for-the-generic-test-which-run)</sub>

**Comment by oravi** [comment]
Hi @minhajpasha ! I believe that this [PR](https://github.com/elementary-data/dbt-data-reliability/pull/443) solves this issue. I'll close this issue once a new version is coming out with this fix.
