### ISSUE TITLE
[ELE-1434] Make `DbtRunner` install the dbt packages if needed.

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#1039]
**Is your feature request related to a problem? Please describe.**
Currently [`DbtRunner`](https://github.com/elementary-data/elementary/blob/master/elementary/clients/dbt/dbt_runner.py) is able to run against a dbt project that doesn't have its required packages installed.

**Describe the solution you'd like**
If the packages are not installed, run `dbt deps` at the constructor (`__init__`).
The code needs to ensure that the required versions are installed, and not only that the packages are installed.
It also shouldn't run `dbt deps` unnecessarily.

<sub>[ELE-1434](https://linear.app/elementary/issue/ELE-1434/make-dbtrunner-install-the-dbt-packages-if-needed)</sub>

**Comment by Arun-kc** [comment]
Hi @elongl, I would love to help with this if possible 😄

**Comment by elongl** [comment]
Hi @Arun-kc, that sounds great and definitely possible!
I've listed the requirements so feel mostly free to implement it however you see right.
One thing to mention though is that I've learned that it's not possible to do this totally accurate because dbt doesn't enforce that the `version` specified in `dbt_project.yml` is actually equivalent to the version specific in dbtHub (The dbt package repository).

Here's the flow in terms of how I see it:
1. In `DbtRunner.__init__` call `self._run_deps_if_needed()`.
2. Implement `_run_deps_if_needed` so that it read the `packages.yml` file, and for each [dbt hub package](https://docs.getdbt.com/docs/build/packages#hub-packages-recommended), check if it's installed under `dbt_packages/<package_name>`. If at least one package is _not_, run `self.deps()`.

An alternative method is to run `dbt parse` and if it fails to run `dbt deps`,
but the problem is that dbt is relatively slow and `dbt parse` might take around 2 seconds, so we'd probably aim to avoid that.

Please let me know f you have any questions, would love to help.
Thanks a lot for your willingness to contribute.

**Comment by Arun-kc** [comment]
Hi @elongl, I have drafted a PR for this issue. Could you please take a look into it? I have only considered the key `package` as of now. Do let me know if you wish to consider `local` packages as well.
