### ISSUE TITLE
[ELE-1481] Job name not populating

### ISSUE THREAD

**Issue by svyas15** [elementary-data/elementary#1059]
**Describe the bug**
In dbt invocations table the job is always blank only the job_id is populating

<sub>[ELE-1481](https://linear.app/elementary/issue/ELE-1481/job-name-not-populating)</sub>

**Comment by oravi** [comment]
Hi @svyas15 ! thanks for reaching out! are you a dbt cloud user? if so, job name is not something that is being passed automatically in dbt cloud (job ID is indeed something that is being passed automatically) - see what's supported by default in dbt cloud [here](https://docs.elementary-data.com/deployment-and-configuration/collect-job-data#which-orchestrators-are-supported). You can pass your job name to the dbt command either via `vars` or via `env vars` as documented [here](https://docs.elementary-data.com/deployment-and-configuration/collect-job-data#how-elementary-collects-jobs-metadata). 

Closing this issue for now, please feel free to say if you need further assistance or if what mentioned here doesn't solve it for you and I'll re-open the issue.

**Comment by oravi** [comment]
Hi @svyas15 ! thanks for reaching out! are you a dbt cloud user? if so, job name is not something that is being passed automatically in dbt cloud (job ID is indeed something that is being passed automatically) - see what's supported by default in dbt cloud [here](https://docs.elementary-data.com/deployment-and-configuration/collect-job-data#which-orchestrators-are-supported). You can pass your job name to the dbt command either via `vars` or via `env vars` as documented [here](https://docs.elementary-data.com/deployment-and-configuration/collect-job-data#how-elementary-collects-jobs-metadata). 

Closing this issue for now, please feel free to say if you need further assistance or if what mentioned here doesn't solve it for you and I'll re-open the issue.
