### ISSUE TITLE
HTML entities in copied query content

### ISSUE THREAD

**Issue by boblannon-fp** [elementary-data/elementary#1063]
**Describe the bug**
Characters  like `>` and `<` display correctly in the web view, but when the query is copied to the clipboard, they're still HTML entities like `&lt;` and `&gt;`.  This, obviously, creates SQL parsing errors

**To Reproduce**

1. Go to any test in the **Test Results** view
2. Click on a test
3. Copy the content of the **Result Query** field:
4. Paste the text into a text editor
5. See invalid SQL code, containing HTML entities instead of logical operators

**Expected behavior**
Valid SQL code.

**Screenshots**
![image](https://github.com/elementary-data/elementary/assets/104772492/4a90950e-57a0-45ed-a947-540a8aa42dee)

![image](https://github.com/elementary-data/elementary/assets/104772492/a74c01b9-02e1-4b8c-9903-f312908739e9)

**Environment (please complete the following information):**

- edr Version: `0.8.2`
- dbt package Version: `1.3.0`

**Additional context**

**Comment by boblannon-fp** [comment]
Ah, I see, this was already identified as a related problem in https://github.com/elementary-data/elementary/issues/965#issuecomment-1666760403

feel free to close this, or use it to track that solution, which seems to already be waiting for release :)

**Comment by Maayan-s** [comment]
Yes @boblannon-fp, will try to release it soon! 
Thanks for reporting
