### ISSUE TITLE
Elementary's Python tests are not yet supported on postgres

### ISSUE THREAD

**Issue by ischwart1** [elementary-data/elementary#1072]
**Is your feature request related to a problem? Please describe.**
I would like to use local development for dbt models and test using a postgres instance.

**Describe the solution you'd like**
I would be happy if someone can just point me to docs or the code saying which warehouses are or are not supported, searched on github and in a clone of the repo but couldnt find the term "Elementary's Python tests are not yet supported on postgres".

**Describe alternatives you've considered**
Just want to see what is supported for now, but if postgres could be supported that would be nice!

**Additional context**

**Would you be willing to contribute this feature?**
Don't think my manager wants me to :(

**Comment by Maayan-s** [comment]
Hey @ischwart1, 
Thanks for opening the issue! 
Elementary uses the dbt python interfaces, and dbt uses the options available in each data platform.
Unfortunately Postgres does not have any Python interface, so we can't really do anything about it on our end. 
So I'm closing this for now.
