### ISSUE TITLE
Gathering column descriptions as artifacts

### ISSUE THREAD

**Issue by jhasaura** [elementary-data/elementary#1086]
**Is your feature request related to a problem? Please describe.**
I aim to assess the quality of our column-level dbt documentation, enabling us to implement necessary improvements. Presently, this evaluation is not possible as elementary artifacts doesn't capture column level description. 

**Describe the solution you'd like**
Can we incorporate descriptions within the dbt_columns table? Is it feasible to extract an additional column from the current solution to fulfil this requirement?

**Describe alternatives you've considered**
As of now i don't have any alternative other than exploring Discovery API in dbt. 

**Additional context**

**Would you be willing to contribute this feature?**
I would love to but i am not sure if i've any expertise in this area.

**Comment by haritamar** [comment]
Hi @jhasaura !
Thanks for opening this issue and sorry for the super delayed response.
Description is now available as a part of the `dbt_columns` model!

Cheers,
Itamar
