### ISSUE TITLE
breakdown by a dimension to elementary.all_columns_anomalies 

### ISSUE THREAD

**Issue by Orensarfaty** [elementary-data/elementary#1127]
- elementary.all_columns_anomalies:
          severity: warn
          where_expression: " type = ('promoting_started') "
          time_bucket:
            period: day
            count: 1
          tags: ["daily"]
          
          I would like to have an option to create this test for several types and to execute a different test for each column.
          another thing is to have an option to choose only several columns that we are interested of without all columns like the name of the test because this test taking a lot of time.
          
          thanks!

**Comment by haritamar** [comment]
Hi all,
This is now available in the both the all_column_anomalies and column_anomalies tests!
The `dimensions` parameter can be used to add one or more dimension to the test.
