### ISSUE TITLE
Pydantic 2.0 Migration

### ISSUE THREAD

**Issue by DustinMoriarty** [elementary-data/elementary#1133]
**Is your feature request related to a problem? Please describe.**
Pydantic has made major breaking changes with 2.0. They have made a good migration guide. However, migration will require some work. Keeping pydantic at 1.* will prevent other libraries which have migrated to pydantic 2.0 from using elementary. We would like to include elementary as a dependency for one of our projects. However, I don't want to be prevented from upgrading Pydantic and everything else that uses Pydantic. 

**Describe the solution you'd like**
I would like to know if there is a plan for Pydantic 2.0 migration and what the timeline looks like so that we can determine if we should include elementary in our project. 

**Describe alternatives you've considered**
We have considered running Elementary in a separate python environment and calling it with the CLI only. However, this is a pretty messy solution. 

**Additional context**
https://docs.pydantic.dev/latest/migration/

**Would you be willing to contribute this feature?**
Some as time allows.

**Comment by ConstantinoSchillebeeckx** [comment]
Any progress on this by chance? This is increasingly going to be a deal breaker.

**Comment by oliver-tosky-sh** [comment]
Also curious about any updates on this!

I'm seeing two closed/reverted PRs:
- #1006 
- #1166 

and two stale PRs:

- #1005 
- #1069 

Is there a reason why the change was rolled back?

**Comment by haritamar** [comment]
Hi all,
Since this issue was last active, we added compatibility support for both pydantic v1 and v2, so either version can be installed without an issue.

Thanks,
Itamar
