### ISSUE TITLE
[ELE-41] Support for arbitrary aggregate functions

### ISSUE THREAD

**Issue by NiallRees** [elementary-data/elementary#114]
Right now it seems only possible to monitor the results of aggregate functions outlined in the column level monitors defined here: https://docs.elementary-data.com/guides/data-monitoring/tests-and-monitors-types

It would be cool to allow users to specify their own custom aggregate function. I'm thinking of a case where a user might be interested to monitor for anomalies on `count_if(col_a > col_b)` or anything else.

<sub>[ELE-41](https://linear.app/elementary/issue/ELE-41/support-for-arbitrary-aggregate-functions)</sub>

**Comment by haritamar** [comment]
Closing since a newer issue about the same topic with more details exists here:
[](https://github.com/elementary-data/elementary/issues/1255)
