### ISSUE TITLE
Median exec. time in Test Runs Report tab

### ISSUE THREAD

**Issue by Ohrusse** [elementary-data/elementary#1144]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated to not be able to track performances with  Median exec. time  of my Test runs
 
**Describe the solution you'd like**
Implement the display of the metric `Median exec. time ` ( same concept in Model runs tab)

**Describe alternatives you've considered**
alternative proposed on [slack support](https://elementary-community.slack.com/archives/C02CTC89LAX/p1693749302351119?thread_ts=1693571420.833169&cid=C02CTC89LAX) but not implemented at this moment 
<img width="772" alt="image" src="https://github.com/elementary-data/elementary/assets/62141888/c51f8063-d589-4be2-8463-d579a67511c8">

**Additional context**
When there is a model or a test which is taking long time then we are planning some refacto to ensure that we are staying with good perf.
for tests runs we are controlling that partitions are well used when there is some perf issues.

**Would you be willing to contribute this feature?**
Not expected at this moment

**Comment by haritamar** [comment]
Hi @Ohrusse ,
This now exists in the Test Runs screen!

Cheers,
Itamar
