### ISSUE TITLE
Support for environments other than `dev` and `prod`

### ISSUE THREAD

**Issue by menzenski** [elementary-data/elementary#1176]
**Is your feature request related to a problem? Please describe.**
We have six environments. One is named `dev` and one is named` prod` but there are four others. It's not ideal to be limited to `dev` and `prod` only. Two of our environments are "production" and we'd like to have them distinguished within elementary.

**Describe the solution you'd like**
Ideally we would be able to provide the name of our environment as a string, so that we are not limited to the two provided environment names.

**Describe alternatives you've considered**

**Additional context**

**Would you be willing to contribute this feature?**
Yes, happy to make an attempt. Might need some direction.

**Comment by leonardo-melo** [comment]
We would also love this feature, as @menzenski organization, we also have a bunch of environments in different regions we would like to differentiate in the dashboard. We also would be willing to help make it happen.

**Comment by noaKurman** [comment]
Hey @menzenski ! 
Would love to help you get started on it
Our final goal is to get the env name from the env mentioned in the invocations table (We assume we have the env and project names already saved in our tables, so to make it more efficient we want to automatically receive it from there) 
**BUT** as we understand this is a bit more complicated and this feature is required by a lot of users we can start from a very simple "step 1" solution - which would just be removing the `Choice` from the CLI (if you look at the file containing all the flags you'll see `env` is only getting a choice between `dev` and `prod`, we can turn it into a string for free text) 

Is that clear? Do you need me to give you more details about which files we're talking about and what are the steps for this change?

**Comment by leonardo-melo** [comment]
For us the second option ("step 1"), would be more than enough, to just pass our desired string to the cli option.

**Comment by willbowditch** [comment]
I've opened a PR for this here: https://github.com/elementary-data/elementary/pull/1373
