### ISSUE TITLE
Issue on docs - typo

### ISSUE THREAD

**Issue by giletich-municorn** [elementary-data/elementary#1215]
Path: /quickstart/generate-report-ui
"invoation" typo

**Comment by Maayan-s** [comment]
Thanks for reporting @giletich-municorn !
There are buttons in the bottom of each page for quick edit suggestions:
<img width="178" alt="image" src="https://github.com/elementary-data/elementary/assets/22072028/2975f119-c29a-4dbf-8932-8d6ab472bce8">
