### ISSUE TITLE
More options for alerting channels such as Teams, Mail, or Webhooks in general

### ISSUE THREAD

**Issue by ramonvermeulen** [elementary-data/elementary#1228]
**Is your feature request related to a problem? Please describe.**
At our current client we are using elementary however the client is not using slack. It would be nice to have more options for alerting channels, such as Teams, Mail, or webhooks in general.

**Describe the solution you'd like**
More implementations for alerting channels.

**Describe alternatives you've considered**
Setting up something on my own to query the tables generated by elementary and use that for alerting.

**Additional context**
-

**Would you be willing to contribute this feature?**
I would like to, however I think it is a lot of work to do on my own.

**Comment by FrankTub** [comment]
One of the things blocking our migration at Beequip from `re_data` to `elementary` is that we do not have a direct way to alert end users. Our end users all have teams or are reachable through mail, but they do not use/want Slack. For us this would be of great help if this would be implemented.

**Comment by 16bzwiener** [comment]
We are having a similar issue at my company. Without an alerting mechanism for Teams we aren't able to realize the full value of Elementary.

**Comment by ellakz** [comment]
Hello! 
Teams integration was implemented by @FrankTub and available starting Elementary 0.14.0
We also created an integration README guide for contributing more integrations, and you can suggest specific integrations in new issues or talk to us on Slack if you want to contribute :)
Closing this one because it's a little broad
