### ISSUE TITLE
Add tags on tests to the tests filter on the elementary report

### ISSUE THREAD

**Issue by clairetaylor352** [elementary-data/elementary#1241]
**Is your feature request related to a problem? Please describe.**
The "tags" feature for filtering tests only applies to models, not tests.
I have added some tags at an individual test level - I do not want all tests on the model to have this tag. 
It would be nice to have the tags appear on the LHS so that I can filter the tests by this tag.

**Describe the solution you'd like**
I'd like to see tags on the LHS here that are only applied to tests in addition to the existing ones, and have them filter the test results on the central panel.
**Describe alternatives you've considered**
I'm getting round it by naming my tests with the tag name in them so I can filter on the name. But @a13xa1v35 agreed it would be a nice idea to add :-)

**Additional context**
Here's the screenshot so you know where I'm talking about.
![image (20)](https://github.com/elementary-data/elementary/assets/7215217/0b931b64-d16a-4e40-b21b-28f15e97b618)

**Would you be willing to contribute this feature?**
I could give it a try but I'm not sure when I'd get round to it! If you think it would be straightforward let me know.

**Comment by haritamar** [comment]
Test tags are available now in the test results page!
The column needs to be selected on the right for it to show:
<img width="179" alt="image" src="https://github.com/elementary-data/elementary/assets/11314965/5155c958-06ec-42b6-8b6c-cd27ba9aa42a">
