### ISSUE TITLE
Error when I try to run edr report-----------------------[FileNotFoundError: [Errno 2] No such file or directory: 'dbt_packages\\dbt-data-reliability-0.12.0\\integration_tests\\deprecated_tests\\macros\\unit_tests\\test_adapter_specific_macros_have_default_implementation.sql']

### ISSUE THREAD

**Issue by ayodelephillips** [elementary-data/elementary#1261]
Hi All,

I am currently trying out elementary.

My packages.yaml looks like this
![image](https://github.com/elementary-data/dbt-data-reliability/assets/29655984/c191d018-804a-4f26-bc11-6e5977305fd4).

Each time I do 'edr report', I get the following error message
![image](https://github.com/elementary-data/dbt-data-reliability/assets/29655984/11606f1c-bb5f-4402-b967-9475baf4dcdb)

I have run 'dbt deps' and 'dbt clean' severally but that doesn't solve it.

![image](https://github.com/elementary-data/dbt-data-reliability/assets/29655984/2c89b166-a2db-41a1-85a3-9e0cb3884464)

**Comment by dapollak** [comment]
@ayodelephillips
What is the cmd you are trying to run?

**Comment by KarthikHampannavar** [comment]
Even I am facing the same issue. Please let me know if you find a fix

**Comment by KarthikHampannavar** [comment]
@dapollak I am trying to run the command : edr report

**Comment by Maayan-s** [comment]
Hey @ayodelephillips @KarthikHampannavar , 
This is a local environment thing. 

What we usually see is one of 2 options:

1. Permissions for CLI to write to Python path - No permissions for the CLI to install a dbt package iy needs (no write access to the path of the package), so the package download isn't complete and the dbt command fails.
2. Python path issue, the package is installed but not in the path `edr` is looking at. Usually happens in Windows, you need to fix the local Python path config.

As this is a local env and not an Elementary issue, I'm closing it.
