### ISSUE TITLE
month option for time bucket throws error

### ISSUE THREAD

**Issue by gravitus153** [elementary-data/elementary#1279]
**Describe the bug**
Documentation for current release has option for time_bucket.period of hour, day, week, month
when we run with the option for month we get the following error
-----------------------
16:05:23 On test.my_new_project.elementary_all_columns_anomalies_stg_elig_std_bcbsmn_90__month__3.27c32769be: Close
16:05:23 Compilation Error in test elementary_all_columns_anomalies_stg_elig_std_bcbsmn_90__month__3 (models/stage/eligibility/bcbsmn/_stg_eligibility_bcbsmn.yml)
  time_bucket.period value should be one of ['hour', 'day', 'week'], got: month

---------------------------------

**To Reproduce**
in DBT CLoud 1.6.7
redshift database

in yaml file using following config

  - name: <table_name>
    description: ""
    config:
      elementary:
        timestamp_column: <table_insert_timestamp>
    tests:
      - elementary.volume_anomalies:
          days_back: 90
          time_bucket:
            period: month
            count: 3
      - elementary.all_columns_anomalies:
          days_back: 90
          time_bucket:
            period: month
            count: 3

1. goto dbt cloud command line
2. run dbt build -s <table_name>
3. goto log interface wait for error
4. open error log, scropp to bottom
5. See error

**Expected behavior**
If it is document to work with month time_bucket we should not be getting this error

**Screenshots**

**Environment (please complete the following information):**

- edr Version: Cannot run pip command in dbt cloud interface. is there a alternate way to get the edr version within dbt cloud
- dbt package Version: 0.12.1

**Additional context**

**Comment by dapollak** [comment]
Hey @gravitus153,
The 'month' option is not supported currently just for redshift by design (technical limitation).
You can change this issue to be a feature request though and we'll triage it

**Comment by gravitus153** [comment]
I can change this to feature request.
In the meantime will using time_bucket: week
                                                                Period: 4
Have roughly the same behaviour?
We load data once a month from multiple clients and are not concerned with seasonality at this time
