### ISSUE TITLE
Add test duration to the report

### ISSUE THREAD

**Issue by alexnikitchuk** [elementary-data/elementary#1284]
**Is your feature request related to a problem? Please describe.**
Sometimes the test may be slow or degrade over time and it is hard to find this info.

**Describe the solution you'd like**
Would be great to have the test duration visible in the report in the same way as the model.

**Describe alternatives you've considered**
Use query history to find long-running tests

**Additional context**
N/A

**Would you be willing to contribute this feature?**
Not sure

**Comment by haritamar** [comment]
Hi @alexnikitchuk !
Thanks for opening this issue and sorry for the delayed response.
Median and last test duration columns are now available under the "Test Runs" screen so I think it covers this use case!
