### ISSUE TITLE
Add Argument for aws session token in edr send-report

### ISSUE THREAD

**Issue by mkeightleyentrata** [elementary-data/elementary#1307]
**Is your feature request related to a problem? Please describe.**
We often use temporary aws credentials which include the session token on top of the aws access key id and secret access key. I am unable to pass the token in as an argument. 

**Describe the solution you'd like**
Ideally there can be an optional argument to pass in the token if using temporary credentials. 

**Describe alternatives you've considered**
My other alternative was using the ~/.aws/credentials file and point to a profile which held the temporary creds. My goal was to trigger edr send-report through Airflow and just being able to pass in the temporary credentials was a lot easier.

**Comment by jwhitneyinsurify** [comment]
Any updates here? I face the same issue as @mkeightleyentrata. I am also trying to trigger `edr send-report` via Airflow and can only pass temporary credentials, but would also need to pass a session token as well. I currently do not see any way to do so, and thus cannot upload the report to S3.

AWS Docs: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

**Comment by elongl** [comment]
Hi @mkeightleyentrata, @jwhitneyinsurify, I've created the [following PR](https://github.com/elementary-data/elementary/pull/1369) that adds `--aws-session-token`. It'll be reviewed by the team and added in the next version.
