### ISSUE TITLE
on_run_end hook to clean up test tables

### ISSUE THREAD

**Issue by i-dalbo** [elementary-data/elementary#1313]
**Is your feature request related to a problem? Please describe.**
Every time an anomaly test runs, a table like `TEST_0366DCDAFC_ELEMENTARY_FRESHNESS_ANOMALIES` is created, but persists to the DB where Elementary runs, even if those entries are written to other tables afterwards.

**Describe the solution you'd like**
It would be great to have an `on_run_end hook` that cleans up stale resources and/or allow to define a set of resources to clean up.

**Describe alternatives you've considered**
Writing a custom script or custom `on_run_end hook`.

**Comment by elongl** [comment]
Hi @i-dalbo, we actually do have [that](https://github.com/elementary-data/dbt-data-reliability/blob/797a5b402890a558755f0eccd767bc43f0ef52dd/macros/edr/tests/test_utils/clean_elementary_test_tables.sql#L1). It's being called from [`handle_tests_results`](https://github.com/elementary-data/dbt-data-reliability/blob/797a5b402890a558755f0eccd767bc43f0ef52dd/macros/edr/tests/on_run_end/handle_tests_results.sql#L17) which is called in the [`on-run-end`](https://github.com/elementary-data/dbt-data-reliability/blob/7fc193ac633549046dc068039a1d00d183d18da5/macros/edr/system/hooks/on_run_end.sql#L21) hook. Care to upgrade to the latest version and see if this continues?

**Comment by i-dalbo** [comment]
> Hi @i-dalbo, we actually do have [that](https://github.com/elementary-data/dbt-data-reliability/blob/797a5b402890a558755f0eccd767bc43f0ef52dd/macros/edr/tests/test_utils/clean_elementary_test_tables.sql#L1). It's being called from [`handle_tests_results`](https://github.com/elementary-data/dbt-data-reliability/blob/797a5b402890a558755f0eccd767bc43f0ef52dd/macros/edr/tests/on_run_end/handle_tests_results.sql#L17) which is called in the [`on-run-end`](https://github.com/elementary-data/dbt-data-reliability/blob/7fc193ac633549046dc068039a1d00d183d18da5/macros/edr/system/hooks/on_run_end.sql#L21) hook. Care to upgrade to the latest version and see if this continues?

hey @elongl, thanks for your answer! We developed a script to clean up, but we will also try to upgrade and use the built-in solution :) have a great week!

**Comment by elongl** [comment]
Thanks a lot, you too.
