### ISSUE TITLE
snowflake__get_profile_creation_query does not work depending on environment

### ISSUE THREAD

**Issue by pei0804** [elementary-data/elementary#1328]
**Describe the bug**
Errors occur when referencing multiple databases or Snowflake databases.

**To Reproduce**

1. Create multiple databases and use them in dbt. 
2. Execute `dbt run-operation create_elementary_user`

**Expected behavior**
Generated SQL can be executed.

**Additional context**

SQL that is actually generated and causes problems

```sql

-- Information schema access
CREATE OR REPLACE PROCEDURE ELEMENTARY_GRANT_INFO_SCHEMA_ACCESS(database_name STRING, role_name STRING)
  RETURNS VARCHAR
  LANGUAGE SQL
  AS
  $$
    BEGIN
      GRANT USAGE,MONITOR ON DATABASE IDENTIFIER(:database_name) TO ROLE IDENTIFIER(:role_name);
      GRANT USAGE,MONITOR ON ALL SCHEMAS IN DATABASE PREP TO ROLE IDENTIFIER(:role_name);
      GRANT USAGE,MONITOR ON FUTURE SCHEMAS IN DATABASE PREP TO ROLE identifier(:role_name);

      GRANT REFERENCES ON ALL TABLES IN DATABASE IDENTIFIER(:database_name) TO ROLE IDENTIFIER(:role_name);
      GRANT REFERENCES ON ALL VIEWS IN DATABASE IDENTIFIER(:database_name) TO ROLE IDENTIFIER(:role_name);
      GRANT REFERENCES ON ALL EXTERNAL TABLES IN DATABASE IDENTIFIER(:database_name) TO ROLE IDENTIFIER(:role_name);

      GRANT REFERENCES ON FUTURE TABLES IN DATABASE IDENTIFIER(:database_name) TO ROLE IDENTIFIER(:role_name);
      GRANT REFERENCES ON FUTURE VIEWS IN DATABASE IDENTIFIER(:database_name) TO ROLE IDENTIFIER(:role_name);
      GRANT REFERENCES ON FUTURE EXTERNAL TABLES IN DATABASE IDENTIFIER(:database_name) TO ROLE IDENTIFIER(:role_name);
    END;
  $$
;
CALL ELEMENTARY_GRANT_INFO_SCHEMA_ACCESS('snowflake', $elementary_role);
CALL ELEMENTARY_GRANT_INFO_SCHEMA_ACCESS('RAW', $elementary_role);
CALL ELEMENTARY_GRANT_INFO_SCHEMA_ACCESS('ELEMENTARY', $elementary_role);
CALL ELEMENTARY_GRANT_INFO_SCHEMA_ACCESS('PROD', $elementary_role);
CALL ELEMENTARY_GRANT_INFO_SCHEMA_ACCESS('PREP', $elementary_role);
```

**Want**

- The snowflake database is a special database, so if you try to grant it, you will get an error, which you want to ignore.
- In an environment where multiple databases are being operated, grant to {{database}} will be insufficient, so we want to use the database of the argument.

**Comment by pei0804** [comment]
The PR I fixed is this.
- https://github.com/elementary-data/dbt-data-reliability/pull/632

**Comment by pei0804** [comment]
```
CALL ELEMENTARY_GRANT_INFO_SCHEMA_ACCESS('ELEMENTARY', $elementary_role);
```

There are some issues where this execution is futile, but I couldn't think of a good idea to work around them.
For example, suppose you use `elementary_database` and ignore it, because the problem arises when the database used by Elementary is PREP or something like that.

**Comment by haritamar** [comment]
Closing issue since it was fixed in a PR
