### ISSUE TITLE
Add "test alerting" on Slack

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#133]
Slack alerts are only sent if there are failed tests.
When users deploy Elementary, they want to have a way to validate the deployment worked. 
We should have a flag for validating the deployment.

**Comment by ronmorgen1** [comment]
Looks interesting. Can I take it?

**Comment by ronmorgen1** [comment]
Looks interesting I would be happy to take this. How would you classify a successful deployment of the package?

**Comment by Maayan-s** [comment]
@ronmorgen1 

Important background - the CLI has an internal dbt project. This project queries the Elementary tables from the dbt package deployment. 
So the flow is:
1. User installs the dbt package, that collects data to an elementary schema
2. The CLI has an internal dbt project, with a profile pointing at the elementary schema
3. The CLI dbt project runs and reads data that should be sent as alerts
4. The CLI sends alerts to Slack

So a successful deployment means that the elementary schema exists, the CLI can read from it (the profile is well configured), and the CLI can find a Slack config and send a message.

**Comment by ronmorgen1** [comment]
@Maayan-s 

I see. So after the CLI installation when the user runs the command `edt monitor`, a slack message is sent only when tests fail, and now we want to send one when deployment is successful (?)

**Comment by Maayan-s** [comment]
@ronmorgen1 

I think we should probably have a `--test` flag.
The use case here is that you install but don't have any failed tests at the moment, but you still want to make sure the deployment actually works.

**Comment by elongl** [comment]
Added as `edr monitor --test`.
