### ISSUE TITLE
Real test names in report

### ISSUE THREAD

**Issue by dmitrii-khr** [elementary-data/elementary#1337]
**Is your feature request related to a problem? Please describe.**
I defined several volume tests on a model with different filtering conditions. I specified the name parameter in a readable and meaningful way. But all tests are displayed in the report identically. The test name is not used for visualization.

**Describe the solution you'd like**
Use real test names to display in the "Test name" column instead of volume_anomalies.
Make it possible to override a description for the volume/column tests.

**Additional context**
![image](https://github.com/elementary-data/elementary/assets/20114683/c2a34a4f-69ff-40ec-8782-de90e4e59e40)

**Would you be willing to contribute this feature?**

**Comment by haritamar** [comment]
Hi @dmitrii-khr !
Thanks for opening this issue and sorry for the delayed response.

Closing this issue as a duplicate of this one:
#1224 

mainly to keep discussion in one place (and since there's an open PR about it)
