### ISSUE TITLE
[ELE-108] Add support for a sum test in numeric column anomalies

### ISSUE THREAD

**Issue by oravi** [elementary-data/elementary#136]
### Requirements (reported on Slack) - 
We have a table with daily amount of sales grouped by store.
We would like to group that table by day and monitor the sum of those sales.
Overall daily sales should be pretty steady. If there is anomaly it's probably issue with our ETL.

<sub>[ELE-108](https://linear.app/elementary/issue/ELE-108/add-support-for-a-sum-test-in-numeric-column-anomalies)</sub>

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1676585508288509

**Comment by elongl** [comment]
Added in https://github.com/elementary-data/dbt-data-reliability/pull/278.
