### ISSUE TITLE
Record test duration and display in the elementary docs

### ISSUE THREAD

**Issue by alsaenko** [elementary-data/elementary#1383]
Elementary records model run duration and displays the results in the elementary docs. 
See the following example:
<img width="967" alt="image" src="https://github.com/elementary-data/elementary/assets/81834608/05319245-02af-4d64-978c-250d58fd087a">

Is it also possible to record run duration (i.e. execution_time) for dbt tests and display the durations in the docs?

Use case:
We would like to be able to easily profile/inspect test execution times to identify bottlenecks and areas of improvement.
For example, if a particular test takes a long time to run, we might want to improve the model and potentially apply partitioning, clustering.

**Comment by haritamar** [comment]
Hi @alsaenko !
Thanks for opening this issue and sorry for the delayed response.
This capability is actually now available in the Test Runs screen!
