### ISSUE TITLE
Dimension test for pre-aggregated values

### ISSUE THREAD

**Issue by szotyola** [elementary-data/elementary#1386]
**Is your feature request related to a problem? Please describe.**
I have a model, named `daily_transactions`
the model has 3 columns:
- `platform` ( dimension for mobile and desktop breakdown )
- `country` (180+ different active countries )
- `counter` (a pre-aggregated value, broken down by the dimensions )

Currently, the only way I can test dimension anomalies for the `country` and `platform` columns if I manually set up new tests for each, which is not scalable. 

**Describe the solution you'd like**
I would like to be able to test anomaly  detections daily by platform on the pre-aggregated values.
eg.: Being able to define:
- which column I want to use as a dimension
- _which column is to be aggregared_ and _how to be aggregared_ ( summing daily values would work in this case ) 

**Describe alternatives you've considered**
adding a `dimension_breakdown` column to the already existing `Column anomalies` test

**Additional context**

**Would you be willing to contribute this feature?**
Let us know if you're willing to contribute so that we'll be able to provide guidance.

**Comment by haritamar** [comment]
Hi @szotyola !
Thanks for opening this issue and sorry for the delayed response.
We have actually just recently added `dimensions` to the column anomalies test! So this capability is now supported.
