### ISSUE TITLE
Table/view exists test

### ISSUE THREAD

**Issue by AdamAizen** [elementary-data/elementary#1388]
**Is your feature request related to a problem? Please describe.**
Not getting slack alerts for underlying DB issues (table doesn't exist).
This can be very painful if tests are not running on a view because one of the feeding tables has a problem and the view was actually not existing (a bigger problem I would like to know about).

**Describe the solution you'd like**
Add a "table/view exists" test.

**Describe alternatives you've considered**
I created a macro to solve this issue, so any time there is missing table i get notified on that issue.

**Would you be willing to contribute this feature?**
Sure, why not.. (-:

**Comment by haritamar** [comment]
Hi @AdamAizen ,

Thanks for opening this issue and sorry for the delayed response.
My tendency is that this capability is not directly related to Elementary functionality so I'm not sure it should be a part of the package. 
However - Elementary can alert on any dbt test. So you should be able to define the test within your own project and Elementary should be able to alert on it (not sure if that's what you did actually).

Closing this issue for now.
