### ISSUE TITLE
Key-value failure with Slack workflows

### ISSUE THREAD

**Issue by esenilsson** [elementary-data/elementary#1418]
**Describe the bug**
While using slack workflows, the request that is sent has "text" as key, and the key-pairs as value, which Slack does not handle very well, as it needs direct key/values in the request body (please correct me if I am wrong here).

It does run with workflow=true, but SlackMessageSchema does not seem to handle key-pairs, only nested by "text" key.

**To Reproduce**
1. Set up slack workflow with a webhook, and use variables as mentioned in documentation 

3. use config.yaml 
 `slack:
  notification_webhook: <your_slack_webhook_url>
  workflows: true`

4. Have an error (that is easy :) )

5. Slack workflow gets initiated, but has no access to "variables". 

I also "listened" to this webhook and saw the format 
`{
    "text": "{\"alert_class_id\": \"test.xxx.unique_exp_active_contract_date_day.858f0ff97d.date_day.generic\"
     \"column_name\": \"date_day\"
     \"database_name\": \"xx\"
     \"detected_at\": \"2024-02-16 08:58:40\"
     \"elementary_unique_id\": \"xxx\"
     \"id\": \"e2dad9db-c503-4a85-91e6-7cd64dafa17e.test.xxx.unique_exp_active_contract_date_day.858f0ff97d\"
     \"model_unique_id\": \"model.xxx.exp_active_contract\"
     \"other\": {}
     \"owners\": []
     \"schema_name\": \"exposure\"
     \"severity\": \"WARN\"
     \"status\": \"error\"
     \"subscribers\": []
     \"suppression_interval\": 24
     \"table_full_name\": \"xx.exposure.exp_active_contract\"
     \"table_name\": \"exp_active_contract\"
     \"tags\": [\"exposure\"]
     \"test_description\": \"This test validates that there are no duplicate values present in a field.\"
     \"test_display_name\": \"Unique Exp Active Contract Date Day\"
     \"test_name\": \"unique_exp_active_contract_date_day\"
     \"test_params\": {\"column_name\": \"date_day\"
     \"model\": \"{{ get_where_subquery(ref('exp_active_contract')) }}\"}
     \"test_results_description\": \"Database error in test unique_exp_active_contract_date_day (models/exposure/tableau/_exp_tableau_models.yml)\\n  000904 (42000): sql compilation error: error line 11 at position 4\\n  invalid identifier 'date_day'\\n  compiled code at target/run/xxx/models/exposure/tableau/_exp_tableau_models.yml/unique_exp_active_contract_date_day.sql\"
     \"test_results_query\": \"select\\n    date_day as unique_field
    \\n    count(*) as n_records\\n\\nfrom xx.exposure.exp_active_contract\\nwhere date_day is not null\\ngroup by date_day\\nhaving count(*) > 1\"
     \"test_rows_sample\": []
     \"test_short_name\": \"unique\"
     \"test_sub_type\": \"generic\"
     \"test_sub_type_display_name\": \"Generic\"
     \"test_type\": \"dbt_test\"
     \"test_unique_id\": \"test.xxx.unique_exp_active_contract_date_day.858f0ff97d\"}"
}
`

**Expected behavior**
Get access to key pairs directly

**Environment (please complete the following information):**
 0.13.2

**Additional context**
Functionality implemented here [https://github.com/elementary-data/elementary/issues/53](url)

**Comment by haritamar** [comment]
Hi @esenilsson !
Thanks for opening this issue and sorry for the delayed response, we are currently in the process of reviewing our open issues and improving our process there.
Since the issue has been open for over 3 months I'm going go ahead to close it - please feel free to re-open if still relevant.

Thanks!
Itamar
