### ISSUE TITLE
Incompatibility elementary-data with Airflow (MWAA)

### ISSUE THREAD

**Issue by mattxxi** [elementary-data/elementary#1421]
**Describe the bug**

We are currently using Airflow (MWAA) 2.7.2, we would like to use elementary with Airflow and run edr commands in operators.
But there is a constraint for the library pydantic which has to be 2.4.2 but elementary-data is using pydantic <2.0.0.

*Please find all airflow constraints here:*
https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.11.txt

**To Reproduce**

Create a file requirements.txt with:
--constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.11.txt"
elementary-data==0.14.0

Then run the command:
```shell
pip download -d tmp/plugins --requirement requirements.txt
```
You must obtain the following error:
![image](https://github.com/elementary-data/elementary/assets/36408416/b94771d7-d1be-480b-b13c-bb9fc3c201a1)

**Expected behavior**

We should be able to install all requirements without conflicts between airflow and elementary.

**Environment (please complete the following information):**

- edr Version: 0.14.0
- dbt package Version: 0.14.0
- airflow: 2.7.2

**Comment by joydeepml** [comment]
One way to get around conflicting requirements between Airflow and dbt/packages is to run dbt inside a virtualenv within the airflow workers. Can set up a virtualenv using a startup script and activate it before running the dbt commands.

**Comment by kokorin** [comment]
> One way to get around conflicting requirements between Airflow and dbt/packages is to run dbt inside a virtualenv within the airflow workers. Can set up a virtualenv using a startup script and activate it before running the dbt commands.

That's exactly what we do.

**Comment by haritamar** [comment]
Hi @mattxxi !
Thanks for opening this issue and apologies for only replying now.
The issue with the pydantic requirement has actually been solved since version 0.14.1 of the package!

(Running in a virtualenv though as suggested above is a good practice in general, if you are already doing so)
