### ISSUE TITLE
Dbt compile failed after installing elementary-data

### ISSUE THREAD

**Issue by HantonMing** [elementary-data/elementary#1427]
**Describe the bug**
For business purpose, we need to run dbt compile. But after we started to use elementary, 'dbt compile' is giving this error:
```
`Runtime Error
  Compilation Error in operation elementary-on-run-end-0 (.\dbt_project.yml)
    'None' has no attribute 'values'
```

    > in macro clean_elementary_temp_tables (macros\edr\system\system_utils\clean_elementary_temp_tables.sql)
    > called by macro on_run_end (macros\edr\system\hooks\on_run_end.sql)
    > called by operation elementary-on-run-end-0 (.\dbt_project.yml)`

I traced it and in macro clean_elementary_test_tables, I found out that a dictionary temp_test_table_relations_map is not getting updated anywhere. Then an error is cast.

**To Reproduce**

1. Install elementary by following all instructions
2. Activate dbt-env
3. run "dbt compile

**Expected behavior**
Dbt compile is expected to run without error

**Screenshots**
![image](https://github.com/elementary-data/elementary/assets/138087562/49a37a3b-c3d1-457c-bc6a-a25952c725ab)

**Environment (please complete the following information):**

- edr Version: [0.14.0]
- dbt core version: [1.7.8]
- dbt databricks version: [1.7.7]

**Additional context**
Could you also explain the purpose of clean_elementary_test_tables? Is it possible to set elementary/macros/edr/system/system_utils/get_config_vars.sql/" 'clean_elementary_temp_tables': true," to false by default?

**Comment by MWS-TAI** [comment]
I am getting the same thing, upgraded from 0.13.2 to 0.14.0 and this error is now coming up.

dbt-core: 1.7.8
dot-redshift: 1.7.3

**Comment by will-warner** [comment]
>I am getting the same thing, upgraded from 0.13.2 to 0.14.0 and this error is now coming up.

Have you run `dbt run --select elementary` in production since upgrading?

https://docs.elementary-data.com/release-notes/upgrading-elementary#upgrade-elementary-dbt-package

**Comment by MWS-TAI** [comment]
@will-warner I had not tried that and yes it did resolve my issue. Not sure if this issue is due to upgrading but likely would be the same issue, maybe could be closed. Thanks!

**Comment by haritamar** [comment]
Closing since I believe [this PR ](https://github.com/elementary-data/dbt-data-reliability/pull/665/commits) fixed this issue. Please re-open if relevant!
