### ISSUE TITLE
Macro databricks__get_columns_from_information_schema is not working as expected

### ISSUE THREAD

**Issue by HantonMing** [elementary-data/elementary#1428]
**Describe the bug**
Unity catalog is disabled for us and we have trouble with `dbt run -s elementary`. In the macro elementary/macros/edr/metadata_collection/get_columns_from_information_schema.sql, another macor is defined for databricks ,which is databricks__get_columns_from_information_schema. The if condition in this macro,
```
{% if target.catalog is none %}
        {# Information schema is only available when using Unity Catalog. #}
        {% do return(elementary.get_empty_columns_from_information_schema_table()) %}
    {% endif %}
```
is not working properly in that if condition` target.catalog is none` is never met. In other words,  `return(elementary.get_empty_columns_from_information_schema_table())` is never executed. I know this because I made changes to rest of the macro, and changes were reflected in compiled query.
**To Reproduce**

1. Install elementary-data following instructions
2. Run `dbt run -s elementary`
3. Error message "Unity Catalog is not abled on this cluster"

**Expected behavior**
Disabled Unity Catalog should be correctly detected. And workaround macro is run.

**Screenshots**
![image](https://github.com/elementary-data/elementary/assets/138087562/ee02a7e0-4927-4b47-b21b-fb61d278581a)

**Environment (please complete the following information):**

- edr Version: [0.14.0]
- dbt core version: [1.7.8]
- dbt databricks version: [1.7.7]

**Additional context**

**Comment by haritamar** [comment]
Hi @HantonMing ,
Thank you for opening this issue and sorry for such a long delay in our reply.

I'm not sure if this is still relevant to you, but actually would love to know - you mentioned the condition `target.catalog is none` is never met.
Do you manage to see what value does it contain? Does it contain a legitimate value even though you are not using Unity Catalog?

**Comment by hamzamazhar** [comment]
@haritamar Thanks a lot for getting back to me. To answer your question, in my case, the `target.catalog` is `hive_metastore`. As mentioned in my original ticket, I am not specifying the field `catalog` in the `profiles.yaml` or anywhere else in the project.

**Comment by haritamar** [comment]
@hamzamazhar - thanks, that's actually very helpful, so it's a pretty simple fix.
