### ISSUE TITLE
will elementary compatible with dbt-spark package

### ISSUE THREAD

**Issue by gargvipul1349** [elementary-data/elementary#1442]
**Describe the gap**
will elementary compatible with dbt-spark package

**Comment by gargvipul1349** [comment]
@Maayan-s can somebody please answer on same

**Comment by haritamar** [comment]
Hi @gargvipul1349 !
While Elementary does work for some users with `dbt-spark`, unfortunately at this point it's not an officially supported contribution and is not actively maintained by the Elementary team, and I cannot guarantee a timeline for it.

That being said, you can try to see if it works for you and also feel free to consult with members in the [community slack ](https://elementary-data.com/community)

Thanks,
Itamar

**Comment by sudohainguyen** [comment]
#1718  can be one of compatibility issues for dbt-spark
