### ISSUE TITLE
Replace the use of 'compiled_sql'

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#145]
dbt made this change, so we need to fix our dependency:
https://github.com/dbt-labs/dbt-core/issues/5558

**Comment by ChenyuLInx** [comment]
@Maayan-s  We haven't make that change yet, we are looking to depreciate `compiled_sql`, it will still be there for the time being. I updated my original issue to make it more clear.

The recommended way to access that is through `compiled_code` after 1.3 release. which is something that exists directly in jinja context and you don't need to get it from model.

**Comment by Maayan-s** [comment]
Oh cool @ChenyuLInx , thank you so much for the clarification! 
I'll close this issue then, and we will address this when 1.3 approaches. 

(I had no idea Github connects issues cross repos like this, super cool!)
