### ISSUE TITLE
Issue on docs - em dash

### ISSUE THREAD

**Issue by acarter24** [elementary-data/elementary#1461]
Path: /data-tests/anomaly-detection-tests/volume-anomalies

Looking at the code block at the bottom of the page, I tried to paste into tests.yml but got a cryptic error. In the end I traced it to a em dash (when a hyphen is required in yaml)
 
C&P from lower code block:
![image](https://github.com/elementary-data/elementary/assets/126154605/e44b1529-5e76-4678-872d-cabea0dcd394)
Correcting to hyphen
![image](https://github.com/elementary-data/elementary/assets/126154605/7904438b-eb6d-4af6-b859-71550970628f)

The code block in the top right is correct and can be copied directly to yaml, just the one at the bottom that has the issue

**Comment by haritamar** [comment]
Thanks @acarter24 !
Fixed [here](https://github.com/elementary-data/elementary/pull/1526)
