### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by ahamefulautom** [elementary-data/elementary#1482]
<img width="505" alt="enable" src="https://github.com/elementary-data/elementary/assets/116164527/777f6ecc-e674-4796-bb94-1b9bce6b1725">
Path: /oss/guides/alerts/elementary-alerts
I wanted to configure Teams Webhook alerting system on the dbt -core, but I instead get the following error - Could please, guide me on what I am doing wrong: Could you please enable it for my instance? Thanks for your support
edr monitor 
    ________                          __
   / ____/ /__  ____ ___  ___  ____  / /_____ ________  __
  / __/ / / _ \/ __ `__ \/ _ \/ __ \/ __/ __ `/ ___/ / / /
 / /___/ /  __/ / / / / /  __/ / / / /_/ /_/ / /  / /_/ /
/_____/_/\___/_/ /_/ /_/\___/_/ /_/\__/\__,_/_/   \__, /
                                                 /____/

You are using Elementary 0.8.0, however version 0.14.1 is available.
Consider upgrading by running: xxxx

Any feedback and suggestions are welcomed! join our community here - https://bit.ly/slack-elementary

2024-04-09 01:17:13 — INFO — Running with edr=0.8.0

**elementary.exceptions.exceptions.InvalidArgumentsError: Either a Slack token and a channel or a Slack webhook is required.**

**Comment by Maayan-s** [comment]
Closing as this was an outdated version issue.
