### ISSUE TITLE
Add project name and environment to slack notification

### ISSUE THREAD

**Issue by kostek-pl** [elementary-data/elementary#1496]
**Is your feature request related to a problem? Please describe.**
Currently slack notification title looks like this:
<img src="https://github.com/elementary-data/elementary/assets/67253952/27defdbf-1640-4461-b593-f7d31e10bc26" width="300">

If there are many dbt projects and environments we need to create lot of separate slack channels to distinguish from which dbt project and environment monitoring summary comes from. 

**Describe the solution you'd like**
To make it easier and more convenient we should add project name and environment to the header so it could look like:

- when --project-name is not provided
   <img src="https://github.com/elementary-data/elementary/assets/67253952/afdf8f59-5ca8-4e2e-ac07-3eb7e5c37f4a" width="200">
   
- when --project-name is provided()
   <img src="https://github.com/elementary-data/elementary/assets/67253952/c9144be4-747f-441d-b401-cb1a5bb49ff3" width="300">

**Would you be willing to contribute this feature?**
Yes, i will contribute and take care of this

**Comment by haritamar** [comment]
Hi @kostek-pl !
Following up on this issue - thanks a lot for opening a PR.
I've noticed that @ellakz left a couple of comments, if you can take a look would be great, then we can ensure this gets into the next version.

**Comment by haritamar** [comment]
This was actually merged, so closing!
