### ISSUE TITLE
elementary in combination with sql server throws error

### ISSUE THREAD

**Issue by bssulfikkar** [elementary-data/elementary#1547]
**Describe the bug**
The dbt run command works fine until I installed elementary package. There is some bug in the elementary package as after installing elementary package I get error as Invalid column name 'True' . I tried using different versions of elementary package together with sql server odbc driver 17 but still getting the same issue.

**To Reproduce**

1. Install dbt in windows using PowerShell with Python 3.8.0. Below python packages are installed.
dbt-adapters==1.2.1
dbt-common==1.1.0
dbt-core==1.7.15
dbt-extractor==0.5.1
dbt-semantic-interfaces==0.4.4
dbt-sqlserver==1.7.4

2. install sql server  in the local machine
3. install elementary by keeping in the packages.yml

packages:
  - package: elementary-data/elementary
    version: 0.15.1

  - package: dbt-labs/dbt_utils
    version: 1.2.0

  - package: calogica/dbt_expectations
    version: 0.10.3
  
  - package: calogica/dbt_date
    version: 0.10.1

4. execute dbt run 

5. See error
[dbt.txt](https://github.com/user-attachments/files/15594130/dbt.txt)

16:58:47  Unhandled error while executing target\run\elementary\models\edr\dbt_artifacts\dbt_invocations.sql
('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'True'. (207) (SQLMoreResults); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Type boolean is not a defined system type. (243)")

16:58:49  Unhandled error while executing target\run\elementary\models\edr\dbt_artifacts\dbt_run_results.sql
('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'True'. (207) (SQLMoreResults); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Type boolean is not a defined system type. (243)")

16:58:55  Unhandled error while executing target\run\elementary\models\edr\data_monitoring\schema_changes\schema_columns_snapshot.sql
('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'True'. (207) (SQLMoreResults); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Type boolean is not a defined system type. (243)")

16:58:56  Unhandled error while executing target\run\elementary\models\edr\data_monitoring\anomaly_detection\metrics_anomaly_score.sql
('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'stddev' is not a recognized built-in function name. (195) (SQLMoreResults); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '::'. (102)")

16:58:57  Unhandled error while executing target\run\elementary\models\edr\alerts\alerts_dbt_source_freshness.sql
('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'and'. (4145) (SQLMoreResults)")

16:58:57  Unhandled error while executing target\run\elementary\models\edr\alerts\alerts_anomaly_detection.sql
('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'and'. (4145) (SQLMoreResults)")

16:58:57  Unhandled error while executing target\run\elementary\models\edr\alerts\alerts_dbt_tests.sql
('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'and'. (4145) (SQLMoreResults)")

16:58:57  Unhandled error while executing target\run\elementary\models\edr\alerts\alerts_schema_changes.sql
('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'and'. (4145) (SQLMoreResults)")
**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Elementary CLI (edr) version: [e.g. 0.5.3], can be found by running `pip show elementary-data` : elementary-data           0.15.1
- Elementary dbt package version: [e.g. 0.4.1], can be found in `packages.yml` file : elementary-data           0.15.1
- dbt version you're using [e.g. 1.8.1] :  dbt-core==1.7.15
- Data warehouse [e.g. snowflake] : sql server
- Infrastructure details (e.g. operating system, prod / dev / staging, deployment infra, CI system, etc) : windows, dev

**Additional context**

**Would you be willing to contribute a fix for this issue?** Not sure if I have time to fix it :) 
Let us know if you're willing to contribute so that we'll be able to provide guidance.

**Comment by haritamar** [comment]
Hi @bssulfikkar !
Elementary does not currently support SQL server as an adapter. You can see the list of supported adapters [here](https://docs.elementary-data.com/oss/oss-introduction#supported-adapters).

We have an [open issue](https://github.com/elementary-data/elementary/issues/353) with the integration request, please feel free to upvote.
We're welcoming contributions community of this adapter.
