### ISSUE TITLE
Issue with freshness test display on Elementary dashboard

### ISSUE THREAD

**Issue by arjunanandkumar** [elementary-data/elementary#1557]
**Describe the bug**
We had a jump in versions from v0.14.1 to v0.15.1 due to an oversight in our deployment script. That's been sorted, and things work fine for the most part except how freshness tests are shown on the dashboard. It looks like elementary now sees the freshness test as both a generic, and freshness type test as opposed to just freshness before. 

Old version:
![image](https://github.com/elementary-data/elementary/assets/162141685/2aad4756-a1e4-4d58-85dd-5d5848549187)

New:
![image](https://github.com/elementary-data/elementary/assets/162141685/64038fb6-3552-4b26-8b44-e42a57937e63)

Notice the 1 of each kind of test detected on most of these models. We haven't changed anything in the model specifically, and the freshness test is the only kind of test defined on it:

```
models:
  - name: engage_campaign_members
    description: desc
    tests:
      - elementary.freshness_anomalies:
          timestamp_column: created
          config:
            severity: warn
```

**To Reproduce**

1. Go to the elementary dashboard.
2. Click on the tests under "Freshness"
3. Test type "generic" is displayed instead of freshness.
4. But, if you navigate to the model where the freshness test is added, it correctly shows that the test type is freshness rather than generic. 

**Expected behavior**
It is expected that only the freshness test shows up in this view. 

**Screenshots**
Previous:
![image](https://github.com/elementary-data/elementary/assets/162141685/62300fd3-acf4-44dd-9ff2-55cce5799527)
Current:
![image](https://github.com/elementary-data/elementary/assets/162141685/1a84a1ff-3429-4c9e-9b55-64b026f11241)

**Environment (please complete the following information):**

- Elementary CLI (edr) version: v0.15.1 
- Elementary dbt package version: 0.13.2
- dbt version you're using: 1.8.1
- Data warehouse Snowflake
- Infrastructure details: dev and prod

**Would you be willing to contribute a fix for this issue?**
I am happy to contribute if I can get some guidelines.

**Comment by ellakz** [comment]
Hi @arjunanandkumar ,
Thanks for submitting the issue.
Other than the different "test type" values, did you notice any change in behavior? Are the results the same?

**Comment by arjunanandkumar** [comment]
Hi @ellakz,
Besides that, there is no change in behavior. I can see that it has run and passed if I navigate directly to the model where the freshness test is defined (Indicated by the green "1").

**Comment by arjunanandkumar** [comment]
Hi @ellakz, I was wondering if you had any new insight on this.

**Comment by arjunanandkumar** [comment]
Hey again @ellakz, we've located the issue. We completely oversaw this warning:
`WARNING — You are using incompatible versions between edr (0.15.1) and Elementary's dbt package (0.13.2).
 `

And this is something we have forgotten to handle on our end after we upgraded to dbt 1.8. I will close down this issue now.

**Comment by ellakz** [comment]
Thanks for updating @arjunanandkumar !
