### ISSUE TITLE
Is this open source or what is the plan

### ISSUE THREAD

**Issue by dhruvk12** [elementary-data/elementary#1625]
**Describe the gap**
Missing documentation about the pricing or whether it is open source
**Additional context**

**Comment by ronisaban2024** [comment]
Hi @dhruvk12
Thanks for pointing this out. Can I suggest a quick call to clarify and answer your questions? 
Roni

**Comment by ronisaban2024** [comment]
@dhruvk12 

Sharing more information here. 

- **Elementary open-source** is free to use. You can find more information about it [here](https://docs.elementary-data.com/oss/oss-introduction). 

- **The Elementary Cloud Platform** is built on top of the Elementary OSS package. It provides out-of-the-box monitoring, tools to easily increase coverage, and integrations for end-to-end visibility across the data stack. The platform helps promote ownership and collaboration on incidents and enables the whole data organization to take an active role in the data quality process. 

You can read more about the platform [here](https://docs.elementary-data.com/cloud/introduction).

Pricing information is available [here](https://www.elementary-data.com/pricing).

Closing this issue for now. 
If there are any more questions feel free to reach out to us.
