### ISSUE TITLE
Parse failed rows as part of the package

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#163]
Failed dbt test results return an error message that includes the number of failed rows.
Today we load the message as is in the package, and parse the number in the CLI using Python.
If we move the parsing to the package, users could run their analysis on these data.

**Comment by aqwvinh** [comment]
Hello!
Would it be also possible to return the number of total failed rows. For now, the error messages includes the number of singular different failed rows but not the total occurrences of rows that are failed. The goal is to track over time the percentage of failures through our tests.
Thanks!

**Comment by Maayan-s** [comment]
@oravi 
I checked the result object as you said, and saw the 'failures' field:
`message='Got 3100 results, configured to fail if != 0', failures=3100`
`message='Got 1 result, configured to fail if != 0', failures=1`

Do you think it's better to use it?

**Comment by Maayan-s** [comment]
Hi @aqwvinh, we think that this might be a quicker win than the regex. 
What do you say?

**Comment by aqwvinh** [comment]
Hello! I will try to find some time to work on the PR this week but as a quick answer to your last message, it can be quicker indeed ! But what about if the test passes? Does it return `failures=0`?

**Comment by Maayan-s** [comment]
Good question, it returns the number of failures. 
If the test has no special config and passes it returns 0.
If the test is configured to fail on failures>100 and there are 5 failures, it will return 5 for a passed test.
If there is an error in running the test - it returns None. 

(I checked on dbt 1.0.0 and above)

**Comment by Maayan-s** [comment]
Released on 0.4.12 of the dbt pakage!
@aqwvinh
