### ISSUE TITLE
After update to dbt `1.8.3` the table `elementary.dbt_run_results` is partially empty

### ISSUE THREAD

**Issue by jan-benisek** [elementary-data/elementary#1650]
**Describe the bug**
After updating to dbt `1.8.1` (from `1.7.2`) and elementary `0.15.1`, the table `elementary.dbt_run_results` is partially empty - the columns `execute_started_at`, `execute_completed_at`, `compile_started_at` and `compile_completed_at` are _null_.

**To Reproduce**
 I just run this query to see the latest dates:
```sql
select
    max(generated_at) as generated_at,
    max(execute_started_at) as execute_started_at,
    max(execute_completed_at) as execute_completed_at,
    max(compile_started_at) as compile_started_at,
    max(compile_completed_at) as compile_completed_at
from elementary.dbt_run_results;
/*
+-------------------+---------------------------+---------------------------+---------------------------+---------------------------+
|generated_at       |execute_started_at         |execute_completed_at       |compile_started_at         |compile_completed_at       |
+-------------------+---------------------------+---------------------------+---------------------------+---------------------------+
|2024-07-29 06:12:50|2024-07-09T05:51:33.254265Z|2024-07-09T05:53:12.946757Z|2024-07-09T05:51:33.243691Z|2024-07-09T05:51:33.252922Z|
+-------------------+---------------------------+---------------------------+---------------------------+---------------------------+
*/
```

**Expected behavior**
I'd expect these fields to be filled in, we use them for internal tracking of execution times.

**Screenshots**
N/A

**Environment (please complete the following information):**

- Elementary CLI (edr) version: `0.15.1`
- Elementary dbt package version:  `0.15.1`
- dbt version you're using: `1.8.3`
- Data warehouse: `Redshift`
- Infrastructure details: Runs as a last step in Airflow on k8s in our dbt pipeline. Never had issues before.

**Additional context**
We also did enable the flag in our project:
```
flags:
  require_explicit_package_overrides_for_builtin_materializations: False
```

Interestingly, the Elementary website dashboard works and has all the execution data.

**Would you be willing to contribute a fix for this issue?**
Sure, if not too complicated.

**Comment by ofek1weiss** [comment]
Hey @jan-benisek, this has been resolved in our newest version (0.16.0) 👍
