### ISSUE TITLE
Need to bump version to use packaging = ">=23.2,<24.0"

### ISSUE THREAD

**Issue by luisgallego-aily** [elementary-data/elementary#1653]
**Is your feature request related to a problem? Please describe.**
I need to use this library with `packaging = ">=23.2,<24.0"`. This version is already allowed since [this commit ](https://github.com/elementary-data/elementary/commit/baf60ee48fffffa5291128b371342f330e85e013) but this change is not yet deployed.

**Describe the solution you'd like**
Just bump elementary-data version to 0.15.2 so this change is deployed.

**Would you be willing to contribute this feature?**
Yes

**Comment by CarlosRicGuerrero** [comment]
Same issue here.

**Comment by mertkucukkuru-aily** [comment]
We are having the same issue, can someone please have a look?

**Comment by juan-abia** [comment]
Could we have a release with this change? It's blocking some teams

**Comment by ofek1weiss** [comment]
deployed in version `0.16.0`
