### ISSUE TITLE
Pre-aggregate data before computing statistics for volume anomalies

### ISSUE THREAD

**Issue by data-blade** [elementary-data/elementary#1663]
**Is your feature request related to a problem? Please describe.**
this is a duplicate of [this issue](https://github.com/elementary-data/elementary/issues/1329), since the duplicated issue got closed prematurely and is now ignored. also see related [slack thread](https://elementary-community.slack.com/archives/C02CTC89LAX/p1702394505257319).

**Describe the solution you'd like**
see [here](https://github.com/elementary-data/elementary/issues/1329)

**Describe alternatives you've considered**
see [here](https://github.com/elementary-data/elementary/issues/1329)

**Additional context**
see [here](https://github.com/elementary-data/elementary/issues/1329)

**Would you be willing to contribute this feature?**
see [here](https://github.com/elementary-data/elementary/issues/1329)

**Comment by IDoneShaveIt** [comment]
Hey @data-blade, thanks for raising that up!
I re-opened the other [issue](https://github.com/elementary-data/elementary/issues/1329) and will continue to update there
