### ISSUE TITLE
Can not use elementary-data 0.16.1 due to not updated dependency in hub.getdbt.com

### ISSUE THREAD

**Issue by sesigl** [elementary-data/elementary#1670]
**Describe the bug**
The version 0.16.1 is not able to be used via https://hub.getdbt.com/api/v1/elementary-data/elementary.json, which forces elementary uses sitting on 0.16.0.

**To Reproduce**

Installing 0.16.1 does not work for DBT using the recommended way installing elementay for dbt, .e.g.

packages.yml
```
---
packages:
  - package: elementary-data/elementary
    version: 0.16.1
```

leads to 

```
dbt.exceptions.PackageVersionNotFoundError: Could not find a matching compatible version for package elementary-data/elementary
  Requested range: =0.16.1, =0.16.1
  Compatible versions: ['0.1.1', '0.2.1', '0.3.0', '0.3.2', '0.3.4', '0.3.6', '0.3.8', '0.3.10', '0.3.12', '0.3.14', '0.3.15', '0.3.16', '0.4.0', '0.4.1', '0.4.2', '0.4.5', '0.4.6', '0.4.7', '0.4.8', '0.4.9', '0.4.10', '0.4.11', '0.4.12', '0.5.0', '0.5.1', '0.5.2', '0.5.3', '0.5.4', '0.5.5', '0.6.0', '0.6.1', '0.6.2', '0.6.3', '0.6.4', '0.6.5', '0.6.6', '0.6.7', '0.6.8', '0.6.9', '0.6.10', '0.6.11', '0.6.12', '0.6.13', '0.7.0', '0.7.1', '0.7.2', '0.7.3', '0.7.4', '0.7.5', '0.7.6', '0.7.7', '0.7.8', '0.8.0', '0.8.1', '0.8.2', '0.8.3', '0.8.4', '0.9.0', '0.9.1', '0.9.2', '0.9.3', '0.9.4', '0.10.0', '0.10.1', '0.10.2', '0.10.3', '0.11.0', '0.11.1', '0.11.2', '0.12.0', '0.12.1', '0.12.2', '0.13.0', '0.13.1', '0.13.2', '0.14.0', '0.14.1', '0.15.0', '0.15.1', '0.15.2', '0.16.0']
```

**Expected behavior**
0.16.1 should be available via https://hub.getdbt.com/api/v1/elementary-data/elementary.json

**Would you be willing to contribute a fix for this issue?**
I guess it should be part of the release process. Maybe there is a bug?

**Comment by Maayan-s** [comment]
Hey @sesigl , 
Elementary includes 2 packages:
- dbt package - installed via dbt hub, latest version is 0.16.0 (https://github.com/elementary-data/dbt-data-reliability)
- Python package / CLI - installed via PIP, latest version is 0.16.1 (this repo)

As long as the minor versions are the same, the packages are compatible. 

We update on new releases on our [Slack community](https://join.slack.com/t/elementary-community/shared_invite/zt-2h9nef281-adqo646GQn~T9gzG2ixxng), and of course you can follow the repos.
