### ISSUE TITLE
X-Axis +1 UTC 

### ISSUE THREAD

**Issue by FredRodrigues** [elementary-data/elementary#1680]
Hello, 

On my X-Axis I am currently seeing 
Aug 19 01:00
Aug 20 01:00
Aug 21 01:00

instead of 
Aug 19 00:00
Aug 20 00:00
Aug 21 00:00

**Screenshots**
![image](https://github.com/user-attachments/assets/3b6f8a5e-ab14-404b-b5a5-ec89ca783d12)

- Elementary CLI (edr) version: 0.16.1
- Elementary dbt package version: 0.16.0
- dbt version 1.8.1
- Data warehouse bigquery

What could be causing this issue?

**Comment by elongl** [comment]
Hi @FredRodrigues, in order to look into it we need the report's data.
Care to share `edr_target/elementary_output.json` with me in private on [our Slack](https://elementary-community.slack.com/archives/D03NUL1LV9N)?
Alternatively, you can email it to me at `elon@elementary-data.com`.
Thanks.

**Comment by FredRodrigues** [comment]
Will do it right now, thanks for answering.

**Comment by FredRodrigues** [comment]
Problem related to local computer timezone.
