### ISSUE TITLE
Demo link leads to an error page

### ISSUE THREAD

**Issue by leopasta-enable** [elementary-data/elementary#1685]
**Describe the bug**

**To Reproduce**

1. Go to the github main page
2. Click on the demo link(https://bit.ly/3IAp9wf)
3. See error

**Expected behavior**

**Screenshots**
https://storage.googleapis.com/elementary_static/elementary_demo.html?utm_source=github&utm_medium=readme&utm_campaign=main-repo

<Error>
<Code>UserProjectAccountProblem</Code>
<Message>The project to be billed is associated with a closed billing account.</Message>
<Details>The billing account for the owning project is disabled in state closed</Details>
</Error>

**Environment (please complete the following information):**

- Elementary CLI (edr) version: [e.g. 0.5.3], can be found by running `pip show elementary-data`
- Elementary dbt package version: [e.g. 0.4.1], can be found in `packages.yml` file
- dbt version you're using [e.g. 1.8.1]
- Data warehouse [e.g. snowflake]
- Infrastructure details (e.g. operating system, prod / dev / staging, deployment infra, CI system, etc)

**Additional context**

**Would you be willing to contribute a fix for this issue?**
Let us know if you're willing to contribute so that we'll be able to provide guidance.

**Comment by ofek1weiss** [comment]
Hey @leopasta-enable , thanks for letting us know and sorry for the late response.
We resolved the issue 👍
