### ISSUE TITLE
on-run-end hook failing: 'Tried to commit transaction on connection "master", but it does not have one open!'

### ISSUE THREAD

**Issue by stevenconnorg** [elementary-data/elementary#1712]
**Describe the bug**
- on-run-end hook failing when trying to upload artifacts with error:
```
19:22:33  Running 1 on-run-end hook
dbt command failed19:24:41  
19:24:41
19:24:41  Finished running 1 incremental model, 1 project hook in 0 hours 4 minutes and 41.25 seconds (281.25s).
19:24:41  Encountered an error:
Internal Error
  Tried to commit transaction on connection "master", but it does not have one open!
```
- on-run-start hook runs successfully

**To Reproduce**
- seems to be failing for all dbt cloud jobs

**Expected behavior**
- not sure why it's failing

**Screenshots**
<img width="854" alt="Screenshot 2024-10-01 at 3 58 02 PM" src="https://github.com/user-attachments/assets/6d193364-2f40-4f77-bc65-636112730d16">

**Environment (please complete the following information):**

- Elementary CLI (edr) version: N/A
- Elementary dbt package version: 0.16.1
- dbt version you're using "Versionless" in dbt cloud, 1.8+
- Data warehouse: Redshift
- Infrastructure details (e.g. operating system, prod / dev / staging, deployment infra, CI system, etc): dbt cloud

**Additional context**
- just started randomly happening yesterday around 5-6 pm CST

**Would you be willing to contribute a fix for this issue?**
Let us know if you're willing to contribute so that we'll be able to provide guidance.
- sure!

**Comment by franloza-jt** [comment]
@stevenconnorg We had the same issue after upgrading to `dbt-redshift~=1.8.0` package, which was required to use Versionless in dbt Cloud. We solved it by turning this flag to `False` in `dbt_project.yml` file:

```
flags:
  restrict_direct_pg_catalog_access: False
``` 

https://docs.getdbt.com/reference/global-configs/redshift-changes#the-restrict_direct_pg_catalog_access-flag

I think the issue is that elementary does not work well when this flag is turned on.

**Comment by stevenconnorg** [comment]
Thanks so much @franloza-jt ! That worked for me. I will submit an issue [here](https://github.com/dbt-labs/dbt-redshift/discussions/921) instead.
