### ISSUE TITLE
Add 'where expression' support  to table and column anomalies tests

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#215]
On the new 'dimension anomalies' test we implemented support of getting 'where expression' param, which contains an SQL expression for filtering the tested data.
The same logic can be implemented for the other tests as well. 

Why not use dbt native 'where' as requested on [this issue](https://github.com/elementary-data/elementary/issues/75)? 
dbt returns an SQL expression when you use it, and we expect a relation ([issue in dbt](https://github.com/dbt-labs/dbt-core/issues/5435)).

**Comment by elongl** [comment]
Work in progress in [this PR](https://github.com/elementary-data/dbt-data-reliability/pull/158).
