### ISSUE TITLE
Unsupported authentication method in Snowflake

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#217]
The 'externalbrowser' authentication is not supported, as this is a CLI and this method requires a manual interference.

**Comment by ronmorgen1** [comment]
I would be happy to pick this up @Maayan-s

**Comment by Maayan-s** [comment]
Hi @ronmorgen1, Thank you!! 
Actually, @IDoneShaveIt started working on it this morning, I didn't update the issue yet.

@IDoneShaveIt - How far along are you? 
And @ronmorgen1 - Were you interested specifically in working on this or could I suggest another issue that would be a good place to start?

**Comment by ronmorgen1** [comment]
@Maayan-s I would appreciate any suggestions you may have

**Comment by Maayan-s** [comment]
Cool @ronmorgen1 !
I think this is a cool issue for the dbt package - https://github.com/elementary-data/elementary/issues/215
And this one for the CLI - https://github.com/elementary-data/elementary/issues/133

WDYT?
