### ISSUE TITLE
Bug in Snowflake Kafka connector queries parsing

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#26]
We’re using it against tables that are populated by the snowflake connector for kafka - and it is recognizing the RECORD_CONTENT field as a table.

(Reported in Slack #support on Oct 21)

**Comment by oolongtea** [comment]
@Maayan-s do you have a Slack link to the bug report, or any other details to try to reproduce?

**Comment by Maayan-s** [comment]
Hi @oolongtea ,
The report was that Elementary recognizes the RECORD_CONTENT field as a table.
Do you use Kafka connector on Snowflake? Are you experiencing the same issue?
