### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by ronmorgen1** [elementary-data/elementary#262]
There is a broken link to the installation guide in the [dbt package documentation](https://docs.elementary-data.com/guides/modules-overview/dbt-package) 

https://github.com/elementary-data/elementary/blob/6dc55c8ae63e7f22b8c503e8ec30d77d66c4f4b5/docs/guides/modules-overview/dbt-package.mdx#L20

**Comment by Maayan-s** [comment]
Thanks for reporting @ronmorgen1 ! 
Want to fix it? :) 
The correct url would be:
`../quickstart#how-to-install-elementary-dbt-package`

**Comment by ronmorgen1** [comment]
Would be happy to @Maayan-s 
Here it is - #263

**Comment by Maayan-s** [comment]
Deployment completed.
Thanks again @ronmorgen1 , see you in the meetup :)
