### ISSUE TITLE
Don't use a separate schema for elementary tests (`elementary__tests`)

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#285]
Request from users, the use case is if you don't use elementary tests or if you have permission issues and are limited in creating new schemas. 

We encountered an issue with dbt that prevents that, in a nutshell - they create a cached schema at the run start and use it later as default. Only if we create a new schema (that is not in cache) we can actually access tables we create during the run.

**Comment by elongl** [comment]
Started working on a PR [here](https://github.com/elementary-data/dbt-data-reliability/pull/90) but stopped working on it for the time being. If anyone would like to continue, this should be a good place to start.

**Comment by Maayan-s** [comment]
https://github.com/elementary-data/dbt-data-reliability/pull/90

**Comment by haritamar** [comment]
Merged a [PR with a fix](https://github.com/elementary-data/dbt-data-reliability/pull/141) to master, will be included in the next release :)
