### ISSUE TITLE
Add config option for s3 key

### ISSUE THREAD

**Issue by askvinni** [elementary-data/elementary#290]
First off, thanks a lot for the package, I'm playing around with it and excited to roll it out gradually.

This is a QoL feature request; it would be great to specify a key inside the S3 bucket for the shared website. I currently have an s3 website hosting the dbt documentation and would like to use the same for elementary, just specifying a subfolder.

The current workaround of setting up a post-run hook after running edr monitor report works perfectly of course, but that would be a slight improvement.

**Comment by Maayan-s** [comment]
Hi @askvinni, 
Thank you for the compliments! 

I'm not sure I understand the request all the way.
We have a `edr monitor send-report` command that uploads directly to S3, here is [the documentation](743af988da482e5738da9d72f85a7b9a4801addfd437c0058ae0b1677cba07f3).

Does this answer the use case or are there improvements you think we should add?
