### ISSUE TITLE
Support custom test name in Slack alerts

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#298]
Since dbt 1.1 custom names for tests are supported.
Config looks like this:
```
        tests:
          - name: unexpected_order_status    # custom name for test
            test_name: accepted_values      # name of the generic test to apply
```

However, we don't use the right field in the alerts to show this name. 

The change:
1. Check if we collect this field in dbt_package elementary_test_restults table. If not - add it.
2. Make alerts use that field as test name if it exists.

**Comment by Maayan-s** [comment]
This is the similar issue for the report: https://github.com/elementary-data/elementary/issues/299

**Comment by Maayan-s** [comment]
https://github.com/elementary-data/dbt-data-reliability/pull/99

**Comment by oravi** [comment]
Duplicate as #299 https://github.com/elementary-data/elementary/issues/299
