### ISSUE TITLE
Disable skipped model alerts

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#300]
For model results Slack alerts, users asked for the option to be notified only on failures and not on skipped models.

**Comment by elongl** [comment]
Sharing my idea of how to implement this feature.

1. Introduce a new `disable_skipped_model_alerts` under [`get_config_var`](https://github.com/elementary-data/dbt-data-reliability/blob/master/macros/edr/system/system_utils/get_config_var.sql) with a default `false` value.
2. If this configuration is enabled, under the [`alerts_dbt_models`](https://github.com/elementary-data/dbt-data-reliability/blob/master/models/edr/alerts/alerts_dbt_models.sql) model, add to the `where` clause - `and status != 'skipped'`.

**Comment by fredmny** [comment]
PR is up. Thank you, @elongl . You're instructions made it quite easy.
I tried to follow the formatting as I saw it on other models

**Comment by Maayan-s** [comment]
https://github.com/elementary-data/dbt-data-reliability/pull/101

**Comment by Maayan-s** [comment]
Released on 0.4.12 of the dbt package. 
Thank you so much @fredmny!!

**Comment by ValdarT** [comment]
I think there should similarly be `disable_skipped_tests_alerts` or perhaps these should be just filtered out as I can't think of a reason why someone would like to get alert from a test that never ran.

**Comment by Maayan-s** [comment]
Hi @ValdarT, 
That makes perfect sense!
On which cases dbt tests are skipped?
On `dbt build` when the model is skipped?

**Comment by ValdarT** [comment]
> On which cases dbt tests are skipped?
On dbt build when the model is skipped?

Exactly

**Comment by Maayan-s** [comment]
@ValdarT 
I can't tag you as you are not a contributor to the repo, opened this issue:
https://github.com/elementary-data/elementary/issues/354

Would you be open to adding it yourself?

**Comment by ValdarT** [comment]
Sure, opened [a PR](https://github.com/elementary-data/dbt-data-reliability/pull/116)
