### ISSUE TITLE
Add disablement flag for uploading test results

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#302]
The test results upload happens on an on-run-end.
Users should have a way to disable it in a specific run using a var.

**Comment by elongl** [comment]
Introduced a `var` called `disable_tests_results`.

**Comment by DakotaMichael** [comment]
Is there anything like this that would be model-specific? For instance if we wanted not to upload particularly wide models from uploading the test_results_query, would this be possible for said models?
