### ISSUE TITLE
Allow Boto3 to determine credentials, or have the local IAM role as an option for S3 report uploads.

### ISSUE THREAD

**Issue by luthes** [elementary-data/elementary#323]
I want to run Elementary as part of an Airflow job, running in an AWS EKS Pod that has a role that allows access to the bucket. The current way that [AWS credentials are handled](https://github.com/elementary-data/elementary/blob/1a85cb8da955d99c78a50e044d92f229c11bc2b9/elementary/clients/s3/client.py#L17) in the S3 Client requires that the user provide either an AWS credential profile, which also ultimately has to have credentials, or AWS Secret/Access Keys which ends up stopping boto3 from finding the IAM role and using that for authentication. I suppose it could be a flag in the CLI, and the [validation in config.py](https://github.com/elementary-data/elementary/blob/0cbf611225e623fd4e2f6b895ca68031e1e56b98/elementary/config/config.py#L58) could check for the flag as well to skip the other credentials. If there's a preference either way, I could submit a PR for this, it's a small change I think.

**Comment by oravi** [comment]
Hi @luthes!

Thanks so much for opening this issue and for willing to contribute, your suggestion sounds great! 
Indeed adding a new flag called `--aws-use-iam-role` could be used to determine if the boto3 session should rely on the IAM role.  As you mentioned it should be added [here](https://github.com/elementary-data/elementary/blob/0cbf611225e623fd4e2f6b895ca68031e1e56b98/elementary/config/config.py#L66). 

Would love to review your PR once it's ready! thanks again @luthes!
