### ISSUE TITLE
Configuration does not properly handle precedence (CLI Arguments -> Config File -> Default)

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#336]
The current lookup for configuration in the [`Config`](https://github.com/elementary-data/elementary/blob/master/elementary/config/config.py) object is based on the value's truthiness.
For instance: `self.conf_val = cli_val or file_conf.get('my_val', True)`.

If the `cli_val` was specified `False` and not `None`, the default `True` of the configuration value would be used regardless because the expression evaluates to `False or True` which is `True`.

A simple solution will be to introduce a `_lookup()` method that checks according to the precedence that values are not `None`.

```py
def _lookup(self, cli_val, file_conf_val, default=None):
    if cli_val is not None:
        return cli_val
    if file_conf_val is not None:
        return file_conf_val
    return default
```

Here's the pseudo code.

An alternative solution is to have the `_lookup` receive only the key in the configuration file so that it's called like this:
`self.slack_token = self._lookup(slack_token, 'slack.token')`.

**Comment by kopackiw** [comment]
I've submitted a PR but have problem with passing CI check. I wrote additional info in the PR and I'd be grateful for help!
