### ISSUE TITLE
Disable skipped tests alerts

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#354]
On dbt build when the model is skipped the tests are skipped as well. 

ValdarT reported ans suggested:
I think there should similarly be `disable_skipped_test_alerts` or perhaps these should be just filtered out as I can't think of a reason why someone would like to get alert from a test that never ran.

I think we should do the same as we did with models - a flag that is False by default. 

Implementation:
1. Introduce a new `disable_skipped_test_alerts` under [get_config_var](https://github.com/elementary-data/dbt-data-reliability/blob/master/macros/edr/system/system_utils/get_config_var.sql) with a default false value.
2. Under the [alerts_dbt_tests](https://github.com/elementary-data/dbt-data-reliability/blob/master/models/edr/data_monitoring/data_monitoring/alerts_dbt_tests.sql) model, add to the where clause - and status != 'skipped' if the var is false.

**Comment by ValdarT** [comment]
https://github.com/elementary-data/dbt-data-reliability/pull/116

**Comment by Maayan-s** [comment]
Thank you @ValdarT for making your first contribution! :tada:
Merged and will be included in the upcoming release.
