### ISSUE TITLE
Replace current_timestamp macro when a core functionality is implemented in dbt core

### ISSUE THREAD

**Issue by rloredo** [elementary-data/elementary#358]
See https://github.com/elementary-data/dbt-data-reliability/blob/dd7d40b36937e012b62df07182160b1a5a02dd88/macros/utils/cross_db_utils/current_timestamp.sql#L3 

It will prevent this warning

```
the `current_timestamp` macro is deprecated and will be removed in a future version of the package, 
once equivalent functionality is implemented in dbt Core. 
The elementary.metrics_anomaly_score model triggered this warning.
```

**Comment by Maayan-s** [comment]
Thanks @rloredo !
I think it is now in dbt core (wasn't yet when @IDoneShaveIt made that change):
https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/adapters/timestamps.sql

I do see that there is some issue there with the old implementation (we are using) on Snowflake.
@oravi you worked on timestamps recently, can you say if we can make the change?

**Comment by oravi** [comment]
Hi @rloredo, just updating that we opened a [PR](https://github.com/elementary-data/dbt-data-reliability/pull/125/files) that fixes it here and it should be released today

**Comment by oravi** [comment]
This is fixed and deployed already, closing this issue!
