### ISSUE TITLE
Microsoft SQL Server (mssql) integration

### ISSUE THREAD

**Issue by match-gabeflores** [elementary-data/elementary#360]
Similar to [Postgres Integration](https://github.com/elementary-data/elementary/issues/61) issue, would like to request SQL Server integration. 

There's prob not a lot of demand for MSSQL but our team would definitely take advantage of this tool.

**Comment by Maayan-s** [comment]
Thanks for opening the issue @match-gabeflores ! 
There is one about it actually, but the name wasn't that clear. 
I'll rename it and close this one, could you please add your support there?
https://github.com/elementary-data/elementary/issues/353

**Comment by Maayan-s** [comment]
@match-gabeflores 
Also, I didn't ask and I can't tag you on the other issue.
Are you open to try implementing it yourself? 

Just the dbt package side. I could provide guidance, we have an incremental approach to integrations with new adapters (we break it down to smaller tasks). I can't say how hard it is as I don't know how different the adapter is, but if it follows the dbt guidelines it shouldn't be complicated as our code is cross platform.

**Comment by match-gabeflores** [comment]
@Maayan-s  - I unfortunately don't have the time commitment but I subscribed to the original issue for updates. Thanks!
