### ISSUE TITLE
Capture dbt variables

### ISSUE THREAD

**Issue by eliasgeee** [elementary-data/elementary#365]
It would be nice to store the dbt variables passed to a run as a json in the database. Something like the functionality dbt artifacts provides https://github.com/brooklyn-data/dbt_artifacts . This would allow us to pass correlation ids etc to dbt and have it in a table for that dbt run and link it to processes / services that triggered the run.

![image](https://user-images.githubusercontent.com/44612469/197530850-dc407d60-4178-410e-9410-91623c28833b.png)

**Comment by elongl** [comment]
Began working on it in [this pull request](https://github.com/elementary-data/dbt-data-reliability/pull/123).

**Comment by elongl** [comment]
[Merged](https://github.com/elementary-data/dbt-data-reliability/pull/123)!
