### ISSUE TITLE
CLI fails if there are changes to table between test and CLI execution

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#370]
We made a decision to get the tests sample data when the CLI runs, and not on the on-run-end hook.
The reason was we didn't want to slow your dbt jobs. 
The downside is this scenario - the test query is collected on the on-run-end but executed only later. If meanwhile there is a change, the query fails and the run fails.

Suggestions:
1. Not fail the whole report if a sample fails.
2. Try moving sampling to the on-run-end, and check the performance impact.

**Comment by elongl** [comment]
Alternatively, we could search for ways to do that outside of `on-run-end`, for instance by using `store_failures` or something in that area.

**Comment by elongl** [comment]
While this could still theoretically happen, we've dramatically decreased the odds of it happening.
It could only occur whenever a sample of 5 test result rows are too big to be fit into the `result_rows` column in `elementary_test_results`.

Due to that change, I'm closing this issue.
