### ISSUE TITLE
Snowflake Query_id

### ISSUE THREAD

**Issue by kkprab** [elementary-data/elementary#383]
**Is your feature request related to a problem? Please describe.**
When we get a dbt run failure, I often look through the debug logs to find the exact query which was run..
Also in case of data issues if we want to use snowflake time travel query id make it easier to go back

**Describe the solution you'd like**
dbt run_results.json has snowflake query_id.. add this as part of elementary table dbt_run_results

**Describe alternatives you've considered**
Right now, I look through the snowflake query history to find the sfqid, which works but is a bit tedious.

**Additional context**

**Comment by Maayan-s** [comment]
Thank you for surfacing @kkprab, sounds like a great addition!
I wonder if this value is returned in other platforms as well. 

Are you open to contributing this feature? 
I would provide guidance of course, should be simple

**Comment by IDoneShaveIt** [comment]
Hey @kkprab  thanks for this idea!
I tested it, and it seems to be a specific information that snowflake adapter is returning on dbt run.
As @Maayan-s said, if you are open to contributing this feature we would love to provide guidance!

In addition, can you please share with us the need this feature helps you with?
And can you please tell us if (or why) the compiled code that we save on the `dbt_run_results` table and shows in our alerts & report isn't enough?
We would love to learn from your use case an improve our product!

**Comment by kkprab** [comment]
Hi
  Yes I am open to contributing for this feature..
I understand that query_id would be only relavant to snowflake... let me try to explain use case
In dbt tables are create or replace so if I want to time travel on a table
Only way is to create table using before (date time or query id)

Reason why we need time travel could be

1)      Issue with logic (ie changes passed on to PROD with out proper validation) I know in our company it happens some time

2)      Data comparison

3)      Say dbt run took long time for certain model with query id it will be faster to get to and view the query profile to find out root casue

If we have query_id there is no better way to time travel as well analysing issue in query profile



Thanks
Prabahar Kamatchirajan

**Comment by IDoneShaveIt** [comment]
Thanks @kkprab for willing to contribute this feature and sharing all this information with us!

Here's a guidance for this feature:
1. We need to add the `query_id` field to the dbt run results table. To do so we need to add the column [here](https://github.com/elementary-data/dbt-data-reliability/blob/master/macros/edr/dbt_artifacts/upload_run_results.sql#L13)
2. We need to extract the data from the run_result object and add it to the uploaded run result object [here](https://github.com/elementary-data/dbt-data-reliability/blob/master/macros/edr/dbt_artifacts/upload_run_results.sql#L37)  - In case that there is no `query_id`, it should be `None`
3. Add the `query_id` to the models that are based on `dbt_run_results` table: [model_run_results](https://github.com/elementary-data/dbt-data-reliability/blob/master/models/edr/run_results/model_run_results.sql), [snapshot_run_results](https://github.com/elementary-data/dbt-data-reliability/blob/master/models/edr/run_results/snapshot_run_results.sql)

**Comment by kkprab** [comment]
I have made the changes Can I ask you how do I test it?




Thanks
Prabahar Kamatchirajan

**Comment by IDoneShaveIt** [comment]
@kkprab of course!
You added a change to the `dbt_run_results` artifact table, meaning all you should do to test your change is to run `dbt run` with your version of elementary package!

I think that the easiest way for you to do so is to install you local elementary package in your dbt project ([guide](https://docs.getdbt.com/docs/build/packages#how-do-i-add-a-package-to-my-project)).
You can do so by replacing elementary package at your dbt project `packages.yml` file with the following rows:

```yaml
packages:
  - local: <dbt-data-reliability cloned repo path>
```

Now when you'll run `dbt deps`, it will install your changes at your dbt project.

Another option is to run our integration tests.
To do so, follow this [guide](https://docs.elementary-data.com/general/contributions#how-to-test-my-code).

Thanks again for the contribution, and feel free to reach out for any other question that you have!

**Comment by haritamar** [comment]
Hi @kkprab , chiming in here.
Can you please send the full file with this change (or a github link)? 
It can help with understanding the issue.

Please correct me if I'm wrong, but I believe you are trying to add an "{% if" statement within the context of "{% set flatten_run_result_dict" in `upload_run_results.sql`.
That won't work as you can't nest Jinja statements.

I believe this should work though:
```
'query_id': run_result_dict.get('adapter_response', {}).get('query_id') if run_result_dict.get('adapter_response', {}).get('query_id') else None
```

Or actually, a shorter version without duplicating the logic that gets the query id:
```
'query_id': run_result_dict.get('adapter_response', {}).get('query_id') or None
```

**Comment by haritamar** [comment]
Hi @kkprab  - You should open a pull request.
See [this github guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) on how to do so, and please let me know if additional help is needed!

**Comment by kkprab** [comment]
Created pull request

***@***.***




Thanks
Prabahar Kamatchirajan
