### ISSUE TITLE
Demo link leads to a takedown

### ISSUE THREAD

**Issue by quimnuss** [elementary-data/elementary#391]
The demo link in the README

https://bit.ly/3IXKShW

leads to a frightening takedown page

`UserProjectAccountProblemThe project to be billed is associated with a delinquent billing account.The billing account for the owning project is disabled in state delinquent`

**Comment by oravi** [comment]
Thanks so much for surfacing @quimnuss !! it was just a temporary wrong setting on our side of our billing information in Google cloud. We've just fixed it and everything should work now! closing this issue for now so feel free to re-open it if anything similar is happening again
