### ISSUE TITLE
'NoneType' object is not iterable when specifying `--vars` with non-json string 

### ISSUE THREAD

**Issue by DOUS3L** [elementary-data/elementary#397]
Executing dbt command with `--var` using non-json string will give this error 
```bash
> dbt build --vars '{key: value, date: 20180101}'

11:27:33  Database error while running on-run-end
11:27:34  Encountered an error:
Compilation Error in operation elementary-on-run-end-0 (./dbt_project.yml)
  'NoneType' object is not iterable
  
  > in macro upload_dbt_invocation (macros/edr/dbt_artifacts/upload_dbt_invocation.sql)
  > called by macro on_run_end (macros/edr/system/hooks/on_run_end.sql)
  > called by macro get_all_vars (macros/edr/dbt_artifacts/upload_dbt_invocation.sql)
  > called by operation elementary-on-run-end-0 (./dbt_project.yml)
```

**Environment:**
 - dbt package Version: 0.5.5

I believe this is caused by this `fromjson()` line returning a `None` when it's not a json string (which dbt also [supports](https://docs.getdbt.com/docs/build/project-variables#defining-variables-on-the-command-line))
https://github.com/elementary-data/dbt-data-reliability/blob/a776e917b16b9db8f6d8acd64c3a1c7f5eaeaa80/macros/edr/dbt_artifacts/upload_dbt_invocation.sql#L58
everything works fine when the provided value is a json

**Comment by Maayan-s** [comment]
Thanks for reporting @DOUS3L ! 
I guess that we should change the macro to handle additional types of input (all the supported methods basically). Would also be good to add a unit test for that macro that passes the different formats. 

Are you open to making this fix yourself as a contribution?

**Comment by elongl** [comment]
Hi @DOUS3L, just wanted to let you know that it'll be fixed on the next release.
Here's [the fix](https://github.com/elementary-data/dbt-data-reliability/pull/149).
Thank you.
