### ISSUE TITLE
Is there a plan to open source the ui?

### ISSUE THREAD

**Issue by Dbraum** [elementary-data/elementary#400]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you be willing to contribute this feature?**
Let us know if you're willing to contribute so that we'll be able to provide guidance.
Is there a plan to open source the ui?
now i see the htlm is is compiling fine, I would like to code

**Comment by Maayan-s** [comment]
Hi @Dbraum, 
We started with releasing the parts that are implemented in Python and SQL, to keep the source code focused on areas that most of our users are familiar with. 
That being said, we would love to hear more about your use case and if there's anything that is missing in the UI today :)
