### ISSUE TITLE
CLI dbt Model Case Sensitivity Issue

### ISSUE THREAD

**Issue by Daniel-Gaimster** [elementary-data/elementary#407]
**Is your feature request related to a problem? Please describe.*

We use Snowflake as our database and have the quoting of identifiers as true in our dbt_projects.yml file. This results in the tables/views created when running `dbt run --select elementary` having lower-case names. 

The issue arises when running `edr monitor report`, as the upper-case names of the tables is searched for and Snowflake returns back an error that looks like this (from the edr.log file):

```
When searching for a relation, dbt found an approximate match. Instead of guessing \\n  which relation to use, dbt will move on. Please delete \\"DATABASENAME\\".\\"ELEMENTARY\\".\\"dbt_invocations\\", or rename it to be less ambiguous.\\n  Searched for: DATABASENAME.ELEMENTARY.DBT_INVOCATIONS\\n  Found: \\"DATABASENAME\\".\\"ELEMENTARY\\".\\"dbt_invocations\\"\\
```

**Describe the solution you'd like**
A flag for the CLI to control the case of the tables/views was suggested by @Maayan-s.

**Describe alternatives you've considered**
Perhaps a var for the dbt package to override the quoting rules set in dbt_project.yml could be another possibility.

**Additional context**
Initial discussion of this issue and the potential solution took place in [this slack thread](https://elementary-community.slack.com/archives/C02CTC89LAX/p1668773776439349).

**Would you be willing to contribute this feature?**
Happy to test on my machine/project, though I'm afraid I don't know how to implement the suggested CLI change myself.

**Comment by Maayan-s** [comment]
Hi @Daniel-Gaimster,
@haritamar added this in the version we released yesterday. 
Here is the documentation:

**dbt Quoting:** Optionally control the [quoting setting](https://docs.getdbt.com/reference/project-configs/quoting) of the internal dbt package of the elementary CLI. You should use this setting if you are overriding dbt’s default quoting in your main dbt package.

```bash
-q, --dbt-quoting [all|none|combination of any of: database,schema,identifier]

# Examples:
# * --dbt-quoting all
# * --dbt-quoting none
# * --dbt-quoting identifier
# * --dbt-quoting schema,identifier
```
