### ISSUE TITLE
Export lineage relationships in a file

### ISSUE THREAD

**Issue by gabola24** [elementary-data/elementary#44]
Some data discovery platforms like Amundsen have options to visualize data lineage relationships at a glance on the moment that you are exploring data. But you need to bring your own lineage metadata, Im really interested in an option to export the lineage relations in a file (csv or json) so I can pass that to the amundsen extractor. In the case of the basic lineage extractor of amundsen uses a single .CSV file with the structure: *source_table , target_table*
If this file is a JSON , additional info can put it in there. So we could filter per type: CREATE_VIEW or CREATE_TABLE operations

**Comment by oravi** [comment]
Hi @gabola24, 

Thanks for opening this issue! starting from version 0.1.3 we now support exporting the lineage and its attributes (query type, update time, duration, etc) to two files - 'lineage_graph.gpickle' and 'graph_attributes.gpickle'. We used this serialization [format](https://networkx.org/documentation/stable/reference/readwrite/gpickle.html) as this is very common when working with graphs. Please let me know if this helps with your use case. 

thanks!
