### ISSUE TITLE
Add ability to suppress multiple Slack alerts for same failing tests

### ISSUE THREAD

**Issue by merunstrong** [elementary-data/elementary#441]
**Is your feature request related to a problem? Please describe.**
Currently, Elementary Slack alerting is great but getting notified every 30 minutes (how frequently we run `dbt`)  about the same test failing is clogging our alerting channel resulting in people muting it, defeating the purpose of alerting to test failures. 

**Describe the solution you'd like**
We would like to be able to set a parameter to allow us to receive all alerts or only the first failure alert depending on the importance of the model. 

**Describe alternatives you've considered**
Without this feature available right now, we are looking at a custom Slack notification based on querying the Elementary schema to check to see if a test failure already exists for that unique test. But this feature seems like it would be useful for everyone and Elementary already has a great Slack alerting setup. 

**Additional context**

**Would you be willing to contribute this feature?**
Yes.

**Comment by elongl** [comment]
Linking a [different problem](https://elementary-community.slack.com/archives/C02CTC89LAX/p1670504842285359?thread_ts=1670502047.073109&cid=C02CTC89LAX) that could relate in terms of the solution to this issue.

> we often have transient DB errors like connection dropped or something so we have a secondary run to catch these before sending alerts for failures only if they fail a second time using something like: dbt build --select result:error+ result:fail+ --defer --state ./target - In the case that a model has failed once, the post hook runs to catch the alert and then the model passes on the 2nd go - Elementary currently sends a failure alert for the first failure (or 2 alerts if it fails both times) - how would you recommend getting around this? I was thinking of maybe disabling the auto upload of alerts for the 1st run (though a var to the command) cos in theory everything that fails is run again anyway and should be caught the 2nd time.

It seems like both could be solved by allowing users to specify an optional `where` to the alerts views to filter the alerts.

**Comment by Hadarsagiv** [comment]
Released in version 0.6.5
