### ISSUE TITLE
Wrongfully showing "Something went wrong" when the problem is that no tests were ran

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#443]
**Describe the bug**
The _Test Results_ and _Test Runs_ tabs on the report show _"Something went wrong."_ whenever a user installed Elementary for the first time without running any tests. In the past, the CLI would continue executing whenever an error occurred and therefore we displayed this error, however, current the CLI itself would raise an error if there's a problem and this page is no longer accurate.

**Expected behavior**
The page should say _"No tests were ran."_ instead.

**Comment by Hadarsagiv** [comment]
Internal issue, will be handled in linear. Closing this public issue
