### ISSUE TITLE
Deduce user id from email for slack alert mentions

### ISSUE THREAD

**Issue by haritamar** [elementary-data/elementary#446]
**Is your feature request related to a problem? Please describe.**
Mentions based on username in slack do not always work, especially in large / enterprise slack workspaces where multiple email domains may be used with the same usernames.
Also the mechanism of deducing the username from email is not accurate.

**Describe the solution you'd like**
Slack recommendation is to mention based on user ID using this format `<@USER_ID>`, this is a more reliable mechanism. However, since adding user IDs manually is not easy and also to maintain backward compatibility for existing users, we suggest the following approach:

1. Check if the supplied owner is a full email (with a regex). If it is, then use slack's API to deduce the user ID from it:
```
client.users_lookupByEmail(email=email)["user"]["id"]
```
2. Otherwise use the current logic.

**Suggested implementation guidelines**

1. The relevant areas in the code are:

- The `_send_alerts_to_slack` method in the `DataMonitoring` class (located in `elementary/monitor/data_monitoring.py`), which also contains a slack client instance.
- The `Alert` base class and its implementations (located in the folder `elementary/monitor/alerts`)
- The `SlackClient` class (located in `elementary/clients/slack/client.py`)

2. The `to_slack` method is used in the various alert implementations to format the slack message, and the owners are currently written via a `_add_fields_section_to_slack_msg` call that looks like this:
```
self._add_fields_section_to_slack_msg(
    slack_message, [f"*Owners*\n{self.owners}", f"*Tags*\n{self.tags}"]
)
```

3. We suggest to add a new method called `_add_owners_section_to_slack_msg` which will also contain the new logic and use that in the various alert implementations. It will need to receive the slack client as input, so it should also be propaged to the `to_slack` call.

4. We also suggest to add the actual logic of looking up the user id from the email in the `SlackClient` class, and also to cache the result per email (to avoid looking up the same email multiple times for different alerts).

5. It is important to maintain backward compatibility, so we should fall back to using the owners as-is in case the logic of looking up the email does not work.

**Comment by elongl** [comment]
Added [here](https://github.com/elementary-data/elementary/pull/448) and [here](https://github.com/elementary-data/elementary/pull/453).
