### ISSUE TITLE
Support `dbt-labs/dbt_utils` `1.0.0`

### ISSUE THREAD

**Issue by pei0804** [elementary-data/elementary#456]
Thank you for providing great OSS.
I am using elementary in my production. I am using `dbt-labs/dbt_utils` and when I try to upgrade the `dbt-labs/dbt_utils` version, need to upgrade the version of the elementary package that depends on `dbt-labs/dbt_utils`.

**Would you be willing to contribute this feature?**
I'll ready to contribute.

**Comment by pei0804** [comment]
fixed
- https://github.com/elementary-data/dbt-data-reliability/pull/174

**Comment by pei0804** [comment]
- https://github.com/elementary-data/dbt-data-reliability/actions/runs/3639622731/jobs/6143240274

oh failed...
I feel no good.
It's ok?

**Comment by IDoneShaveIt** [comment]
Will be released on version 0.6.5
