### ISSUE TITLE
primary_test_model_candidates with same name part

### ISSUE THREAD

**Issue by mgeerken** [elementary-data/elementary#458]
**Describe the bug**
The parent_model_unique_id value of the dbt_tests artifact is identified by checking if the dependend model is part of test_metadata.kwargs.model.

If more than one model is part of it, then the parent_model_unique_id is not filled. That is already the case, if one dependend model name is part of the actual parent model.

By standard we define relationships tests between "model123" and "model123_related". Like every PK of "model123_related" must be in "model123". Since model123 is part of the model123_related name, this concept is not working.

If I'm missing anything please let me know. Could also be a feature rather than a bug.
Unfortunately, I can't provide a reliable and tested solution.

**To Reproduce**
Steps to reproduce the behavior (this logic can be found in the upload_dbt_test() macro in line 94):
`{% set mod= 'model.project_name.model123' %}
{{true if mod.split('.')[-1] in '{{ get_where_subquery(ref("model123_related")) }}'}}`

**Expected behavior**
The parent_model_unique_id value of the dbt_tests artifact is filled even there is another dependend model, that is part of the parent model name.

**Environment (please complete the following information):**
 - dbt core: 1.2
 - elementary package: 0.6.4

**Comment by elongl** [comment]
Hi @mgeerken, thanks a lot for opening this issue.

Adding the context here on the particular use-case that you shared with me:
> I was building a singular dbt test, that checks whether the related model has the same data sources as the main model.
This rule applies for all the same models, that also have the relationship test implemented.
In this example i need to ensure that all the sources from the LINK are also sources used for the ESAT_LINK.
Of course i could build this directly on the graph, buts a lot easier und the structured information coming from the package. Especially later for other developers to maintain.

It definitely makes sense to me that we'd be able to detect the model that the generic test is defined on.
I think I have a good solution, I'll open a PR soon and update in this thread.

**Comment by elongl** [comment]
I created [this PR](https://github.com/elementary-data/dbt-data-reliability/pull/175) that finds the parent model in a simpler manner. It takes the `model` argument from the test's arguments and simply renders the Jinja expression that is used there. This returns the relation, and afterwards we lookup the node by the relation and extracts the unique ID. I'll wait for one of the team members to review it.
