### ISSUE TITLE
[ELE-65] Support regular expression in the search bar and a "select all" option in the lineage view

### ISSUE THREAD

**Issue by yu-iskw** [elementary-data/elementary#468]
**Is your feature request related to a problem? Please describe.**
I would like to quickly search multiple dbt model(s)/source(s) with the search bar in the lineage view. For instance, I would like to search all sources in a database and a schema with a pattern of regular expression. And then, I would like to filter by selecting the matched resources with a "select all" option at once.

**Describe the solution you'd like**
1. It would be great to support regular expression pattern matching in the search bar of the lineage view.
2. It would be awesome to select all matched resources at once. 

![image](https://user-images.githubusercontent.com/1523515/207262364-7f9ed282-4384-421c-9114-9a941f4339a2.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Would you be willing to contribute this feature?**
I would love to contribute.

<sub>[ELE-65](https://linear.app/elementary/issue/ELE-65/support-regular-expression-in-the-search-bar-and-a-select-all-option)</sub>

**Comment by Hadarsagiv** [comment]
Thanks @yu-iskw ! we've added this task to our backlog. We'll keep you updated once we have news about this issue.

**Comment by Hadarsagiv** [comment]
Released in 0.7.10 🎉

**Comment by yu-iskw** [comment]
Thank you so much! I look forward to the next release.
