### ISSUE TITLE
[ELE-70] Add thread_id to dbt run results tables

### ISSUE THREAD

**Issue by eliasgeee** [elementary-data/elementary#493]
In the run_results.json file there is a thread id. I Think this would be handy to use to find out the complete execution flow of the DAG: see which models run in parallel and where there might be a hick-up in performance if models have to wait for 1 model to complete

<sub>[ELE-70](https://linear.app/elementary/issue/ELE-70/add-thread-id-to-dbt-run-results-tables)</sub>

**Comment by Maayan-s** [comment]
Hi @eliasgeee, 
Sounds like a cool addition! 
You could identify the specific DAGs that take longer. 

Would you be open to contributing it? 
We can provide guidance of course

**Comment by eliasgeee** [comment]
I would be open to contribute. I have some time in this EOY sprint.

**Comment by elongl** [comment]
Hi @eliasgeee ! Thanks a lot for your willingness to contribute.
Here's what you'll need to do:
1. Add the `thread_id` to the `dbt_run_results` table [here](https://github.com/elementary-data/dbt-data-reliability/blob/087b72d164e3263de649199a0ac9cf9904a1afb3/macros/edr/dbt_artifacts/upload_run_results.sql#L30) - `('thread_id', 'string')`.
2. Extract the `thread_id` from the run result node and add it to the artifact [here](https://github.com/elementary-data/dbt-data-reliability/blob/50722171f7ffbe379036dd37404c65fb2bfebbe4/macros/edr/dbt_artifacts/upload_run_results.sql#L56) - `'thread_id': run_result_dict.get('thread_id')`.

**Comment by eliasgeee** [comment]
What tests do you expect to be written/adjusted (unit tests/ integration tests/...)? And can you provide possible examples

**Comment by Maayan-s** [comment]
You would need to check that the change is working for you as expected on your data platform, and then run e2e tests to validate that the change does not break other functionality. 
Here is a guide for the e2e: 
https://docs.elementary-data.com/general/contributions#how-to-test-my-code

After you submit a PR we run it on our CI on the rest of the platforms.

**Comment by elongl** [comment]
Hi @eliasgeee ,any updates?
Would love to help if needed.
