### ISSUE TITLE
[ELE-29] Being able to define "endpoint_url" when sending report to S3

### ISSUE THREAD

**Issue by esenilsson** [elementary-data/elementary#507]
We have selfhosted S3 instances (not AWS). My need is  to send the generated report to the selfhosted one, instead of AWS.

As I understand it, boto3 is used, and it is possible to use other endpoints than aws with the parameter "endpoint_url". Ideal solution (for me) would be to able to choose custom endpoint with edr cli

<sub>[ELE-29](https://linear.app/elementary/issue/ELE-29/being-able-to-define-endpoint-url-when-sending-report-to-s3)</sub>

**Comment by Maayan-s** [comment]
Hi @esenilsson, thanks for opening the issue! 
This sounds like a simple addition, and it makes sense to support it.

Would you be open to contributing it? 
We would provide guidance of course :)

**Comment by elongl** [comment]
Thought I'd share the changes needed:

1. Add the required flag [here](https://github.com/elementary-data/elementary/blob/de9be164a62ab06e606831b2b254352a3725948a/elementary/monitor/cli.py#L407-L406).
2. Pass it to `Config` [here](https://github.com/elementary-data/elementary/blob/51ed8209a4b69454c5f1db49b3ce28a3d2977f8e/elementary/config/config.py#L51).
3. Change `S3Client.send_report()` to support an endpoint URL [here](https://github.com/elementary-data/elementary/blob/7e0475922e86b401bcf5bdfc9230f8acf5dcbabb/elementary/clients/s3/client.py#L32).

Hope that helps, let us know if you have any questions.

**Comment by esenilsson** [comment]
Hi both, 

Sure, I have given it a shot. Let me know if I have done something stupid

**Comment by elongl** [comment]
Works great, thanks for the contribution.
Will be released in the upcoming version.

**Comment by elongl** [comment]
@esenilsson 
Could you please also document the new `--s3-endpoint-url` flag [here](https://github.com/elementary-data/elementary/edit/master/docs/understand-elementary/cli-commands.mdx)?
