### ISSUE TITLE
[ELE-77] Transient Error - TestRunSchema.test_runs: None is not an allowed value

### ISSUE THREAD

**Issue by falonso-alo** [elementary-data/elementary#521]
**Describe the bug**

 We are running DBT/Elementary from a MWAA (Managed Workflows for Apache Airflow) using a KubernetesPodOperator. We experienced a transient error where the `TestRunSchema` threw a validation error. Below is the command log and the stack trace.

```
2023-01-04 17:01:27 — INFO — Running dbt --log-format json run-operation get_tests_invocations --args {"invocations_per_test": 720, "days_back": 7} --project-dir /usr/local/lib/python3.10/site-packages/elementary/monitor/dbt_project
2023-01-04 17:01:33 — ERROR — Could not get test runs and totals - Error: 1 validation error for TestRunSchema
test_runs
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/elementary/monitor/data_monitoring/data_monitoring_report.py", line 272, in _get_test_runs_and_totals
    tests_runs = self.tests_api.get_test_runs(
  File "/usr/local/lib/python3.10/site-packages/elementary/monitor/api/tests/tests.py", line 249, in get_test_runs
    test_run = TestRunSchema(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TestRunSchema
test_runs
  none is not an allowed value (type=type_error.none.not_allowed)
```

**To Reproduce**
The exception was a transient error and it's not clear how to trigger it reliably without knowing the internals of Elementary.

**Expected behavior**
No exception would be raised if there are no tests to run.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - apache airflow=2.0.2
 - dbt-redshift=1.3.0
 - elementary-data[redshift]=0.6

**Additional context**
Happy to provide any additional context that you may require.

<sub>[ELE-77](https://linear.app/elementary/issue/ELE-77/transient-error-testrunschematest-runs-none-is-not-an-allowed-value)</sub>

**Comment by oravi** [comment]
Hi @falonso-alo ! sorry to hear about this, can you please share your `edr.log` and `/usr/local/lib/python3.10/site-packages/elementary/monitor/dbt_project/logs/dbt.log`?

**Comment by oravi** [comment]
If you prefer sending it over Slack in private feel free to join our [Slack ](https://join.slack.com/t/elementary-community/shared_invite/zt-uehfrq2f-zXeVTtXrjYRbdE_V6xq4Rg)

**Comment by falonso-alo** [comment]
Hello @oravi,

Unfortunately, I don't think we ship those logs when the process fails and since it is being run in a container the environment is lost. If this makes debugging the issue impossible feel free to close out this ticket. 

Thank you for your time,
Felix

**Comment by falonso-alo** [comment]
@IDoneShaveIt,

Sorry to leave you in suspense! I haven't seen it the last couple of days.

**Comment by Maayan-s** [comment]
Hi @falonso-alo, as you saw we are pretty sure we understand why it happens. 
If there are `dbt test` or `dbt run` commands executed in parallel to the `edr run` it causes a race condition that sometimes makes the run fail.
We have a solution and would fix on the next version, the linked issue is the one to follow. 
Will update here as well as soon as it's out.

**Comment by Maayan-s** [comment]
Hi @falonso-alo, 
We released last night a version with a fix. 
Upgrading the Python package to 0.6.6 and the dbt package to 0.6.11 should solve this for you :)

Closing the issue.

**Comment by falonso-alo** [comment]
Thank you, @Maayan-s!
