### ISSUE TITLE
[ELE-124] Anomaly tests use invalid metrics when a `timestamp_column` is added or removed.

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#523]
**Describe the bug**
A test that was ran with a `timestamp_column` will have time-bucketed metrics.
If the `timestamp_column` was removed from the test, it'll still use the previous metrics.

![image](https://user-images.githubusercontent.com/30181361/210816353-db4b721a-f0a1-4afb-b0e8-2f72c0005ace.png)

<sub>[ELE-124](https://linear.app/elementary/issue/ELE-124/anomaly-tests-use-invalid-metrics-when-a-timestamp-column-is-added-or)</sub>

**Comment by oravi** [comment]
Closing this issue as this is duplicated with #595
