### ISSUE TITLE
[ELE-126] Display execution time in Test Runs

### ISSUE THREAD

**Issue by gary-beautypie** [elementary-data/elementary#524]
**Is your feature request related to a problem? Please describe.**
Tracking down optimisation candidates within a dbt project, quickly identifying slow tests or those that are trending upwards in execution time

**Describe the solution you'd like**
Display execution time stats in the Test Runs tab in the UI

**Describe alternatives you've considered**
Querying artifacts from the tables directly, i.e. dbt_run_results, etc, is fine for those of us who do it frequently, but it's easier to democratise the responsibility with the Elementary UI

**Additional context**
Alerting on long running tests/ models will be useful one day to notify those accountable for the models

**Would you be willing to contribute this feature?**
I'm not really a UI dev, so wouldn't be much help here, happen to contribute to other tasks though!

<sub>[ELE-126](https://linear.app/elementary/issue/ELE-126/display-execution-time-in-test-runs)</sub>

**Comment by Hadarsagiv** [comment]
Thanks for opening this issue @gary-beautypie !
We added this task to our backlog and it will go through our product prioritization process. Usually one of our considerations when prioritizing is the demand from the community.
We'll keep you updated once we have news about this issue.

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1674582169679429 (Jon Simpson)

**Comment by Smellow19** [comment]
I would also like to see this feature, As a data engineer a big part of my job is optimizing runs and having model and test timing metrics easily available is a huge plus for me as I can review the reports at least once a week to see if there are any models / tests running longer than they should or being able to identify models/tests that may need optimization

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C03LPJ5EYU9/p1682079171532709

**Comment by haritamar** [comment]
Closing, since we now support last and median execution time in the Test Execution History (previously Test Runs) screen!
