### ISSUE TITLE
[ELE-135] Support disabling test sampling in Elementary's dbt package

### ISSUE THREAD

**Issue by oravi** [elementary-data/elementary#529]
Today it's possible to disable test sampling by defining the following --disable-samples in Elementary's CLI.

Following this thread -

https://elementary-community.slack.com/archives/C02CTC89LAX/p1672963194187039

We also need to support disabling the test sampling mechanism in the package itself so PII won't be stored in the elementary tables.

<sub>[ELE-135](https://linear.app/elementary/issue/ELE-135/support-disabling-test-sampling-in-elementarys-dbt-package)</sub>

**Comment by oravi** [comment]
This will be fixed with https://github.com/elementary-data/dbt-data-reliability/pull/226

**Comment by oravi** [comment]
@elongl will review

**Comment by RoiTabach** [comment]
Re-raised in support case - https://elementary-community.slack.com/archives/C02CTC89LAX/p1681891108231959 
running with limit=0 will disable the upload but will still run (potentially) a lot of queries, affecting performance
