### ISSUE TITLE
Add support for Slack workflows format in alerts 

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#53]
The current format does not support workflows, as it only supports key-value pairs.
```
{
  "description": <ALERT_DESCRIPTION>,
  "table": <table_name>,
  "detected_at" <detected_at>
}
```

**Possible solution:**
Config property where you can set the type of slack integration you are using (either 'workflow' or 'webhook'). If you set the config to 'workflow' the response body would be formatted in the proper way.

**Comment by oravi** [comment]
Hi,

### Suggested design

**Configuration**
  
In the config.yml the slack webhook config should look as follows - 
```
slack:
    notification_webhook: <webhook_url>
    workflows: true / false
```
This requires small changes to the config.py file. The default value for slack worfklows should be set to false.

**Alerts**

- Alert base class should expose a new function in its interface called 'to_slack_workflows_message' and each alert type should implement this new function.
- The template that should be implemented in 'to_slack_workflows_message' should follow the restrictions slack workflows messages must adhere to. 
- The 'send_to_slack' function in Alert base class should receive a new parameter that indicates if the regular slack template or the workflow template should be used and call 'to_slack_message' or 'to_slack_workflows_message' accordingly. 
- Then in data_monitoring.py, pass the new slack workflows flag using the config object to the 'send_to_slack' function of each alert.

Please let me know your thoughts or questions about it :)

**Comment by Maayan-s** [comment]
Added by @aaron-westlake in version 0.2.1 :tada:
