### ISSUE TITLE
[ELE-130] Synonymous data types (varchar, text) aren't treated equally in schema changes baseline test

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#543]
<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-130](https://linear.app/elementary/issue/ELE-130/synonymous-data-types-varchar-text-arent-treated-equally-in-schema)</sub>

**Comment by elongl** [comment]
@itamar will review

**Comment by oravi** [comment]
@haritamar are you reviewing this?
