### ISSUE TITLE
[ELE-157] Empty screen when there are no test results shouldn't be the error screen

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#545]
Example: [https://elementary-community.slack.com/archives/C02CTC89LAX/p1673294641017789](https://elementary-community.slack.com/archives/C02CTC89LAX/p1673294641017789)

When there is no error, just no results, we still return this:

![](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/f288870b-e16f-4bc8-847e-2edc38dedd3d/e937a4b0-4499-4343-bba3-84c1cd9b720b)

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-157](https://linear.app/elementary/issue/ELE-157/empty-screen-when-there-are-no-test-results-shouldnt-be-the-error)</sub>

**Comment by elongl** [comment]
*Note*: if the property is `null` rather than an empty list, the error screen should still show.

However, an empty list should no longer be treated as an error.

@nimrod

**Comment by Maayan-s** [comment]
Does the change handle empty model runs screen as well?
One user had that recently.
@Hadarsagiv @elongl

**Comment by Hadarsagiv** [comment]
@Maayan-s - Right I also thought of that, will create a separate task for this use case.
