### ISSUE TITLE
[ELE-164] Document how to pass the job env_vars for dbt_invocations

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#551]
[https://elementary-community.slack.com/archives/C02CTC89LAX/p1673374633074929](https://elementary-community.slack.com/archives/C02CTC89LAX/p1673374633074929)

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-164](https://linear.app/elementary/issue/ELE-164/document-how-to-pass-the-job-env-vars-for-dbt-invocations)</sub>

**Comment by Maayan-s** [comment]
Also https://elementary-community.slack.com/archives/C02CTC89LAX/p1673383038648659

**Comment by elongl** [comment]
Documented [here](https://github.com/elementary-data/elementary/commit/95915681121537844bbb4fe84afd95d8e546f97b).

**Comment by Maayan-s** [comment]
Can you make the documentation of dbt artifacts tables a snippet and add it to the `dbt artifacts` page as well? 
I think these are the 2 places I would go look for.

**Comment by elongl** [comment]
I think a better solution is to not have so many data duplications in the docs. It's really confusing and we over-use snippets in my opinion.

Also, I think we should be more opinionated regarding this feature. Users just "happen" to realize that you can use `dbt_invocations` and `job_run_results` to capture your jobs and link dbt runs to PRs and so on. Maybe we should add this to one of the guides.
