### ISSUE TITLE
[ELE-166] Add `user` to `dbt_invocations`

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#554]
**Is your feature request related to a problem? Please describe.**
Users would like to be able to attribute a dbt invocation to a user in the orgranization.

**Describe the solution you'd like**
Add a `user` column to `dbt_invocations`.

**Additional context**

Here's the [Slack thread](https://elementary-community.slack.com/archives/C02CTC89LAX/p1673374633074929).

<sub>[ELE-166](https://linear.app/elementary/issue/ELE-166/add-user-to-dbt-invocations)</sub>

**Comment by elongl** [comment]
Here are the steps for implementation:

1. Add the column to the table [here](https://github.com/elementary-data/dbt-data-reliability/blob/0efa57bdd89aa149c9576a552283551f39b49000/macros/edr/dbt_artifacts/upload_dbt_invocation.sql#L112).
2. Read the user value from `DBT_USER` environment variable [here](https://github.com/elementary-data/dbt-data-reliability/blob/0efa57bdd89aa149c9576a552283551f39b49000/macros/edr/dbt_artifacts/upload_dbt_invocation.sql#L31).

**Comment by ayalalo** [comment]
Hi @elongl, as mentioned [here](https://elementary-community.slack.com/archives/C02CTC89LAX/p1673436289553589?thread_ts=1673374633.074929&cid=C02CTC89LAX). 
perhaps storing all DBT environment variables (excluding sensitive information, can help on other use cases.

**Comment by elongl** [comment]
Hi @ayalalo ,
could you perhaps clarify the use-case?
Also, what do you mean by dbt environment variables?

There's also a technical challenge that we cannot read all the environment variables and then filter them.
We have to know the name of the variable in advance.

**Comment by ayalalo** [comment]
Hi @elongl,
in short:
when querying elementary tables we would like to slice by DBT_USER attribute who actually made the invocation.

details:
Our DBT setup make use of DBT_USER as an environment variable. 
we're using dbt-core and when developing locally, 
each user stores its own username as an environment variable.
in DBT:
this environment variable is then used in the proflie.yml creating the connection to the relevant dwh.
this environment variable is also used for changing the schema name (via custom macro for generate_schema_name).

hence each local dbt invocation (dbt run, dbt test ect...) is actually writing the result set into a custom_schema.custom_table table.

but, looking at elementary invocations table we dont see any of the custom configuration being applied and cannot differ between invocations.

we can add the --vars option to each and every 'dbt command' we run but thats not convenient and prone to human typos...

regarding your second question:
what about some ENUM list of DBT_* values?
something like:
DBT_ALLOWED_ENVIRONMENT_VARIABLES = [DBT_USER, DBT_ENV, ....]
and this list could then be checked and returned a dictionary of these keys and their actual values

**Comment by oravi** [comment]
Hi @ayalalo ! chiming in here to help with this issue - is there anything else besides DBT_USER that is critical for you to see in the elementary invocations table and doesn't exist already?

**Comment by ayalalo** [comment]
Hi @oravi,
the most important thing for us is recording the actual user who performed the action (e.g who ran a specific dbt command)
so adding the DBT_USER is crucial for us.

all other environment variables are of less importance to us at the moment.

**Comment by Maayan-s** [comment]
https://github.com/elementary-data/dbt-data-reliability/pull/254
