### ISSUE TITLE
[ELE-162] Support defining anomaly detection time buckets at the model-level

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#557]
Currently they're only passed as a test's argument.

This requires duplication in case multiple Elementary tests are defined.

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-162](https://linear.app/elementary/issue/ELE-162/support-defining-anomaly-detection-time-buckets-at-the-model-level)</sub>

**Comment by Maayan-s** [comment]
Released in dbt package 0.7.7
