### ISSUE TITLE
[ELE-177] Add "dev" mode for Slack alerts

### ISSUE THREAD

**Issue by snirisl** [elementary-data/elementary#567]
**Is your feature request related to a problem? Please describe.**
We want a way to make sure that all slack alerts triggered when running `edr monitor` on any environment other than production will be sent to a dedicated slack channel, regardless of the channel configuration used in the command or configured in the models/tests/project.

**Describe the solution you'd like**
Configuration available to set slack channel/s when on dev mode.

**Describe alternatives you've considered**
We handle it currently by using conditional Jinja in the configuration in dbt yaml files.

<sub>[ELE-177](https://linear.app/elementary/issue/ELE-177/add-dev-mode-for-slack-alerts)</sub>

**Comment by Hadarsagiv** [comment]
Thanks for opening this issue @snirisl ! this makes a lot of sense.
We added this task to our backlog and it will go through our product prioritization process. Usually one of our considerations when prioritizing is the demand from the community. 
We'll keep you updated once we have news about this issue.

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1689336253165739

@ellakz this was actually requested before
