### ISSUE TITLE
[ELE-189] Monitor only a decrease in row count rather than absolute deviation

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#586]
**Is your feature request related to a problem? Please describe.**
I would like to monitor volume (row count) anomalies for my table,
however I don't mind if there's a substantial growth in the table,
only if there's a decrease in the row count.

**Describe the solution you'd like**
Currently we calculate anomalies by applying `abs()` to the anomaly score that represents the deviation from the average value. We need to add a test parameter that allows to choose the signedness of the deviation.
This functionality is [already available for the freshness tests](https://github.com/elementary-data/dbt-data-reliability/blob/a92bfb265a1fcf362cfe8ae13fe3b16dbedf7f75/macros/edr/tests/test_utils/get_anomaly_query.sql#L54), but it needs to be available for other tests, most notably `volume_anomalies`, as well.

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-189](https://linear.app/elementary/issue/ELE-189/monitor-only-a-decrease-in-row-count-rather-than-absolute-deviation)</sub>

**Comment by aarushisoni** [comment]
Hi, 
I want to work on this issue; please assign me to this.

**Comment by elongl** [comment]
Hi @aarushisoni, thanks a lot for willing to work on this issue.
At the moment, this feature requires a bit of product scoping in order to decide what should the user interface for this feature be.

@oravi @Hadarsagiv 
What's your take on it?

**Comment by oravi** [comment]
Hi! this is great and we actually want to generalize this request. We'd like to introduce a new flag called anomaly_direction that will be either `spike` or `drop`. This flag should be introduced in all of our anomaly detection tests (should be easy as we already support it in our freshness test). I'll add further design guidelines soon on how to do it
