### ISSUE TITLE
`dbt run --select elementary` fails on postgres

### ISSUE THREAD

**Issue by ckdake** [elementary-data/elementary#589]
**Describe the bug**

Thanks for getting postgres support merged! It looks like there is at least one small issue left with it to get it working:

`dbt run --select elementary` fails on postgres in `on-run-end`

**To Reproduce**
1. Install dbt 1.3.1 (https://github.com/elementary-data/elementary/issues/588 prevents even getting this far in 1.3.2)
2. Install and configure elementary 0.6.6 (following https://docs.elementary-data.com/quickstart)
3. Get to the step in setup, and run `dbt run --select elementary`

**Expected behavior**
Things work.

**Actual Result**
dbt errors out with:

```
16:07:41  Running 2 on-run-end hooks
16:07:41  Running dbt Constraints
16:07:41  Finished dbt Constraints
16:07:41  1 of 2 START hook: dbt_constraints.on-run-end.0 ................................ [RUN]
16:07:41  1 of 2 OK hook: dbt_constraints.on-run-end.0 ................................... [OK in 0.00s]
16:07:41  Database error while running on-run-end
16:07:41  Encountered an error:
Database Error
  syntax error at or near "dummy_string"
  LINE 6: ...t\n            \n                \n        cast(\'dummy_stri...
```

with `dbt --debug run --select elementary`, the relevant error message is added:

```
16:11:24.404134 [debug] [MainThread]: Postgres adapter: Postgres error: syntax error at or near "dummy_string"
LINE 6: ...t\n            \n                \n        cast(\'dummy_stri...
```

**Environment (please complete the following information):**
 - edr Version: 0.6.6
 - dbt package Version: 1.3.1
 - postgres version: psql (PostgreSQL) 15.1 (Debian 15.1-1.pgdg110+1)

**Comment by ckdake** [comment]
cc @elongl

**Comment by Maayan-s** [comment]
Hi @ckdake , 
On your `dbt_packages.yml`, did you configure 0.6.6 or 0.6.11?
```
packages:
  - package: elementary-data/elementary
    version: 0.6.11
```

**Comment by ckdake** [comment]
I did 0.6.6 to go with https://github.com/elementary-data/elementary/releases which labels 0.6.6 as newest. 0.6.11 (which I don't see on /releases?) does seem to work!  So this is a false alarm, but the 0.6.6 -vs- 0.6.11 is a hair confusing

**Comment by Maayan-s** [comment]
Yes, I get why this is confusing. 
We manage our dbt package in a different repo because of how the dbt packages hub work:
https://github.com/elementary-data/dbt-data-reliability

We have a pending issue with them on enabling managing both on the same repo, but not possible at the moment. 

We actually had a thought that we need to bump versions and make sure we are aligned in both.
cc: @haritamar @oravi

**Comment by Maayan-s** [comment]
So I'm closing the issue, please report if you encounter any issues with this new integration 🙏

**Comment by ckdake** [comment]
The version bump to be aligned on both would be a huge help for someone installing elementary for the first time. Thanks!
