### ISSUE TITLE
[ELE-207] Outdated metrics are used in anomaly tests after changing test's arguments

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#595]
**Describe the bug**
An anomaly test can use invalid metrics upon calculating the anomaly scores.

Currently the way we read the anomaly scores is by querying `data_monitoring_metrics` and filtering by:

1. Table name
2. Column name
3. Metric name
4. Dimension

This is problematic when editing the test's arguments, hence changing the metrics collected.

For instance, if a user:

1. Changed the `timestamp_column` - Metrics with the previous `timestamp_column` will still be used.
2. Added a `where_expression` - Metrics without the `where_expression` will still be used.
3. Defined `volume_anomalies` with a `time_bucket` of 1 hour, and then changed it to 6 hours, the 1 hour metrics will still be included in the anomaly scores.

**To Reproduce**

1. Define a `volume_anomalies` test with `time_bucket: {period: hour, count: 1}`.
2. Run the test.
3. Edit the test to `time_bucket: {period: hour, count: 6}`.

**Solution**

1. Create a `metric_id` that is built by `hash(table_name, column_name, metric_name, timestamp_column, time_bucket, where_expression, dimension)` in `data_monitoring_metrics`.
2. Change the metrics gathering in `get_anomaly_scores_query` to use the newly-added `metric_id`.

*Note*: The implementation may include more changes. Those are the main bullet points.

For context, a more obvious solution would've been to simply add the `test_unique_id` into `data_monitoring_metrics`.
The reason of not doing so is that we'd like to keep the metrics de-coupled from the tests as they serve a purpose on their own and with high probability, in the future we'll use them independently.

**Additional context**
Happened to @NoamMosko.

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-207](https://linear.app/elementary/issue/ELE-207/outdated-metrics-are-used-in-anomaly-tests-after-changing-tests)</sub>

**Comment by oravi** [comment]
This is happening only when changing params which affect the metrics calculation - 

1. timestamp column
2. where expression
3. time_bucket

It's not easy to detect a params change and if one of these is different we should treat it as a different metric as it impacts the way we calculate our metrics. Also we want to support having multiple metrics for the same metric_name but with different where / timestamp_column / time bucket. So doing a full refresh could be a workaround but not the ideal solution.

**Comment by elongl** [comment]
Why not generate the metric ID within the query that generates the metrics (table_monitoring_query)? I think it’s simpler to implement and also more intuitive.

**Comment by Maayan-s** [comment]
Cool, we instruct them to do it when we bump minor so we need to bump this time.
