### ISSUE TITLE
`dbt test` fails saving elementary results with postgres and large compiled model sizes

### ISSUE THREAD

**Issue by ckdake** [elementary-data/elementary#600]
**Describe the bug**

We're getting elementary up and running for the first time. Due to how dbt unit testing and macros interact, we end up with compiled files with 10s of 1000s of blank lines. Literally 87550 lines in our compiled unit tests folder, with only 75 lines of actual content. `dbt` handles these just fine without elementary.

With elementary, Running `dbt test` yields `Postgres adapter: Postgres error: value too long for type character varying(65535)`. With `dbt --debug test`, this is within a `insert into "[redacted-db-name]"."[redacted-schema-name]"."elementary_test_results"` query.  (A few lines up I see "'Model code is too long - over 10240 bytes',1,NULL)" as well.

I've spent some time going down the rabbit hole of using https://docs.getdbt.com/docs/get-started/learning-more/using-jinja#use-whitespace-control-to-tidy-up-compiled-code to reduce the output side, but its a pretty nasty rabbit hole. 

Looking at the schema, `varchar(65535)` is used for a lot of fields that do not need that much space (e.g. `id`). I'm not sure which field is blowing up here, but I bet it is `test_results_description`. It's set this way due to being a 'long_string' in the empty_table.sql macro. In Postgres, it would probably more appropriate to use a `text` column here which would have a bit more overhead (up to ~1GB).

What do you think? 

Can/should the type mappings for postgres better reflect expected data sizes? 

Can/should elementary trim whitespace-onlyl lines before saving?

Should dbt be stripping whitespace lines before saving things in `target/compiled/`? (potential dbt feature request)

Should I sink a bunch more time into adding `-` all over our tests? (I've lost a good few hours here already, without luck, there are macros inside of `dbt_unit_testing` interacting with ours)

**Environment (please complete the following information):**
 - edr Version: 0.6.7
 - dbt package Version: 0.6.11
 - backend: postgres

**Comment by elongl** [comment]
Hi @ckdake !
Thanks a lot for bringing this up.
I've created [this pull request](https://github.com/elementary-data/dbt-data-reliability/pull/238) that changes the data type of `long_string` from `varchar` to `text` as you said which should be unlimited in size.
![image](https://user-images.githubusercontent.com/30181361/213520021-0c91eb6f-f1c6-4d9f-8b02-89bf51236086.png)

Would you mind using this branch and validate that it solves your problem?
You can do so by updating `packages.yml` with the following data:

```yml
packages:
  - git: "https://github.com/elementary-data/dbt-data-reliability.git"
    revision: postgres-long-string-type
```

Afterwards run `dbt deps` and try the action that previously failed.
Thanks a lot.

**Comment by ckdake** [comment]
This looks like it will do the trick, thanks! I'm able to run `dbt test` with this branch, and the test results are correctly inserted.

It still 'smells' funny to me to have things like the `id` and `test_unique_id` column to be `text` instead of something tighter to what they may be, but given the workflow for dbt and elementary, this probably isn't a practical problem.

**Comment by elongl** [comment]
I can see your point.
However, I believe this is a different problem that we perhaps need to define different data types for those columns.
Thanks for testing, I'm merging this PR right now.

**Comment by elongl** [comment]
@ckdake 
From the [Postgres docs](https://www.postgresql.org/docs/current/datatype-character.html).
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/30181361/213526203-f0046386-74a8-4bff-96e2-d7620fa26704.png">
