### ISSUE TITLE
[ELE-217] Alert deduping

### ISSUE THREAD

**Issue by haritamar** [elementary-data/elementary#605]
**Is your feature request related to a problem? Please describe.**
This problem originated from the community (thread [here](https://elementary-community.slack.com/archives/C02CTC89LAX/p1674118291945399)) and relates to a **retry flow** - where a run is followed by a retry run to handle temporary issues such as db concurrency problems. We want to avoid sending multiple failures, or sending failures for nodes that succeeded in the retry run.

**Describe the solution you'd like**
We propose adding a dedup mechanism to the alert functionality in the CLI, which will support:
1. Sending each alert only once.
2. Sending only alerts that didn't have a successful run following them.

**Describe alternatives you've considered**
An alternative which was proposed is the ability to skip alerts on a specific dbt invocation. It is also a valid solution, but we feel the dedup can potentially be more generic and apply to other similar cases.

<sub>[ELE-217](https://linear.app/elementary/issue/ELE-217/alert-deduping)</sub>

**Comment by IDoneShaveIt** [comment]
We only do the 1 step - "sending each alert only once"

**Comment by Maayan-s** [comment]
@elongl will review

**Comment by haritamar** [comment]
To clarify - we're currently doing (1), but (2) may be mitigated in retry scenarios by running:
```edr monitor -s result:error```
(so we'll only include tests that failed in the last run, and the dedup feature guarantees we'll only send them once)
