### ISSUE TITLE
SQL compilation error when using column-level anomalies

### ISSUE THREAD

**Issue by nbdaw-st** [elementary-data/elementary#62]
Hey all,

I added the elementary package to the dbt repository and used `dbt run` to create all required tables. But when I tried to add column-level anomalies, the dbt run gave me an error as 
```
19:10:32    001003 (42000): SQL compilation error:
19:10:32    syntax error line 7 at position 19 unexpected '""'.
19:10:32    syntax error line 10 at position 15 unexpected ''day''.
19:10:32    syntax error line 10 at position 26 unexpected '('.
19:10:32    syntax error line 10 at position 40 unexpected 'as'.
19:10:32    syntax error line 12 at position 1 unexpected ')'.
```
The configuration I added to the yml file is as:
```
  - name: table_name
    config:
      elementary:
        timestamp_column: "_inserted_at"
    tests:
      - elementary.table_anomalies:
          table_anomalies:
            - row_count
            - freshness
    columns:
      - name: "id"
        description: " "
        quote: true
        tests:
          - not_null
          - unique
          - elementary.column_anomalies:
              column_anomalies:
                - missing_count
                - min_length
```
However, table-level anomalies worked as expected. I tried to look up compiled SQL files from target/compiled and target/run, but couldn't find any models relevant to this problem. Any ideas?

**Comment by Maayan-s** [comment]
Hi @nbdaw-st, I think from the error the problem might be the quotes around the column names.
Could you try to remove these from the yml and run again? 
Also which DWH are you using?

**Comment by nbdaw-st** [comment]
@Maayan-s Hey, thanks for the quick response. If the column is not quoted, column_anomalies can be run. Will you guys make this compatible with a quoted column in the future?

**Comment by nbdaw-st** [comment]
thanks!

**Comment by Maayan-s** [comment]
@nbdaw-st 
New version is live 0.3.10! 
If you can provide feedback that it works for you I will close the issue
