### ISSUE TITLE
Update Slack permissions screenshot

### ISSUE THREAD

**Issue by bendiktv2** [elementary-data/elementary#627]
**Describe the gap**
The picture of the Slack permissions needed for Elementary to send Slack-messages does not reflect the actual permissions needed. 

https://github.com/elementary-data/elementary/blob/master/docs/_snippets/setup-slack-integration.mdx#1-create-a-slack-token

The list above the screenshot lists 6 permissions, but the screenshot only lists 5 of them (`groups:read` is missing)

**Comment by Maayan-s** [comment]
Hi @bendiktv2 , 
Thank you for surfacing!
I see that we updated the permissions in text but the picture is indeed outdated.
Do you happen to have a screenshot with the right permissions?
(The docs are in the repo so you could open a PR if you do)

**Comment by bendiktv2** [comment]
Hello @Maayan-s ,
Please see attatched screenshot

![Screenshot 2023-01-31 at 07 52 39](https://user-images.githubusercontent.com/86664407/215687854-859ce593-ce91-415d-b538-fabcf1f41d5c.png)

**Comment by Maayan-s** [comment]
Looks great!!
Could you upload here:
https://github.com/elementary-data/elementary/tree/master/docs/pics
?
I can do it in a few hours if not. No worries.

**Comment by bendiktv2** [comment]
I would prefer it if I didn’t have to fork+clone+PR. I don’t have permissions to simply upload the file directly (understandably), so I have no qualms with waiting for you to handle it 😊

Thanks in advance 😊

--
Bendik Nesbø (Ulriken Consulting AS)
Konsulent for TV 2

From: Maayan Salom ***@***.***>
Date: Tuesday, 31 January 2023 at 07:58
To: elementary-data/elementary ***@***.***>
Cc: Bendik Nesbø (Ulriken Consulting AS) ***@***.***>, Mention ***@***.***>
Subject: Re: [elementary-data/elementary] Update Slack permissions screenshot (Issue #627)

Looks great!!
Could you upload here:
https://github.com/elementary-data/elementary/tree/master/docs/pics
?
I can do it in a few hours if not. No worries.
