### ISSUE TITLE
[BigQuery] Syntax error: Illegal escape sequence

### ISSUE THREAD

**Issue by obause** [elementary-data/elementary#63]
Hi, 
I'm testing your dbt package for our data warehouse which is placed on Google BigQuery
The generated sql scripts are producing erros. One big error is coming from the on-run-end hook:

```
Database Error
  Syntax error: Illegal escape sequence: \E at [6:566]
```

I've checked the generated SQL code and it seems that all backslashes coming from the model names are producing an error e.g. this part:
...'models\business_vault\EXCHANGERATESAPI\msrglB\currency_datedexchangerates_xrio_brs.sql','business_vault\EXCHANGERATESAPI\msrglB\currency_datedexchangerates_xrio_brs.sql','2022-04-05 11:04:47')

I think there is some escaping missing.

**Comment by oravi** [comment]
Hi, thanks for surfacing @obause!

I'll try to reproduce in my local env and debug the issue.

**Comment by oravi** [comment]
Hi, we have just released a new version and I believe this should also fix the issue on Windows. Could you please let us know if it works for you with the new version? 

Thanks!
