### ISSUE TITLE
[ELE-323] Add an alert configuration option in edr monitor CLI / config to send fail and warn tests alerts in distinct slack channels

### ISSUE THREAD

**Issue by moreaupascal56** [elementary-data/elementary#630]
**Is your feature request related to a problem? Please describe.**
Today I am using `edr monitor` to send slack alerts after a `dbt test` run.
As we have lots of tests that are warnings (that we should also fix but it is not the same severity level) the slack channel is sometimes flooded with warnings alerts and it can sometimes shadow fail alerts (and cause mental load to the team). 

I would love to have the possibility to use distinct slack channels for warn and fail tests. 

The only solution about this subject that I found today is the [configurations](https://docs.elementary-data.com/quickstart/send-slack-alerts#alert-types-configuration) in `dbt_project.yml`: 

```
vars:
  # Alerts configuration vars   #
  # All set to false by default #
  disable_model_alerts: false
  disable_test_alerts: false
  disable_warn_alerts: false
  disable_skipped_model_alerts: true
  disable_skipped_test_alerts: true
```

But that will disable warn (or fail) alerts for the whole project and I want to keep getting them but just somewhere else. 

**Describe the solution you'd like**
I was thinking about a new option in `edr monitor` CLI.  like `edr monitor --severity fail/warn`. 
Or by using the existing -c / --config option and by adding the values below to the config file: 
```
  disable_test_alerts: false
  disable_warn_alerts: false
```
(this seems less user friendly in my opinion)

**Describe alternatives you've considered**
Could not find any alternatives. 

**Would you be willing to contribute this feature?**
Yes I'd like to contribute

<sub>[ELE-323](https://linear.app/elementary/issue/ELE-323/add-an-alert-configuration-option-in-edr-monitor-cli-config-to-send)</sub>

**Comment by elongl** [comment]
This should've been possible by utilizing the `--project-dir` flag which allows using native dbt selectors.
Here's an example:

```bash
edr monitor --project-dir . --select config.severity:warn --slack-channel-name warning-alerts-channel
edr monitor --project-dir . --slack-channel-name default-alerts-channel
```

However, it seems like we currently have a bug that makes the native dbt selectors not work.
I've created an issue for it [here](https://github.com/elementary-data/elementary/issues/631).

**Comment by elongl** [comment]
@moreaupascal56 Yeah, I think the same way.
This should be easily solvable using selectors and it fits the use-case.
So I tend to think this issue can be closed.

@Hadarsagiv What do you think?

**Comment by Hadarsagiv** [comment]
@elongl - for now it seems like an acceptable workaround.
As it requires using the project dir, we need to make sure that it's documented and we need to consider stop to automatic uploading of artifacts. 
Once we document this we can close this issue.

**Comment by moreaupascal56** [comment]
Hello there, the workaround works, just a little objection:
in the case where a dbt test have a config like below: 
```
                config:
                  severity: error
                  error_if: ">10"
                  warn_if: ">0"

```

with several [severities](https://docs.getdbt.com/reference/resource-configs/severity) (depending on the test result), the selector `--select config.severity.warn` does not work as it should. 

In this case we want this test alert to go in the channel for warnings if the condition. ">0" and in the channel for errors for the condition ">10". 
Today it always go in the alert for errors because of the severity.




Because the severity does not change so I think we should maybe get something else (like the `test status`  - I do not know how it is called in the manifest.

**Comment by Maayan-s** [comment]
@moreaupascal56 
Maybe using the `--result` selector?
Check out this thread:
https://elementary-community.slack.com/archives/C02CTC89LAX/p1674118291945399
