### ISSUE TITLE
[ELE-321] dbt v1.4.0+: Native dbt selectors don't work (`--select` with `--project-dir`)

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#631]
**Describe the bug**
From dbt-1.4.0 onwards, the alerts selectors don't work when a dbt project directory is provided.
The bug seems to happen because `dbt ls --log-format json` now returns JSONs which it previously didn't.

```
# dbt 1.3.0
$  dbt --log-format json ls --select config.severity:warn
elementary_integration_tests.elementary_volume_anomalies_any_type_column_anomalies_hour__4

# dbt 1.4.1
$  dbt --log-format json ls --select config.severity:warn
{"data": {"msg": "elementary_integration_tests.elementary_volume_anomalies_any_type_column_anomalies_hour__4"}, "info": {"category": "", "code": "Z049", "extra": {}, "invocation_id": "9d0de6d7-a944-45c3-8dff-a7b091db7595", "level": "info", "msg": "elementary_integration_tests.elementary_volume_anomalies_any_type_column_anomalies_hour__4", "name": "ListCmdOut", "pid": 46966, "thread": "MainThread", "ts": "2023-02-01T16:02:04.756399Z"}}
```

**To Reproduce**

```
edr monitor --project-dir . --select config.severity:warn --slack-channel-name warning-alerts-channel
```

**Expected behavior**
I'd expect the warnings tests to be sent to `warning-alerts-channel`.
Instead, no alerts are detected.

**Proposed solutions**

1. Handle the JSONs.
2. Omit the `--log-format json` on `dbt ls`.

In any case, we should add tests to this feature.

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-321](https://linear.app/elementary/issue/ELE-321/dbt-v140-native-dbt-selectors-dont-work-select-with-project-dir)</sub>

**Comment by elongl** [comment]
Hi @moreaupascal56!
I believe the issue is that Elementary's Python package is out-dated on your machine.
I recommend that you upgrade to the latest version by invoking `pip install --upgrade elementary-data`.
Please give it a shot and let me know if that fixes your issue.
Thanks.

**Comment by moreaupascal56** [comment]
Yes seems to wok with newer versions :) thanks, following this issue before updating to dbt 1.4.0 then :)
