### ISSUE TITLE
Column size issue in 'all_columns_anomalies' test

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#64]
**Issue description:**
On the test 'all_columns_anomalies' the results table is created using the first batch of results (the first column), and the results column sizes are assigned by the content of this batch.
If there is a following batch with larger values, the insert of the batch fails. 

**Solution:**
Create the table with an empty template (like we do with the incremental tables). 

The fix will be deployed as part of the Redshift integration branch:
https://github.com/elementary-data/dbt-data-reliability/pull/20

**Comment by oravi** [comment]
Happy to update that this issue was fixed with version 0.3.12 of the dbt package. Closing this issue 🥳
