### ISSUE TITLE
support test owners

### ISSUE THREAD

**Issue by kimLalilo** [elementary-data/elementary#660]
**Describe the bug**
When we add an owner in meta on a custom generic test, owner doesn't appears in slack alert

**To Reproduce**
1. Create a custom generic test in DBT with a meta  
<img width="682" alt="Screen Shot 2023-02-08 at 22 22 57" src="https://user-images.githubusercontent.com/115019594/217843607-2b93e41a-5f7a-498c-b7a2-9051def75ada.png">

2. run the test and run a monitor to send an alert in a slack channel

3. See owner missing in alert
<img width="918" alt="Screen Shot 2023-02-08 at 22 23 09" src="https://user-images.githubusercontent.com/115019594/217844124-7a9b6b28-3821-4879-893f-ea932bcd9229.png">

**Expected behavior**
We expected to have the tag for owners as it appears for subscribers

**Screenshots**

**Environment (please complete the following information):**
 - edr Version: 0.6.7
 - dbt package Version: 0.9.2

**Additional context**

**Comment by elongl** [comment]
Hi @kimLalilo,
Starting in edr v0.6.10, we also support getting the owners from the test's `meta` field.
Please upgrade by running `pip install --upgrade elementary-data`.
Thanks.
