### ISSUE TITLE
[ELE-379] Improve nodes default position on the lineage graph

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#669]
According to @nimrodne, we’re currently not applying any special logic on the y coordinate of the nodes.
Only on the x coordinate.
We can try improving our logic to position the nodes closest to their parent (or parents) on the y axis.

This might improve usability for large graphs.

**Additional context**

@gautierdp

![](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/9cff0ce3-4cbf-48ef-8668-5e1883b17bea/1c6a2914-f7c5-4b3f-97f0-61e07735d360)

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-379](https://linear.app/elementary/issue/ELE-379/improve-nodes-default-position-on-the-lineage-graph)</sub>

**Comment by RoiTabach** [comment]
It sounds to me like we want the DOT layout https://graphviz.org/docs/layouts/dot/
I'll look a bit for alternatives
