### ISSUE TITLE
Multiple profiles for alerting

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#68]
Our current configuration for alerting using the CLI is to configure a profile named 'elementary' and provide it the schema where 'data_monitoring_metrics' is.
This means that there can only be one profile for alerting. 

The need here is to enable monitoring of two different schemas that are managed separately on the same db.

Hemant - could you confirm that this describes the need well?

**Comment by hemanthatgeir** [comment]
LGTM

**Comment by Maayan-s** [comment]
After some thought - the fast solution should be to use a single profile with multiple targets. The command 'edr monitor' would pass the target to the '--target' flag of the dbt runs that are invoked by the CLI.
