### ISSUE TITLE
[ELE-391] Folders in the report look empty although there are models in them

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#683]
**Describe the bug**
There are models in the folder, but selecting the folder shows an empty result. 
Seems like this happens when the original path and path columns in dbt_models use backslash in path name but the report expects forward slash.

**Screenshots**
Staging folder has 3 models but look empty:
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/22072028/219352792-d99b95e7-c2ba-44c2-8e9a-af4aac9283be.png">

**Additional context**
Reported by Tasos Kouridis.
https://elementary-community.slack.com/archives/C02CTC89LAX/p1676543589962929

<sub>[ELE-391](https://linear.app/elementary/issue/ELE-391/folders-in-the-report-look-empty-although-there-are-models-in-them)</sub>

**Comment by IDoneShaveIt** [comment]
Released on elementary python package 0.7.2
