### ISSUE TITLE
Databricks integration

### ISSUE THREAD

**Issue by oravi** [elementary-data/elementary#69]
This is a new type of integration that was requested in the [Slack community](https://elementary-community.slack.com/archives/C02BPB78J4T/p1650907380944009). 

- From a quick look it seems like dbt [already supports databricks](https://github.com/databricks/dbt-databricks) and it seems like most of the features are supported
- The monitoring is implemented as dbt tests and therefore we will need to run the package and its tests on a databricks env to see if the tests are working as expected on this platform

**Comment by sanjaykmenon** [comment]
would love to have this, so that i can start using elementary in our databricks instance

**Comment by Maayan-s** [comment]
Databricks is supported in version 0.4.8!! 
The support includes dbt observability + report + alerts.

We will add the anomaly detection tests support in later versions, will open a new issue about it.
