### ISSUE TITLE
WHERE_EXPRESSION json-schema-test

### ISSUE THREAD

**Issue by Deathfireofdoom** [elementary-data/elementary#697]
**Is your feature request related to a problem? Please describe.**
The JSON-schema test is a great test, but right now, looking at the macro is does not support the "where_expression". Since we will be using it to test schemas of event, it will be to heavy (or at least unnecessary) to test the old data every time we run the test. 

We only want to test the newest data, a good way to do this without keeping bookmarks is to use a where expression combined with dateadd and current_timestamp.

**Describe the solution you'd like**
I want the elementary.json_schema test to accept where_expression which should be the same where expression one would use to filter the data in SQL.

**Describe alternatives you've considered**
Alternatives I have considered is to create views with the where expression and test the views. This works but it is a hacky solution. 

**Additional context**

**Would you be willing to contribute this feature?**
I would love to contribute to this feature. 

While trying to debug why it didn't work I started to look at the code, and found this.

Working solution: 

File `edr/tests/test_json_schema.sql`

*Line 1*
```
{% test json_schema(model, column_name) %}
``` 
to 
```
{% test json_schema(model, column_name, where_expression) %}
```

*Line 14*
```
    {{ elementary.test_python(model, elementary.json_schema_python_test, {'column_name': column_name, 'json_schema': kwargs},
                              packages=['jsonschema']) }}
```
to
```
{{ elementary.test_python(model, elementary.json_schema_python_test, {'column_name': column_name, 'json_schema': kwargs, 'where_expression': where_expression},
                              packages=['jsonschema']) }}
```
*Line around 44*
Add this snippet:
```
where_expression = "{{ args.where_expression }}"
if where_expression:
    model_df = model_df.filter(where_expression)
```

**Comment by Deathfireofdoom** [comment]
This implementation is assuming the code in `def test` is pyspark code and model_df is a pyspark-dataframe until line `model_df = model_df.toPandas()`.

This should mean nothing is materialised until we get the data into pandas dataframe. 

Otherwise the filtering should probably be done earlier to avoid reading all data then filter.

**Comment by Deathfireofdoom** [comment]
As @Maayan-s mention this was a Python-test feature and not a specific json-schema-test feature.

Therefore I think a more generic solution, for all python test would be good.

Here is an idea on how to implement:

* To follow Elementary's naming-convention the parameter should be named `where_expression`, not like dbts `where`.
* The python test in `edr/tests/python.sql` could either be modified to accept the `where_expression` as a parameter. `{% test python(model, code_macro, macro_args, where_expression) %}` or the `macro_args` could be re-used(using `marco_args.where_expression` to access the where-clause). Re-using macro_args would be less invasive on the existing code, but adding `where_expression` would make the code more readable.
* The python code compiler in `edr/tests/test_utils/compile_py_code.py` will be modified to accept `macro_args` or just `where_expression`. `{% macro snowflake__compile_py_code(model, py_code, output_table, macro_args, code_type) %}`.
* Also, `macro_args` needs to be sent when being called form `python.sql`.
* In the main-function in `compile_py_code.sql`(both BQ and Snowflake) following code: is added to filter.

```
    where_expression = '{{ macro_args.where_expression|replace("'", "\\'")}}'
    if where_expression:
        model_df = model_df.filter(where_expression)
```

**Comment by elongl** [comment]
HI @Deathfireofdoom, thanks a lot for sharing your solution's design, looks great.

One important thing is that we want to abstract that it's a Python test.
In practice, this means that we want the `where_expression` to still be an SQL expression.
It seems that [`.filter()` supports it](https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.filter.html#pyspark-sql-dataframe-filter) (need to also check on Snowflake), so it's important to make sure to quote the `where_expression` which seems like you already did 👌🏽.

I tend to think that it's better to de-couple the new `where_expression` from `macro_args` so that it'll look like:

```yaml
models:
  - name: lost_orders
    tests:
      - elementary.python:
          where_expression: "status == 'lost'"
          code_macro: compare_tables
          macro_args:
            other_table: raw_orders
```

Also, I think it'd be better to conditionally render the `model_df.filter` only if the `where_expression` is not `None`.
For instance:
```py
{% if where_expression %}
model_df = model_df.filter("""{{ where_expression }}""")
{% endif %}
```

Looking forward to the PR!
Thanks a lot for the great work and thorough details.
