### ISSUE TITLE
Artifacts uploader fails on Bigquery if reaches query size limit

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#70]
The query on the artifacts uploader on-run-end hook failed with the following error:
```
Database error while running on-run-end
Encountered an error:
Database Error
  The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.
 
``` 
 
This probably happens on very large dbt projects.

**Comment by oravi** [comment]
Closing this issue as this is now solved with version 0.3.15 of the dbt package and 0.2.7 of the CLI
