### ISSUE TITLE
Support custom anomaly threshold

### ISSUE THREAD

**Issue by oravi** [elementary-data/elementary#71]
**Task Overview**

- Currently all anomalies are calculated statistically with a fixed global threshold (it's configurable with a var called anomaly_score_threshold, its default is 3). In some use cases it's better to define a more / less sensitive threshold based on the underlying dataset. Currently all the monitors are implemented as dbt tests and therefore the ideal solution would be to provide an additional test parameter that could receive this custom anomaly threshold for a specific test. If this parameter was not provided to the test, the the default should remain as it's configured with the global var 'anomaly_score_threshold'.

**Design** 

- There are three main files where the test macros are implemented - test_table_anomalies.sql, test_column_anomalies.sql and test_all_columns_anomalies.sql (please note that currently there is some code duplication in these files and in the future we will probably fix it). 
- All of these test macros should receive a new parameter (defined at the end) with a default value 'none', called 'anomaly_threshold'.
- Then each test should pass this value to the macro 'get_anomaly_query' 
- If the received value of this param is none, the code in 'get_anomaly_query' macro should use the macro elementary.get_config_var to get the global var 'anomaly_score_threshold' and use its value instead (this is the behavior today).
- Then the anomaly query should use this param (or the global value of the var anomaly_score_threshold) to determine if there is an anomaly or not (look for 'where abs(anomaly_score)')

**Comment by Ecalzo** [comment]
Hey @oravi I've attempted to start the implementation in https://github.com/elementary-data/dbt-data-reliability/pull/26 - happy to incorporate any feedback

**Comment by Maayan-s** [comment]
Added by @Ecalzo in version 0.3.16 of the package.
Thanks @Ecalzo 🌟
