### ISSUE TITLE
Python Test breaks EDR MONITOR 

### ISSUE THREAD

**Issue by Deathfireofdoom** [elementary-data/elementary#748]
**Describe the bug**
Running `edr monitor` after a failed python test with following error:

```json
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command - {'returncode': 1, 'cmd': ['dbt', '--log-format', 'json', 'run-operation', 'get_pending_test_alerts', '--args', '{"days_back": 1, "disable_samples": false}', '--project-dir', '/Users/oskarelvkull/Library/Python/3.8/lib/python/site-packages/elementary/monitor/dbt_project', '--target', 'prod'], 'output': b'{"code": "A001", "data": {"v": "=1.3.1"}, "invocation_id": "29566b3c-1385-4b8b-b4b0-6359240ce881", "level": "info", "log_version": 2, "msg": "Running with dbt=1.3.1", "pid": 13745, "thread_name": "MainThread", "ts": "2023-03-01T07:11:12.890608Z", "type": "log_line"}\n{"code": "Q001", "data": {"exc": "Database Error\\n  002003 (42S02): SQL compilation error:\\n  Object \'<REDACTED>.ELEMENTARY.PYTEST_TMP__ELEMENTARY_SOURCE_JSON_SCHEMA__BF323C23D3F5E6B18C3A3F1A8E995C6E\' does not exist or not authorized."}, "invocation_id": "29566b3c-1385-4b8b-b4b0-6359240ce881", "level": "error", "log_version": 2, "msg": "Encountered an error while running operation: Database Error\\n  002003 (42S02): SQL compilation error:\\n  Object \'<REDACTED>.ELEMENTARY.PYTEST_TMP__ELEMENTARY_SOURCE_JSON_SCHEMA__BF323C23D3F5E6B18C3A3F1A8E995C6E\' does not exist or not authorized.", "pid": 13745, "thread_name": "MainThread", "ts": "2023-03-01T07:11:14.623132Z", "type": "log_line"}\n', 'stderr': b''}
```

Running on Snowflake.

The reason why it fails seems to be that it tries to query a table, that is non-existent. The reason why the table does not exist is this line in `compile_py_code.sql`

`output_df.write.mode('overwrite').save_as_table(target_relation, table_type='temporary')`

The table is written as a temporary table and only exists in that exact session. Since the name include `tmp` it could be that the table should be `temporary` and the fault is somewhere in the `edr monitor`. 

A simple fix would be to remove the `table_type='temporary'` but the could be a reason why it is temporary, maybe the result of the test is fetching wrong "result query". 

**To Reproduce**
Any failing python test in Snowflake should cause this error. 

**Expected behavior**
The expected behaviour would be that `edr monitor` does not fail.

**Screenshots**

**Environment (please complete the following information):**
 - edr Version: 0.7.2
 - dbt package Version: 0.7.1

**Additional context**

**Comment by elongl** [comment]
Hi @Deathfireofdoom, does this issue still occur?
I believe we've made some changes in the latest versions of `edr` and the dbt package that should prevent this from happening.

**Comment by haritamar** [comment]
Closing since there has been no response for a while, please open a new issue if relevant!
