### ISSUE TITLE
[ELE-517] Order slack messages by test run time ASC

### ISSUE THREAD

**Issue by willi-mueller** [elementary-data/elementary#749]
**Is your feature request related to a problem? Please describe.**
I'm confused when I scroll through the slack notifications because they are not clearly ordered.

**Describe the solution you'd like**
Order by test run timestamp ascending

**Describe alternatives you've considered**
Order by test name or model name. However, this would be inconsistent with the slack logic of having messages ordered by time.

**Additional context**
<img width="660" alt="Screenshot_2023-03-15_at_2_59_19_PM" src="https://user-images.githubusercontent.com/217980/225271337-919d343c-7295-4d31-8fa3-90b400ab8f95.png">

**Would you be willing to contribute this feature?**
Yes

<sub>[ELE-517](https://linear.app/elementary/issue/ELE-517/order-slack-messages-by-test-run-time-asc)</sub>

**Comment by RoiTabach** [comment]
Hi Willi! I am happy that you're open to contributing this feature.
In the code, the class that deals with alerting is `DataMonitoringAlerts` . On the `send_alerts` function inside of it, there's a call to group alerts per config (creating `GroupOfAlerts` objects with 1 alert or more, per the config) and then below https://github.com/elementary-data/elementary/blob/master/elementary/monitor/data_monitoring/data_monitoring_alerts.py#L170 there's a call to actually send the alerts one by one. Seems that place would be the most appropriate to add a call to sorting, something like
```python
alerts_groups = sorted(alerts_groups, key=lambda grp: max(alert.detected_at for alert in grp.alerts))
```
and then the next row will iterate over that sorted list.

Let me know here or via Slack if you need more help with contributing this feature!
