### ISSUE TITLE
[ELE-526] Allow local definition of days_back

### ISSUE THREAD

**Issue by jalriols** [elementary-data/elementary#756]
**Is your feature request related to a problem? Please describe.**
We have a source that receives tables with a quarterly frequency. I would need to set the global variable [days_back](https://docs.elementary-data.com/guides/elementary-tests-configuration#data-monitoring-global-vars) to 3 months, in order to detect anomalies on it. The downside is that it would increase 6 fold the computational cost for the rest of the project's tests.

**Describe the solution you'd like**
It would be cool if `days_back` could be set independently for each test.

**Describe alternatives you've considered**
None so far.

**Additional context**

**Would you be willing to contribute this feature?**
Willing to help, but I have a shallow knowledge of the library.

<sub>[ELE-526](https://linear.app/elementary/issue/ELE-526/allow-local-definition-of-days-back)</sub>

**Comment by RoiTabach** [comment]
Hi @jalriols 
Just to clarify - the anomalies are on daily granularity? The table gets data retroactively once per quarter of the quarter that just passed?

If it's on a quarterly granularity you can set it up in the test's parameters - check out this https://docs.elementary-data.com/guides/elementary-tests-configuration#test-arguments 

If indeed on a daily granularity - I agree this feature request makes sense, so product will prioritize it and we'll let you know once it's updated.

The stopgap / alternative solution you can use for now - if you want - is to just set the var to 90 days back globally - Most tests that run day after day will only need to run 1 day on each daily run, only if you add a new test it will backfill 90 days for the first run. So - indeed expensive computationally but maybe not to the extent you thought. (Hope that explanation was clear)

**Comment by RoiTabach** [comment]
> On your second comment, if increasing the days_back value only affects new tests, I am ok with it.
In the setup you described - if days_back is 90 days and a table gets an update of something that happened 90 days ago, this table's test will run on all these 90 days. So - the request for granularity in setting days_back is exactly what you need in here.

> You first suggested to set up a quarterly granularity in the test's parameters. What parameter do you refer to? 
I meant bucket size, yes.

Anyway - I think this is a possible fix. Do you want to contribute this? If yes I'll write up a few points on where in the code we should be getting this from, etc.

**Comment by Maayan-s** [comment]
@RoiTabach @jalriols 
Check @haritamar description on how to implement here:
https://github.com/elementary-data/elementary/issues/329#issuecomment-1375939171

**Comment by Maayan-s** [comment]
Closing as it's duplicated, will continue discussing in:
https://github.com/elementary-data/elementary/issues/329
