### ISSUE TITLE
[ELE-530] Change Unit Display Type of Y-Axis counts to account for large numbers

### ISSUE THREAD

**Issue by kevinsanz93** [elementary-data/elementary#758]
**Is your feature request related to a problem? Please describe.**
When a number of 8 digits is displayed, it is cut off.
![image](https://user-images.githubusercontent.com/41018734/225955692-a7b4f694-443f-4205-aa5f-2bc4b45be13e.png)

**Describe the solution you'd like**
Large numbers should be shortened where it makes sense.

2,501,000,000 -> 2.501B
100,000,000 -> 100M or 100,500,000 -> 100.5M
150,167 -> 150k

**Describe alternatives you've considered**
Alternative would be to have fewer rows in our data set?

**Additional context**

**Would you be willing to contribute this feature?**
Not at the moment.

<sub>[ELE-530](https://linear.app/elementary/issue/ELE-530/change-unit-display-type-of-y-axis-counts-to-account-for-large-numbers)</sub>

**Comment by Maayan-s** [comment]
Thanks @kevinsanz93 , I think we should fix it so changed it from feature request to a bug and passed to our FE team tickets. 
Will follow up and let you know once it's fixed!

**Comment by Hadarsagiv** [comment]
@kevinsanz93 this issue was fixed:)
