### ISSUE TITLE
[ELE-527] High memory consumption when running edr

### ISSUE THREAD

**Issue by RoiTabach** [elementary-data/elementary#761]
**Describe the problem**
Seems some of the users running edr are experiencing too high memory usage. Affecting their ability to run in CI / other dockers orchestration, but not so good anyway

**Describe the solution**
needs to be investigated first

**Additional context**
Happened in 2 users in support over the last two days:

Jake - see [https://elementary-community.slack.com/archives/C02CTC89LAX/p1678895828557069](https://elementary-community.slack.com/archives/C02CTC89LAX/p1678895828557069)

Oliver - see [https://elementary-community.slack.com/archives/C02CTC89LAX/p1678963756105439](https://elementary-community.slack.com/archives/C02CTC89LAX/p1678963756105439)

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-527](https://linear.app/elementary/issue/ELE-527/high-memory-consumption-when-running-edr)</sub>

**Comment by Maayan-s** [comment]
@oravi :
Ok here is my quick analysis for now when working with our CI data set -
- On disk html / json files are between 12-13 MB each
- send-report starts with around 100MB even before doing anything (is it the Python interpreter? click? imports we are doing? not sure yet but haven't looked it it thoroughly yet)
- The total memory in RAM was around 350MB (27x on the report size!)
- Expectedly data_monitoring.send_report increments the memory by 250M
  - Expectedly the heaviest part there was get_all_test_results_db_rowswith 219MB
    - There it was the run-operation with get_test_results with 196MB
    - Loading it from strings to dicts using json load added additional 21MB
  
![image](https://user-images.githubusercontent.com/22072028/226358989-88d4cedd-70a4-4441-9a71-a658561a64e7.png)
![image](https://user-images.githubusercontent.com/22072028/226359041-39fb2a98-b8ce-4579-bb6c-45497fc67727.png)
![image](https://user-images.githubusercontent.com/22072028/226359077-beb4c695-6394-495b-9376-c0e7b696f908.png)
![image](https://user-images.githubusercontent.com/22072028/226359104-a3053631-ca1e-4cda-a6a8-d2586e45a907.png)



You can see there that this line -->
`logger.debug(f"Output: {output}")`
Added alone ~114 MB
    
![image](https://user-images.githubusercontent.com/22072028/226358584-fb773bad-a7a1-4af5-ab2f-55f277250756.png)

Removing it reduced the memory by 1/3 (with my local setup) -
![image](https://user-images.githubusercontent.com/22072028/226358908-d35c23d9-4e47-44ac-b993-8eb5627b3017.png)

**Comment by francescomucio** [comment]
We are facing the same problem on Elementary 0.12.0. What was the solution here?

**Comment by jakeberesford-palmetto** [comment]
I've been pinned to v0.6.5 since hitting this issue. I think setting `--days-back` to `3` (or less than 7) may help, but I haven't had time to come back to this and test any other fixes.

**Comment by gvillafanetapia** [comment]
Have the same problem! Tried with the latest version (0.14.1) and could only get 4 last days of data with 5GB RAM in kubernetes. 🙃

**Comment by amishas157** [comment]
I am running into the same problem with elementary-version 0.15.1 (using bigquery adapter). I am looking with last 7 days of data and 8Gi memory OOMs
