### ISSUE TITLE
[ELE-746] Have anomaly testing specific to groups of date and other dimensions inside my model

### ISSUE THREAD

**Issue by dennisgera** [elementary-data/elementary#764]
**Is your feature request related to a problem? Please describe.**
I would like to configure a column anomaly test that works on groups of dimensions - not just time blocks.

**Describe the solution you'd like**
I want to make my anomaly testing specific to groupings of date and other dimensions inside my model.

**Describe alternatives you've considered**
Writing this as sql dbt test

**Additional context**

**Would you be willing to contribute this feature?**
Let us know if you're willing to contribute so that we'll be able to provide guidance.

<sub>[ELE-746](https://linear.app/elementary/issue/ELE-746/have-anomaly-testing-specific-to-groups-of-date-and-other-dimensions)</sub>

**Comment by sharma-vaibhav1** [comment]
Hi @Maayan-s @dennisgera I feel this feature would be super useful for everyone. Having dimension anomaly detection on other custom metrics is much needed in our use cases also.

**Comment by haritamar** [comment]
Hi all,
It is now possible to configure `dimensions` within the column anomalies test!
I'm going to go ahead and close this issue. If you feel some capabilities are missing there please open a new issue!

Cheers,
Itamar
