### ISSUE TITLE
Adjusting Anomaly Sensitivity 

### ISSUE THREAD

**Issue by vishaalkk** [elementary-data/elementary#780]
**Is your feature request related to a problem? Please describe.**

I have implemented `elementary.volumen_anomalies` on a bunch of source tables in our project. Currently, these tests run every 6 hours, and tables are generally stable. I haven't configured any test vars in `dbt_project.yml` so everything is using default.

On some tables, the row counts have changed by a tiny fraction, and Elementary is treating them as failures. Please see attached screenshots. 
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/13641827/228008687-07c54fee-d49b-46f5-a31f-4e81e7bf9316.png">

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/13641827/228008775-fd3d564c-3de1-4471-83ed-89686bbf7679.png">

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/13641827/228008865-5b787b19-1eb3-49d9-8039-3622a7df3ca0.png">

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/13641827/228008962-5103d954-48e3-4eb7-9818-d276fafaa28e.png">

**Describe the solution you'd like**
I do not have knowledge of sensitivity analysis, but something which will look at the average + the percentage change threshold?
This is what @RoiTabach suggested when I posted the question in Slack:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/13641827/228008420-a2278a69-ac21-41ed-9be1-2f1e275e0051.png">

**Describe alternatives you've considered**

**Additional context**

**Would you be willing to contribute this feature?**
Let us know if you're willing to contribute so that we'll be able to provide guidance.

**Comment by haritamar** [comment]
I believe the relevant feature that handles this issue and was added since the last comment is the `ignore_small_changes` parameter:
https://docs.elementary-data.com/data-tests/anomaly-detection-configuration/ignore_small_changes

I think it covers exactly this use case so I'm going to go ahead and close this issue.
