### ISSUE TITLE
[ELE-638] Azure Blob Storage & Elementary Data Cli

### ISSUE THREAD

**Issue by dharitsura248** [elementary-data/elementary#795]
Share observability report to Azure blob storage by using `edr send-report` command

<sub>[ELE-638](https://linear.app/elementary/issue/ELE-638/azure-blob-storage-and-elementary-data-cli)</sub>

**Comment by oravi** [comment]
Hi @dharitsura248 ! 

The design for this goes as follows - 

- Add new set of parameters that are required to upload the report to Azure blob to the Elementary CLI in monitor/cli.py. Go to the send_report endpoint and see how the S3 / GCS params are configured. 
- Populate the new params to Config.py (see how S3 / GCS params are populated there)
- Add new AzureBlobClient (take a look at S3Client or GCSClient). We will need to implement 2 main things here - 
  - create_client - static method to create the client 
  - send_report - uploads the report to Azure blob. if `self.config.update_bucket_website` is enabled it means that we will need to make this bucket a static website. This will enable users to access the report as a static website. The implementation on how to make a bucket a static website is a bit different between cloud providers but feel free to reach out and I can help with that as well. 
- In DataMonitoringReport initialize the new AzureBlobClient and use it in both send_report and upload_report functions in case the Azure blob params were given

Please let me know if you have any questions! would love to help with this
