### ISSUE TITLE
Add Version command to Elementary

### ISSUE THREAD

**Issue by FridayPush** [elementary-data/elementary#814]
**Is your feature request related to a problem? Please describe.**
When producing debug reports it's often helpful for users of the CLI to report their version. However currently the `edr` command does not have a `edr --version` command. Nor does `edr help` print the current version. 

**Describe the solution you'd like**
I'd like to have some variant of `edr --version` that prints the corresponding python package value. `0.7.7`, etc.

**Would you be willing to contribute this feature?**
Not at this time.

**Comment by manulpatel** [comment]
I would love to implement the feature. 

I have come up with 2 approaches as of now:
i) Print the package version along every cli command invoked. This can be done by adding `Running with edr={package.get_package_version()}` in the `click.secho()` under `invoke` function.
https://github.com/elementary-data/elementary/blob/b47035934b8392a8a342de26c7ad1845d8f65486/elementary/cli/cli.py#L62


ii) We could create a new command "version" under `_CMD_MAP` list and define its function elsewhere in separete file like current functions such as monitor,report, send_report.
https://github.com/elementary-data/elementary/blob/b47035934b8392a8a342de26c7ad1845d8f65486/elementary/cli/cli.py#L66

**Comment by Maayan-s** [comment]
Hi @manulpatel, thank you for offering! 
I think that for the purpose of issues debug it makes more sense to go with the second. 
This is also a good prep to add resolution suggestions to [incompatibility between package and CLI](https://github.com/elementary-data/elementary/blob/master/elementary/monitor/data_monitoring/data_monitoring.py#:~:text=def-,_check_dbt_package_compatibility,-(dbt_pkg_ver%3A) and recommend upgrades. 

As reference, see dbt --version:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/22072028/235343635-93e7aaaf-cd22-4d14-a021-bcd8e1799ef6.png">
