### ISSUE TITLE
[ELE-699] group_alerts_by in config.yml not respected

### ISSUE THREAD

**Issue by dimoschi** [elementary-data/elementary#816]
**Describe the bug**
The `group_alerts_by` value in config.yml is not respected because the option has a default value of alerts.
https://github.com/elementary-data/elementary/blob/2bc0204ca304f9205bfa6964a41937294e7ec3c8/elementary/monitor/cli.py#L217-L222

So eventually when the `Config` is instantiated, the `self.slack_group_alerts_by` gets the default value that is first and not the config value.
https://github.com/elementary-data/elementary/blob/2bc0204ca304f9205bfa6964a41937294e7ec3c8/elementary/config/config.py#L111-L115

**To Reproduce**
1. Setup config.yml with `group_alerts_by: "table"`
2. Run `edr monitor`
3. Check in Slack that the alerts are not grouped by table

**Expected behavior**
My expectations were:
* for the command to run using the config value of `group_alerts_by`
* for the Slack alerts to be grouped by table

**Environment (please complete the following information):**
 - edr Version: 0.7.7
 - dbt package Version: 0.7.5

**Additional context**
My proposal is to make the default value in `click.option` to be `None`, since later the `alert` is the default fallback.

I can create a PR if you'd like. 

<sub>[ELE-699](https://linear.app/elementary/issue/ELE-699/group-alerts-by-in-configyml-not-respected)</sub>

**Comment by RoiTabach** [comment]
@dimoschi 
1. Good catch
2. Thanks for the in depth analysis
3. Sure thing! I think if you open a PR for a fix that will be great. I can provide guidance and make sure the automation runs tests on it, just tag me in the PR

**Comment by dimoschi** [comment]
> @dimoschi
> 
> 1. Good catch
> 2. Thanks for the in depth analysis
> 3. Sure thing! I think if you open a PR for a fix that will be great. I can provide guidance and make sure the automation runs tests on it, just tag me in the PR

Thank you @RoiTabach. I've created PR #819, however, I couldn't run the tests, but I've tested locally in my dbt setup. Let me know how can we proceed.
