### ISSUE TITLE
[ELE-700] Add default values to `time_bucket` if only count or period are passed

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#817]
Currently, the default is `count=1, period=day`. 
If the user only changes one of these, for example `period=hour` the test fails because `count` is missing. 

<sub>[ELE-700](https://linear.app/elementary/issue/ELE-700/add-default-values-to-time-bucket-if-only-count-or-period-are-passed)</sub>

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1681720115547899
https://elementary-community.slack.com/archives/C02CTC89LAX/p1682026511522449

**Comment by RoiTabach** [comment]
Suggesting we raise an indicative compilation error and force the user to actually explicitly say both count and period?

**Comment by Maayan-s** [comment]
No, I think it's reasonable to override just one param. 
If you pass `period: week` the default of `count: 1` should still apply.

**Comment by RoiTabach** [comment]
I am concerned with the other way around: not sure that a `count` of 1 means it's 1 day and not 1 hour for example.
