### ISSUE TITLE
Problem with '-d' param in 'edr lineage generate'

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#82]
The context is not being passed from the [lineage](https://github.com/elementary-data/elementary/blob/master/lineage/cli.py#L160) to the [generate](https://github.com/elementary-data/elementary/blob/master/lineage/cli.py#L245).

If you print the profiles_dir on lineage() and if you print it on generate() you get different values.
The one on lineage() is the expected one, and generate() just have the default values no matter what ~/.dbt .

Reported by @elongl.
Slack thread with details:
https://elementary-community.slack.com/archives/C02CTC89LAX/p1654904945951899

**Comment by elongl** [comment]
Not that big of a deal, but it's not just `-d` it's that the `lineage` parameters are not passed in general to the `generate` command. I suppose it's only been tested with the default options.
