### ISSUE TITLE
[ELE-742] Sample size in UI

### ISSUE THREAD

**Issue by skyveider** [elementary-data/elementary#822]
Hi! The parameter test_sample_row_count is not affected UI (html report). 

For example I will be seeing 5 rows in html report instead of 10 if set this parameter equal to 10

<sub>[ELE-742](https://linear.app/elementary/issue/ELE-742/sample-size-in-ui)</sub>

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1682258791786689?thread_ts=1682189527.028859&cid=C02CTC89LAX
