### ISSUE TITLE
[ELE-740] `upload-source-freshness` can overflow CLI arguments max size

### ISSUE THREAD

**Issue by elongl** [elementary-data/elementary#836]
**Describe the problem**
After a user runs `dbt source freshness`, a file is generated under `target/sources.json`. If a user has many source with freshness defined, the file would be respectively large. The way `edr` uploads the source freshness data to the warehouse is by running a macro and providing the results as an argument to the macro like so:

```
dbt run-operation upload_source_freshness --args '{"results": <DATA>}'
```

The problem is that `<DATA>` (freshness of all the sources) is too big and therefore the argument list is too long in the command itself.

**Describe the solution**
Upload the source freshness to the warehouse in chunks, essentially running the macro multiple times.

**Additional context**
[Slack thread](https://elementary-community.slack.com/archives/C02CTC89LAX/p1682603034308799)

**Reviewer**
@elongl 

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-740](https://linear.app/elementary/issue/ELE-740/upload-source-freshness-can-overflow-cli-arguments-max-size)</sub>

**Comment by fredmny** [comment]
Hey @elongl 
I made suggestion on [PR 850](https://github.com/elementary-data/elementary/pull/850). Let me konw your thoughts
