### ISSUE TITLE
[ELE-774] Hard to see long table names in the report

### ISSUE THREAD

**Issue by oravi** [elementary-data/elementary#841]
**Describe the bug**
From a thread in the community - 
"Nearly all of our Table names don’t fit in the table_name column of any view in the UI even with report pretty large. When expanding a row there’s no visual of what that table is requiring a user to mouse over each table that has a warning or error individually. This is true in the sidebar as well. We use a similar naming format as quite a few public projects like Fivetran which is either <domain>__<table> <stg_domain__table> etc. For us this essentially means that if, for example, 6 tables have warnings after the weekend the sidebar filtered for warnings/failures. And the test results page doesn’t tell us anything unless we hover one by one."

**To Reproduce**
Generate an elementary report for tables with long names.

**Expected behavior**
A user can clearly see the table, column and test names in the test results table.

**Screenshots**
![Screen Shot 2023-05-01 at 8 02 20 AM](https://user-images.githubusercontent.com/4517234/235501277-6af884c6-9a1f-43b1-af8a-6ede15407dac.png)

<sub>[ELE-774](https://linear.app/elementary/issue/ELE-774/hard-to-see-long-table-names-in-the-report)</sub>

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1682954226118479

**Comment by Hadarsagiv** [comment]
We improved our tables experience for environments with long tables name:
- We've added the ability to minimize the side bar
- We've set a default width for some of the columns to allow the table name column to expand more
