### ISSUE TITLE
[ELE-777] Add default descriptions to Elementary tests

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#843]
To present instead of this:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/22072028/235664046-913ad89f-994f-4ba8-a9e3-ead4bc3085a4.png">

<sub>[ELE-777](https://linear.app/elementary/issue/ELE-777/add-default-descriptions-to-elementary-tests)</sub>

**Comment by elongl** [comment]
Added in https://github.com/elementary-data/dbt-data-reliability/pull/514.
