### ISSUE TITLE
[ELE-1254] Table name missing in Elementary report for Relationship where dbt expectation tests & for relationship generic tests

### ISSUE THREAD

**Issue by syerrapalli** [elementary-data/elementary#853]
**Describe the bug**
Table name missing in Elementary report for Relationship where dbt expectation tests & for relationship generic tests

**To Reproduce**

1. Go to 'models>>source>>yml file and define dbt expectation relationshipwhere/relationship generic  tests'
2. run dbt test
3. generate edr report
4. In Test Results & Test Runs we do not see table name being displayed for "relationship where"/reatlionship generic tests

**Expected behavior**
Shoulb be able to see Table name displayed for relationship where/realtionships tests.

**Screenshots**

![](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/1005d75f-f851-44a5-9054-9dd80747759b/80b1d29a-0a4a-4afb-ba94-36b29714da14)

[dbt_tests_202305081105.csv](https://github.com/elementary-data/elementary/files/11422711/dbt_tests_202305081105.csv)

**Environment (please complete the following information):**

* edr Version: Version: 0.7.7
* dbt package Version: \[e.g. 0.4.1\], can be found in `packages.yml` file

**Additional context**
Notes from Support team member:I think I know what the problem is.
For each test we try and match the node it depends on. Some tests (like this one) depends on 2 nodes. In that case we can't know which node is the main one (on some test there isn't even a main one - singular tests for example), so we can't show it's table.
We need to understand how we can extract the relevant table from the 2.

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-1254](https://linear.app/elementary/issue/ELE-1254/table-name-missing-in-elementary-report-for-relationship-where-dbt)</sub>

**Comment by oravi** [comment]
This happens only in sources

**Comment by elongl** [comment]
I believe this happens because we use a [heuristic](https://github.com/elementary-data/dbt-data-reliability/blob/2e95cf900ea263341d057c552fb6fb0a7dfe41b4/macros/edr/dbt_artifacts/upload_dbt_tests.sql#L102) to resolve the parent model. It works by matching on `ref(…)`, however, when working with sources, dbt outputs `source(<SOURCE>, <TABLE>)` and we should also support matching on that format.

**Comment by Kevin-Grismore** [comment]
Hey, I just want to say this would also be incredibly useful for me, as I'm testing relationships between sources pretty often and I'd like relationship test failures to show on the parent node in the lineage graph.

**Comment by elongl** [comment]
Hi @Kevin-Grismore, thanks for sharing that.
@ellakz is working on that in the upcoming week or two.
You're invited to subscribe to this issue to get updates on it.

**Comment by RonanObert** [comment]
Hi,
@elongl, that seems to be the reason :
> I believe this happens because we use a [heuristic](https://github.com/elementary-data/dbt-data-reliability/blob/2e95cf900ea263341d057c552fb6fb0a7dfe41b4/macros/edr/dbt_artifacts/upload_dbt_tests.sql#L102) to resolve the parent model. It works by matching on `ref(<TABLE>)`, however, when working with sources, dbt outputs `source(<SOURCE>, <TABLE>)` and we should also support matching on that format.


I suggest you simply add source management to the heuristics as follows:
```
{% if not test_model_name_matches %}
   {% set test_model_name_matches = modules.re.findall("source\(['\"]\w+['\"], ['\"](\w+)['\"]\)|ref\(['\"](\w+)['\"]\)", test_model_jinja) %}
{% endif %}
```

**Comment by RonanObert** [comment]
It seems simpler to me to manage this via a condition to avoid managing Null expressions in the findall.

```
{% if not test_model_name_matches %}
    {% set test_model_name_matches = modules.re.findall("source\(['\"]\w+['\"], ['\"](\w+)['\"]\)", test_model_jinja) %}
{% endif %}
```

**Comment by Maayan-s** [comment]
@noaKurman note that this fix was contributed:

[https://github.com/elementary-data/dbt-data-reliability/pull/443](https://github.com/elementary-data/dbt-data-reliability/pull/443)
