### ISSUE TITLE
[ELE-847] Add materialization to dbt_run_results

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#860]
Slack link: [https://elementary-community.slack.com/archives/C02CTC89LAX?cid=C02CTC89LAX&thread_ts=1683731660.594379](https://elementary-community.slack.com/archives/C02CTC89LAX?cid=C02CTC89LAX&thread_ts=1683731660.594379)

Matt Feeser:

Right now we’re trying to tune some models. We’re finding that some models, due to data volume, run faster when materialized as  `incremental` vs `table` , however this information is not captured in the `DBT_RUN_RESULTS` table. It does capture whether the execution included the `full-refresh` optional parameter, but not the materialization of the specific execution. Is there a way to see this for each execution, or is it only available for the most recent execution via the `DBT_MODELS`  table? I’d like to retrieve an average runtime of a model grouped by the materialization type so that we can see which materialization type typically runs faster. Surprisingly it’s not always `incremental` with large source tables.

Elon:

Hi [@Matt Feeser](https://elementary-community.slack.com/team/U040HHFSF18), thanks for the thorough description 🙏🏻

You're correct, at the moment there's no way of doing so as the materialization is only stored in the `dbt_models`. However, adding that should be very easy.
Here's the change required:

1. Add a new column in the `dbt_run_results` table [here](https://github.com/elementary-data/dbt-data-reliability/blob/2e95cf900ea263341d057c552fb6fb0a7dfe41b4/macros/edr/dbt_artifacts/upload_run_results.sql#L30-L31).
2. Read the materialization from `run_result.config.materialized` [here](https://github.com/elementary-data/dbt-data-reliability/blob/2e95cf900ea263341d057c552fb6fb0a7dfe41b4/macros/edr/dbt_artifacts/upload_run_results.sql#L58).

Would you be interested in contributing it?
I'd be able to provide assistance if necessary.

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-847](https://linear.app/elementary/issue/ELE-847/add-materialization-to-dbt-run-results)</sub>

**Comment by arilmav** [comment]
@Maayan-s would love to work on this. Got a solution working by adding the following to the upload_run_results macro:

![Screenshot 2023-05-15 at 9 46 44 PM](https://github.com/elementary-data/elementary/assets/60354578/711f42ae-985c-4bba-b52c-0d395b719d32)
