### ISSUE TITLE
[ELE-37] Detection of deleted columns in Bigquery

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#88]
Elementary pulls the data to detect schema changes from the information schema columns view.
This view is updated in a delay (unclear how long), so the alert on deleted columns is delayed as well.

**Possible solution**
Research if there is an alternative source that updates in real time. 

<sub>[ELE-37](https://linear.app/elementary/issue/ELE-37/detection-of-deleted-columns-in-bigquery)</sub>

**Comment by oravi** [comment]
Test comment

**Comment by haritamar** [comment]
Closing this issue since it's pretty old, but please re-open if still relevant!
