### ISSUE TITLE
[ELE-934] [ELE-344] Configuring alerts_config overrides global alerts_config

### ISSUE THREAD

**Issue by IDoneShaveIt** [elementary-data/elementary#894]
**Describe the problem**
When configuring a global alerts_config and specific alerts_config (directly to a model /test), because it's a nested meta attribute, the specific configuration overrides the whole global configuration.

For example:

1. `dbt_project.yml` alerts_config is set to `suppression_interval: 1` and `channel: main`
2. The model alerts_config at the `schema.yml` is set to `channel: dev`

The alerts_config of the model will override the suppression_interval and now it will be set to 0 (by default).

This is an unwanted behavour - we want to only override the channel

**Describe the solution**
We need to see if we can do a deep merging between the 2 configurations.

If not, we can flatten the configuration and not support nested configuration.

**Describe the tests of the solution**
Test that defining alerts_config does a merge between the configuration instead of override it completely

**Additional context**
\- [https://elementary-community.slack.com/archives/C02CTC89LAX/p1674743690650599?thread_ts=1673893162.838399&cid=C02CTC89LAX](https://elementary-community.slack.com/archives/C02CTC89LAX/p1674743690650599?thread_ts=1673893162.838399&cid=C02CTC89LAX)

* [https://elementary-community.slack.com/archives/C04VD7AANNB/p1683287533210229](https://elementary-community.slack.com/archives/C04VD7AANNB/p1683287533210229)
* [https://elementary-community.slack.com/archives/C02CTC89LAX/p1675932347555719](https://elementary-community.slack.com/archives/C02CTC89LAX/p1675932347555719)

![image.png](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/29229f29-3404-42e8-b0dc-c4e42766f435/1531fbd2-d67e-4750-9f48-b9dc28de88e9)

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-344](https://linear.app/elementary/issue/ELE-344/configuring-alerts-config-overrides-global-alerts-config)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-344](https://linear.app/elementary/issue/ELE-344/configuring-alerts-config-overrides-global-alerts-config)</sub>

**Comment by IDoneShaveIt** [comment]
Arado had this issue.

Here the thread: [https://elementary-community.slack.com/archives/C04VD7AANNB/p1683287533210229](https://elementary-community.slack.com/archives/C04VD7AANNB/p1683287533210229)

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1682073866770489

**Comment by elongl** [comment]
@Maayan-s Would you like to link the PR for that issue?

**Comment by elongl** [comment]
This task could be solved by changing the docs to define the flattened config keys rather than `alerts_config` and that's it.

**Comment by Maayan-s** [comment]
@elongl 
You might be right, however:
1. I'm not sure all params are supported in the flat format. 
2. If a user has mixed config (dict and flat format), what will happen?
3. I believe subscribers should be an aggregated field, don't think the current code covers it. 
4. I'm not sure if the current code covers both meta and config.

**Comment by elongl** [comment]
@IDoneShaveIt Given that you implemented that can you share what's the behavior of for each bullet @Maayan-s raised?

Regarding (2), since we'll deprecate the `alerts_config` we can tell users who have a problem with that to flatten it and with time there won't be such users anymore.

**Comment by IDoneShaveIt** [comment]
Hey @Maayan-s and @elongl, regarding the points you were raising:

1. They way the flattening works is by combining the meta dict with the alerts_config dict with the following code:
```python
def _flatten_meta(self, node_meta_field: str) -> dict:
    # backwards compatibility for alert configuration
    meta = try_load_json(self.alert.get(node_meta_field)) or {}
    flatten_meta = {**meta, **meta.get(ALERTS_CONFIG_KEY, {})}
    flatten_meta.pop(ALERTS_CONFIG_KEY, None)
    return flatten_meta
``` 
The meaning of this is that we support all of the params here.

2. If a user has a mixed configuration, the alerts_config will override the flat ones. The reason for that is that we said that the flatten way was deprecated and that we want the users to use the alert_config object. It can be easily changed to the other way by changing the method from point 1 to the following code:
```python
def _flatten_meta(self, node_meta_field: str) -> dict:
    # backwards compatibility for alert configuration
    meta = try_load_json(self.alert.get(node_meta_field)) or {}
    flatten_meta = {**meta.get(ALERTS_CONFIG_KEY, {}), **meta}
    flatten_meta.pop(ALERTS_CONFIG_KEY, None)
    return flatten_meta
```

3. Actually subscribers are aggregated in the current state of our alerts 🙂
You can see in the following code that we use both the test and the model meta:
```python
def _get_alert_meta_attrs(self, meta_key: str) -> List[Optional[str]]:
    attrs = []
    test_attrs = self.test_meta.get(meta_key, [])
    model_attrs = self.model_meta.get(meta_key, [])
    if isinstance(test_attrs, list):
        attrs.extend(test_attrs)
    else:
        attrs.append(test_attrs)
    if isinstance(model_attrs, list):
        attrs.extend(model_attrs)
    else:
        attrs.append(model_attrs)
    return attrs
```

4. I am not sure which key is should be under the config. Care to elaborate why we would like to support both config and meta and not choosing only one way?

**Comment by elongl** [comment]
@Maayan-s I suggest that I'll make the flat ones take priority and remove the `alerts_config` in the docs.

What do you think?

**Comment by IDoneShaveIt** [comment]
@Maayan-s there should already be tests for that :)

**Comment by Maayan-s** [comment]
@IDoneShaveIt So why didn't we catch the dicts override issue?

**Comment by IDoneShaveIt** [comment]
@Maayan-s The problem with the dicts override is that it is happening on dbt level and passed to the meta as already overridden.
The tests we have check that we handle correctly the params from the test and model meta. We test that the flattening method, subscribers union and that backwards comp are working, but we don't have the infra to test a flow where we check that the dbt project yamls are matching the final alert.

@elongl maybe we can do a similar trick to the e2e test we have on the python package for the report, and assume that one of our e2e dbt tests won't change and we can test the final result of the alert. It can work but this has high chances to break though.

**Comment by elongl** [comment]
Let's go simple and just guide our users to not get into that problem in the first place by editing the docs and obsoleting the `alerts_config`. I'm marking this issue as completed for now. Good learning about nested configurations in dbt.
