### ISSUE TITLE
Elementary take longer time to finish dbt run

### ISSUE THREAD

**Issue by Sunnyinho** [elementary-data/elementary#895]
**Describe the bug**

Usually, when I run a model in dbt with command `dbt run -s <model_name>` it takes around 5-10 sec to complete the run. Since I have integrated the elementary package in dbt, it takes about 60-70 sec more to complete the run. Usually, it takes time in on-run-end hook.

**To Reproduce**
1. Go to 'your dbt project'
2. run any model with dbt cli `dbt run -s <model_name>`
3. Wait for the run to finish.
4. Process stuck at  `on-run-end`

**Expected behavior**
I wish that the execution of elementary happens faster.

**Screenshots**
The time log provides the execution time in this screenshot.
<img width="1157" alt="Screenshot 2023-05-24 at 09 16 10" src="https://github.com/elementary-data/elementary/assets/34419524/bca0f96b-4632-45e1-8e7e-407c03178cfb">

**Environment (please complete the following information):**
 - edr Version: [e.g. 0.5.3], can be found by running `pip show elementary-data`
    The version of Elementary is  `0.7.8`

 - dbt package Version: [e.g. 0.4.1], can be found in `packages.yml` file
  The package version is 
```yml
  - package: elementary-data/elementary
    version: 0.7.5
```

**Additional context**

**Comment by NoyaArie** [comment]
@Sunnyinho please upgrade to dbt 1.4.0, this should help. 
[Here](https://docs.elementary-data.com/dbt/on-run-end_hooks#metadata-models) is a link to our docs for more information about it.
