### ISSUE TITLE
[ELE-946] Allow setting an SQL expression as a timestamp column

### ISSUE THREAD

**Issue by shyamk136** [elementary-data/elementary#897]
**Is your feature request related to a problem? Please describe.**
When setting the timestamp column for a freshness anomaly test, we are unable to use a nested field from a struct type column. Storing table metadata like ingestion timestamps in a struct column is a common enough practice.

**Describe the solution you'd like**
It would be great if we are able to pass a nested value from a struct column (i.e., `_meta.ingested_at`) when configuring tests. 

**Describe alternatives you've considered**
An alternative of using a valid SQL expression was suggested. Have not tested it.

**Additional context**
Related Slack post link - https://elementary-community.slack.com/archives/C02CTC89LAX/p1684934480465639

**Would you be willing to contribute this feature?**
Not right now

<sub>[ELE-946](https://linear.app/elementary/issue/ELE-946/allow-setting-an-sql-expression-as-a-timestamp-column)</sub>

**Comment by Maayan-s** [comment]
Another relevant use case - 
https://elementary-community.slack.com/archives/C02CTC89LAX/p1683764020831119

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1686748178330809

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1687385776940869

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1688654551488189
