### ISSUE TITLE
[ELE-994] Add `detection_delay` to anomalies detection period

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#911]
**Describe the problem**
Sometimes the volume and freshness tests are running before the latest batch of data is loaded into the table, causing it to look like there's a drop in volume / freshness issue when in fact the latest load of data didn't run yet.

**Describe the solution**
If there's no way to reschedule the test run time, we need to have the test exclude a certain period of time from the detection period. we need to add a param to support that.

it could be something like 'ignore latest bucket' or 'period to ignore' .

when running the test, the data of the ignored period will not be loaded into data_monitoring_metrics

* If we are removing the "bucket" setting from the freshness test we need to think of a param in units other than buckets

**Describe the tests of the solution**
add the setting and run the test. make sure the data is not included in the report and not found in data_monitoring_metrics

**Describe the documentation**
The new param + usage should be added to the anomaly test docs

**Additional Context**

[https://elementary-community.slack.com/archives/C02CTC89LAX/p1685329307468749](https://elementary-community.slack.com/archives/C02CTC89LAX/p1685329307468749)

[https://elementary-community.slack.com/archives/C02CTC89LAX/p1682044085432779](https://elementary-community.slack.com/archives/C02CTC89LAX/p1682044085432779)

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-994](https://linear.app/elementary/issue/ELE-994/add-detection-delay-to-anomalies-detection-period)</sub>

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1686562047916199

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1693326052904229

**Comment by ellakz** [comment]
PR from contributor:

[https://github.com/elementary-data/dbt-data-reliability/pull/519/files](https://github.com/elementary-data/dbt-data-reliability/pull/519/files)

**Comment by ofek1weiss** [comment]
Currently does not pass tests (seems like a test issue rather then contribution issue).
