### ISSUE TITLE
Integrate linage visualization with the report UI

### ISSUE THREAD

**Issue by yu-iskw** [elementary-data/elementary#92]
## Motivation
The report UI is awesome. When we find failures on a table, we would like to investigate affected downstream tables. So, it would be great to support the lineage feature in the report UI.

**Comment by yu-iskw** [comment]
@Maayan-s That sounds awesome! I would love to be involved in the discussion as well. If there is anything I can do, please let me know.

**Comment by Maayan-s** [comment]
Added V1 support in 0.4.5 :)

**Comment by yu-iskw** [comment]
@Maayan-s Awesome. Do you have a plan to visualize graph dependencies of tables on the web UI in the future? Personally, that would be easy to understand downstream models of a violated model.

**Comment by Maayan-s** [comment]
Yes, working on it!

**Comment by Maayan-s** [comment]
Just released @yu-iskw :)

**Comment by yu-iskw** [comment]
This is awesome. I will give it a try asap. Thank you for supporting.
