### ISSUE TITLE
[ELE-1084] Add Elementary favicon to the report

### ISSUE THREAD

**Issue by Maayan-s** [elementary-data/elementary#933]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1686533920627359

<sub>[ELE-1084](https://linear.app/elementary/issue/ELE-1084/add-elementary-favicon-to-the-report)</sub>

**Comment by HotDiggityDogz** [comment]
🥰. Yes, thank you for adding the issue here.  I will keep an eye on it!

**Comment by manulpatel** [comment]
Hello @Maayan-s! I would love to contribute to display the favicon icon of elementary. I belive adding the [elementary icon](https://github.com/elementary-data/elementary/blob/master/static/elementary_icon.ico) inside `<link rel="icon">` [here ](https://github.com/elementary-data/elementary/blob/bfffc5f021d17a4d95532312ba0c4163ccb4bce7/elementary/monitor/data_monitoring/report/index.html#LL6C1-L6C1) would be fine. What do you suggest?

**Comment by Maayan-s** [comment]
Hi @manulpatel , Thank you! Our FE dev actually added it last night, for several reasons we manage the FE development on a different repo.

**Comment by manulpatel** [comment]
Okay got it! Thanks for the info.

**Comment by Maayan-s** [comment]
<img width="293" alt="image" src="https://github.com/elementary-data/elementary/assets/22072028/50846f71-f968-4ed1-9dff-229850b70fe8">

Released in 0.8.1 🎉 @HotDiggityDogz
