### ISSUE TITLE
Make Elementary test tables as temp tables

### ISSUE THREAD

**Issue by Dineshvrma** [elementary-data/elementary#937]
**Is your feature request related to a problem? Please describe.**
Once elementary is set up in a DBT repository for Snowflake as the underlying Data warehouse. After running the tests there are tables getting created in the elementary schema and as long as the number of tests increases, the tables also increase and might blow up space for unwanted tables.

**Describe the solution you'd like**
These tables can be made temporary and should drop once the session is complete

**Additional context**

<img width="219" alt="Screenshot 2023-06-08 at 9 58 03 AM" src="https://github.com/elementary-data/elementary/assets/32808160/10baae49-a754-4b33-9b7e-270cd89b884b">

**Would you be willing to contribute this feature?**
I would like to contribute, But my availability is minimum given the bandwidth is less for me. But would love to check how to contribute for the same

**Comment by leilafi** [comment]
I'm closing https://github.com/elementary-data/elementary/issues/979 as this feature seems to resolve it. Just wondering if there are any updated on this request?

**Comment by elongl** [comment]
Hi @Dineshvrma, @leilafi !
From [now on](https://github.com/elementary-data/dbt-data-reliability/pull/502/files#diff-40c828ca51eb806aba73532a4a51d075a339b7b5ea7d2e2be800cb61813334e5R1) Elementary's temporary test tables will automatically be deleted.
This change will be released in the upcoming version.
Thanks a lot for opening the issue.
