### ISSUE TITLE
[ELE-1195] Add "hour of day" to seasonality test param

### ISSUE THREAD

**Issue by cfritzlar** [elementary-data/elementary#962]
**Is your feature request related to a problem? Please describe.**

Tests on `volume_anomalies` would help us understand if for certain hours there are too low or high amounts of data coming in.
However we have a dataset where incoming events vary largely depending on the time of day. I.e. during the night at 4 AM we have always very low amounts of data flowing in while at 8 PM there is usually an expected spike etc. - seasonality on an hourly granularity so to say.
While this concept (seasonality) already exists for elementary the only value that can be provided at the moment is `day_of_week`.
To sum it up: at the moment we would never catch an anomaly because without seasonality the upper / lower threshold is way too big for most times of the day.

**Describe the solution you'd like**

To support seasonality also for hours you could add a new value to the `seasonality` parameter, i.e. `time_of_day`.
It would work similar to `day_of_week` but instead of comparing i.e. monday to mondays it would compare 8PM to 8PM etc each day.

**Describe alternatives you've considered**

I think this is actually the place where this config belongs, I also wasn't able to get the desired outcome with different configurations on parameters that already exist.

**Would you be willing to contribute this feature?**

In theory yes, but not sure if I will find the time. Also depends when you can pick up this topic

<sub>[ELE-1195](https://linear.app/elementary/issue/ELE-1195/add-hour-of-day-to-seasonality-test-param)</sub>

**Comment by Maayan-s** [comment]
@cfritzlar Thanks for this! 
Just to make sure - you want this to compare 8PM on Monday to 8PM on previous Mondays or to 8PM anyday? 
Is the relevant seasonality `hour_of_day` or `hour_of_week`?

**Comment by cfritzlar** [comment]
@Maayan-s actually `hour_of_week` would be most beneficial in our case. So taking weekday and hour into account.
Then it would also be consistent in the way it is used to `day_of_week`

**Comment by mossyyy** [comment]
@Maayan-s I spent some time on `hour_of_day` last night and got a working version in our dev environment manually making that changes needed in the elementary package. Do you want me to open a pull request against this ticket once I'm ready for that or do you want to leave this one as `hour_of_week` and I can create a seperate ticket for `hour_of_day`?

**Comment by mossyyy** [comment]
@Maayan-s @NoyaArie I've added hour of week and got a branch ready to push to origin and open a pull request on. Could I please request contributor access so I can open the PR for this? Thanks!

**Comment by Maayan-s** [comment]
Thank you so much @mossyyy!
You can just fork the [dbt package repo](https://github.com/elementary-data/dbt-data-reliability) and open a PR from the fork to master 😊

**Comment by mossyyy** [comment]
Hmm strange.

**Comment by mossyyy** [comment]
@Maayan-s PR is up for this, please let me know if you prefer squashed commits and want me to do a PR into the main repo to update documentation as well for this.
