### ISSUE TITLE
[ELE-1184] Dashboard bug - special characters are wrongly parsed in the report

### ISSUE THREAD

**Issue by assafshayhaimhibob** [elementary-data/elementary#965]
[https://github.com/elementary-data/elementary/pull/947/files](https://github.com/elementary-data/elementary/pull/947/files) - This change caused special characters to be parsed as html (for example "&" turns into "&")

The change was created to avoid failure in the report when users have scripting language in their metadata or description (for example the use of <script> would raise an error)

We need to find a different solution to handle both cases

Example - [https://elementary-community.slack.com/archives/C02CTC89LAX/p1687364002039899](https://elementary-community.slack.com/archives/C02CTC89LAX/p1687364002039899)

see image below:

![](https://uploads.linear.app/56c81801-6242-4fa8-b46c-9e89cdf95c21/fe769784-24f8-4673-be42-3df452cd4f1f/fd725d68-b246-4e90-aaa8-0fb074c3aaa5)

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-1184](https://linear.app/elementary/issue/ELE-1184/dashboard-bug)</sub>

**Comment by elongl** [comment]
For context, we [added escaping to HTML tags](https://github.com/elementary-data/elementary/pull/947/files) which [doesn't crash the report](https://github.com/elementary-data/elementary/issues/940) if there are HTML characters such as `<`, `>`, but it created a different problem in which those characters are displayed incorrectly in queries. We need to fine-tune the escaping.

**Comment by Maayan-s** [comment]
https://elementary-community.slack.com/archives/C02CTC89LAX/p1688991999341169

**Comment by Hadarsagiv** [comment]
[https://elementary-community.slack.com/archives/C03LPJ5EYU9/p1691128208734199](https://elementary-community.slack.com/archives/C03LPJ5EYU9/p1691128208734199)
