### ISSUE TITLE
[ELE-1255] Fix dbt_columns permission issue in BigQuery

### ISSUE THREAD

**Issue by oravi** [elementary-data/elementary#985]
**Relevant community threads -** 

* [https://elementary-community.slack.com/archives/C02CTC89LAX/p1687786100077469](https://elementary-community.slack.com/archives/C02CTC89LAX/p1687786100077469)
* [https://elementary-community.slack.com/archives/C02CTC89LAX/p1684375323318529](https://elementary-community.slack.com/archives/C02CTC89LAX/p1684375323318529)

We have a few options to solve this - 

* Exclude source tables in BigQuery from this view (this is only a workaround)
* Find a way to get the columns from the information schema in BigQuery that won't throw these access violation errors

<sub>From [SyncLinear.com](https://synclinear.com) | [ELE-1255](https://linear.app/elementary/issue/ELE-1255/fix-dbt-columns-permission-issue-in-bigquery)</sub>

**Comment by haritamar** [comment]
Some additional context - there's something in BQ called **Authorized Views** which is intended for this use case, and also has support in dbt.

I'm not sure it's the right solution but it's worth looking into.

**Comment by ofek1weiss** [comment]
authorized views seems to be a solution for the other way around, it lets you create a view for a table you have access to and let people who dont have access to it the ability to query the view,

in our situation, we dont have the access to the table
